//>>built
define("dijit/_editor/plugins/EnterKeyHandling",["dojo/_base/declare","dojo/dom-construct","dojo/_base/event","dojo/keys","dojo/_base/lang","dojo/_base/sniff","dojo/_base/window","dojo/window","../_Plugin","../RichText","../range","../selection"],function(B,j,C,D,u,r,q,y,E,z,g,v){return B("dijit._editor.plugins.EnterKeyHandling",E,{blockNodeForEnter:"BR",constructor:function(a){if(a){if("blockNodeForEnter"in a)a.blockNodeForEnter=a.blockNodeForEnter.toUpperCase();u.mixin(this,a)}},setEditor:function(a){if(this.editor!==
a)if(this.editor=a,this.blockNodeForEnter=="BR")this.editor.customUndo=!0,a.onLoadDeferred.addCallback(u.hitch(this,function(b){this.connect(a.document,"onkeypress",function(a){if(a.charOrCode==D.ENTER){var b=u.mixin({},a);b.shiftKey=!0;this.handleEnterKey(b)||C.stop(a)}});return b}));else if(this.blockNodeForEnter){var b=u.hitch(this,this.handleEnterKey);a.addKeyHandler(13,0,0,b);a.addKeyHandler(13,0,1,b);this.connect(this.editor,"onKeyPressed","onKeyPressed")}},onKeyPressed:function(){if(this._checkListLater){if(q.withGlobal(this.editor.window,
"isCollapsed",dijit)){var a=q.withGlobal(this.editor.window,"getAncestorElement",c,["LI"]);if(a){if(r("mozilla")&&a.parentNode.parentNode.nodeName=="LI")a=a.parentNode.parentNode;var b=a.firstChild;if(b&&b.nodeType==1&&(b.nodeName=="UL"||b.nodeName=="OL")){a.insertBefore(b.ownerDocument.createTextNode("\u00a0"),b);b=g.create(this.editor.window);b.setStart(a.firstChild,0);var c=g.getSelection(this.editor.window,!0);c.removeAllRanges();c.addRange(b)}}else if(z.prototype.execCommand.call(this.editor,
"formatblock",this.blockNodeForEnter),a=q.withGlobal(this.editor.window,"getAncestorElement",c,[this.blockNodeForEnter]))a.innerHTML=this.bogusHtmlContent,r("ie")&&(a=this.editor.document.selection.createRange(),a.move("character",-1),a.select())}this._checkListLater=!1}this._pressedEnterInBlock&&(this._pressedEnterInBlock.previousSibling&&this.removeTrailingBr(this._pressedEnterInBlock.previousSibling),delete this._pressedEnterInBlock)},bogusHtmlContent:"&#160;",blockNodes:/^(?:P|H1|H2|H3|H4|H5|H6|LI)$/,
handleEnterKey:function(a){var F;var b,c,e,m,k,w,l=this.editor.document,n,f,o;if(a.shiftKey){n=q.withGlobal(this.editor.window,"getParentElement",v);if(a=g.getAncestor(n,this.blockNodes)){if(a.tagName=="LI")return!0;b=g.getSelection(this.editor.window);c=b.getRangeAt(0);c.collapsed||(c.deleteContents(),b=g.getSelection(this.editor.window),c=b.getRangeAt(0));if(g.atBeginningOfContainer(a,c.startContainer,c.startOffset))n=l.createElement("br"),e=g.create(this.editor.window),a.insertBefore(n,a.firstChild),
e.setStartAfter(n),b.removeAllRanges(),b.addRange(e);else if(g.atEndOfContainer(a,c.startContainer,c.startOffset))e=g.create(this.editor.window),n=l.createElement("br"),a.appendChild(n),a.appendChild(l.createTextNode("\u00a0")),e.setStart(a.lastChild,0),b.removeAllRanges(),b.addRange(e);else{if((f=c.startContainer)&&f.nodeType==3)return o=f.nodeValue,q.withGlobal(this.editor.window,function(){m=l.createTextNode(o.substring(0,c.startOffset));k=l.createTextNode(o.substring(c.startOffset));w=l.createElement("br");
k.nodeValue==""&&r("webkit")&&(k=l.createTextNode("\u00a0"));j.place(m,f,"after");j.place(w,m,"after");j.place(k,w,"after");j.destroy(f);e=g.create();e.setStart(k,0);b.removeAllRanges();b.addRange(e)}),!1;return!0}}else if(b=g.getSelection(this.editor.window),b.rangeCount){if((c=b.getRangeAt(0))&&c.startContainer)if(c.collapsed||(c.deleteContents(),b=g.getSelection(this.editor.window),c=b.getRangeAt(0)),(f=c.startContainer)&&f.nodeType==3)q.withGlobal(this.editor.window,u.hitch(this,function(){var a=
!1,d=c.startOffset;if(f.length<d)s=this._adjustNodeAndOffset(f,d),f=s.node,d=s.offset;o=f.nodeValue;m=l.createTextNode(o.substring(0,d));k=l.createTextNode(o.substring(d));w=l.createElement("br");k.length||(k=l.createTextNode("\u00a0"),a=!0);m.length?j.place(m,f,"after"):m=f;j.place(w,m,"after");j.place(k,w,"after");j.destroy(f);e=g.create();e.setStart(k,0);e.setEnd(k,k.length);b.removeAllRanges();b.addRange(e);a&&!r("webkit")?v.remove():v.collapse(!0)}));else{var A;c.startOffset>=0&&(A=f.childNodes[c.startOffset]);
q.withGlobal(this.editor.window,u.hitch(this,function(){var a=l.createElement("br"),c=l.createTextNode("\u00a0");A?(j.place(a,A,"before"),j.place(c,a,"after")):(f.appendChild(a),f.appendChild(c));e=g.create(q.global);e.setStart(c,0);e.setEnd(c,c.length);b.removeAllRanges();b.addRange(e);v.collapse(!0)}))}}else z.prototype.execCommand.call(this.editor,"inserthtml","<br>");return!1}var p=!0;b=g.getSelection(this.editor.window);c=b.getRangeAt(0);c.collapsed||(c.deleteContents(),b=g.getSelection(this.editor.window),
c=b.getRangeAt(0));var a=g.getBlockAncestor(c.endContainer,null,this.editor.editNode),d=a.blockNode;if(this._checkListLater=d&&(d.nodeName=="LI"||d.parentNode.nodeName=="LI")){if(r("mozilla"))this._pressedEnterInBlock=d;if(/^(\s|&nbsp;|&#160;|\xA0|<span\b[^>]*\bclass=['"]Apple-style-span['"][^>]*>(\s|&nbsp;|&#160;|\xA0)<\/span>)?(<br>)?$/.test(d.innerHTML))d.innerHTML="",r("webkit")&&(e=g.create(this.editor.window),e.setStart(d,0),b.removeAllRanges(),b.addRange(e)),this._checkListLater=!1;return!0}if(!a.blockNode||
a.blockNode===this.editor.editNode){try{z.prototype.execCommand.call(this.editor,"formatblock",this.blockNodeForEnter)}catch(B){}a={blockNode:q.withGlobal(this.editor.window,"getAncestorElement",v,[this.blockNodeForEnter]),blockContainer:this.editor.editNode};if(a.blockNode){if(a.blockNode!=this.editor.editNode&&!(a.blockNode.textContent||a.blockNode.innerHTML).replace(/^\s+|\s+$/g,"").length)return this.removeTrailingBr(a.blockNode),!1}else a.blockNode=this.editor.editNode;b=g.getSelection(this.editor.window);
c=b.getRangeAt(0)}d=l.createElement(this.blockNodeForEnter);d.innerHTML=this.bogusHtmlContent;this.removeTrailingBr(a.blockNode);var h=c.endOffset,p=c.endContainer;if(p.length<h)var s=this._adjustNodeAndOffset(p,h),p=s.node,h=s.offset;if(g.atEndOfContainer(a.blockNode,p,h))a.blockNode===a.blockContainer?a.blockNode.appendChild(d):j.place(d,a.blockNode,"after"),p=!1,e=g.create(this.editor.window),e.setStart(d,0),b.removeAllRanges(),b.addRange(e),this.editor.height&&y.scrollIntoView(d);else if(g.atBeginningOfContainer(a.blockNode,
c.startContainer,c.startOffset))j.place(d,a.blockNode,a.blockNode===a.blockContainer?"first":"before"),d.nextSibling&&this.editor.height&&(e=g.create(this.editor.window),e.setStart(d.nextSibling,0),b.removeAllRanges(),b.addRange(e),y.scrollIntoView(d.nextSibling)),p=!1;else{a.blockNode===a.blockContainer?a.blockNode.appendChild(d):j.place(d,a.blockNode,"after");p=!1;if(a.blockNode.style&&d.style&&a.blockNode.style.cssText)d.style.cssText=a.blockNode.style.cssText;f=c.startContainer;var i;if(f&&f.nodeType==
3){var x,h=c.endOffset;if(f.length<h)s=this._adjustNodeAndOffset(f,h),f=s.node,h=s.offset;o=f.nodeValue;m=l.createTextNode(o.substring(0,h));k=l.createTextNode(o.substring(h,o.length));j.place(m,f,"before");j.place(k,f,"after");j.destroy(f);for(i=m.parentNode;i!==a.blockNode;){var t=l.createElement(i.tagName);if(i.style&&t.style&&i.style.cssText)t.style.cssText=i.style.cssText;if(i.tagName==="FONT"){if(i.color)t.color=i.color;if(i.face)t.face=i.face;if(i.size)t.size=i.size}for(h=k;h;)x=h.nextSibling,
t.appendChild(h),h=x;j.place(t,i,"after");m=i;k=t;i=i.parentNode}h=k;if(h.nodeType==1||h.nodeType==3&&h.nodeValue)d.innerHTML="";for(i=h;h;)x=h.nextSibling,d.appendChild(h),h=x}e=g.create(this.editor.window);if(this.blockNodeForEnter!=="BR"){for(;i;)n=i,F=x=i.firstChild,i=F;if(n&&n.parentNode){if(d=n.parentNode,e.setStart(d,0),b.removeAllRanges(),b.addRange(e),this.editor.height&&y.scrollIntoView(d),r("mozilla"))this._pressedEnterInBlock=a.blockNode}else p=!0}else if(e.setStart(d,0),b.removeAllRanges(),
b.addRange(e),this.editor.height&&y.scrollIntoView(d),r("mozilla"))this._pressedEnterInBlock=a.blockNode}return p},_adjustNodeAndOffset:function(a,b){for(;a.length<b&&a.nextSibling&&a.nextSibling.nodeType==3;)b-=a.length,a=a.nextSibling;return{node:a,offset:b}},removeTrailingBr:function(a){if(a=/P|DIV|LI/i.test(a.tagName)?a:v.getParentOfType(a,["P","DIV","LI"]))if(a.lastChild&&(a.childNodes.length>1&&a.lastChild.nodeType==3&&/^[\s\xAD]*$/.test(a.lastChild.nodeValue)||a.lastChild.tagName=="BR")&&j.destroy(a.lastChild),
!a.childNodes.length)a.innerHTML=this.bogusHtmlContent}})});