//>>built
define("dijit/_editor/plugins/FontChoice",["dojo/_base/array","dojo/_base/declare","dojo/dom-construct","dojo/i18n","dojo/_base/lang","dojo/store/Memory","dojo/_base/window","../../registry","../../_Widget","../../_TemplatedMixin","../../_WidgetsInTemplateMixin","../../form/FilteringSelect","../_Plugin","../range","../selection","dojo/i18n!../nls/FontChoice"],function(h,e,o,p,l,q,j,r,g,s,t,y,m,n,k){var g=e("dijit._editor.plugins._FontDropDown",[g,s,t],{label:"",plainText:!1,templateString:"<span style='white-space: nowrap' class='dijit dijitReset dijitInline'><label class='dijitLeft dijitInline' for='${selectId}'>${label}</label><input data-dojo-type='dijit.form.FilteringSelect' required='false' data-dojo-props='labelType:\"html\", labelAttr:\"label\", searchAttr:\"name\"' tabIndex='-1' id='${selectId}' data-dojo-attach-point='select' value=''/></span>",
postMixInProperties:function(){this.inherited(arguments);this.strings=p.getLocalization("dijit._editor","FontChoice");this.label=this.strings[this.command];this.id=r.getUniqueId(this.declaredClass.replace(/\./g,"_"));this.selectId=this.id+"_select";this.inherited(arguments)},postCreate:function(){this.select.set("store",new q({idProperty:"value",data:h.map(this.values,function(b){var a=this.strings[b]||b;return{label:this.getLabel(b,a),name:a,value:b}},this)}));this.select.set("value","",!1);this.disabled=
this.select.get("disabled")},_setValueAttr:function(b,a){a=a!==!1;this.select.set("value",h.indexOf(this.values,b)<0?"":b,a);if(!a)this.select._lastValueReported=null},_getValueAttr:function(){return this.select.get("value")},focus:function(){this.select.focus()},_setDisabledAttr:function(b){this.disabled=b;this.select.set("disabled",b)}}),u=e("dijit._editor.plugins._FontNameDropDown",g,{generic:!1,command:"fontName",postMixInProperties:function(){if(!this.values)this.values=this.generic?["serif",
"sans-serif","monospace","cursive","fantasy"]:["Arial","Times New Roman","Comic Sans MS","Courier New"];this.inherited(arguments)},getLabel:function(b,a){return this.plainText?a:"<div style='font-family: "+b+"'>"+a+"</div>"},_setValueAttr:function(b,a){this.generic&&(b={Arial:"sans-serif",Helvetica:"sans-serif",Myriad:"sans-serif",Times:"serif","Times New Roman":"serif","Comic Sans MS":"cursive","Apple Chancery":"cursive",Courier:"monospace","Courier New":"monospace",Papyrus:"fantasy","Estrangelo Edessa":"cursive",
Gabriola:"fantasy"}[b]||b);this.inherited(arguments,[b,a!==!1])}}),v=e("dijit._editor.plugins._FontSizeDropDown",g,{command:"fontSize",values:[1,2,3,4,5,6,7],getLabel:function(b,a){return this.plainText?a:"<font size="+b+"'>"+a+"</font>"},_setValueAttr:function(b,a){a=a!==!1;b.indexOf&&b.indexOf("px")!=-1&&(b={10:1,13:2,16:3,18:4,24:5,32:6,48:7}[parseInt(b,10)]||b);this.inherited(arguments,[b,a])}}),w=e("dijit._editor.plugins._FormatBlockDropDown",g,{command:"formatBlock",values:["noFormat","p","h1",
"h2","h3","pre"],postCreate:function(){this.inherited(arguments);this.set("value","noFormat",!1)},getLabel:function(b,a){return this.plainText||b=="noFormat"?a:"<"+b+">"+a+"</"+b+">"},_execCommand:function(b,a,d){if(d==="noFormat"){var c;if((a=n.getSelection(b.window))&&a.rangeCount>0){var d=a.getRangeAt(0),e;if(d){a=d.startContainer;for(c=d.endContainer;a&&a!==b.editNode&&a!==b.document.body&&a.nodeType!==1;)a=a.parentNode;for(;c&&c!==b.editNode&&c!==b.document.body&&c.nodeType!==1;)c=c.parentNode;
var f=l.hitch(this,function(a,c){if(a.childNodes&&a.childNodes.length){var d;for(d=0;d<a.childNodes.length;d++){var e=a.childNodes[d];if(e.nodeType==1&&j.withGlobal(b.window,"inSelection",k,[e])){var g=e.tagName?e.tagName.toLowerCase():"";h.indexOf(this.values,g)!==-1&&c.push(e);f(e,c)}}}}),d=l.hitch(this,function(a){if(a&&a.length){for(b.beginEditing();a.length;)this._removeFormat(b,a.pop());b.endEditing()}}),i=[];if(a==c){var g;for(c=a;c&&c!==b.editNode&&c!==b.document.body;){if(c.nodeType==1&&
(e=c.tagName?c.tagName.toLowerCase():"",h.indexOf(this.values,e)!==-1)){g=c;break}c=c.parentNode}f(a,i);g&&(i=[g].concat(i))}else for(c=a;j.withGlobal(b.window,"inSelection",k,[c]);)c.nodeType==1&&(e=c.tagName?c.tagName.toLowerCase():"",h.indexOf(this.values,e)!==-1&&i.push(c),f(c,i)),c=c.nextSibling;d(i);b.onDisplayChanged()}}}else b.execCommand(a,d)},_removeFormat:function(b,a){if(b.customUndo){for(;a.firstChild;)o.place(a.firstChild,a,"before");a.parentNode.removeChild(a)}else{j.withGlobal(b.window,
"selectElementChildren",k,[a]);var d=j.withGlobal(b.window,"getSelectedHtml",k,[null]);j.withGlobal(b.window,"selectElement",k,[a]);b.execCommand("inserthtml",d||"")}}}),x=e("dijit._editor.plugins.FontChoice",m,{useDefaultCommand:!1,_initButton:function(){var b={fontName:u,fontSize:v,formatBlock:w}[this.command],a=this.params;if(this.params.custom)a.values=this.params.custom;var d=this.editor;this.button=new b(l.delegate({dir:d.dir,lang:d.lang},a));this.connect(this.button.select,"onChange",function(a){this.editor.focus();
this.command=="fontName"&&a.indexOf(" ")!=-1&&(a="'"+a+"'");this.button._execCommand?this.button._execCommand(this.editor,this.command,a):this.editor.execCommand(this.command,a)})},updateState:function(){var b=this.editor,a=this.command;if(b&&b.isLoaded&&a.length&&this.button){var d=this.get("disabled");this.button.set("disabled",d);if(!d){var c;try{c=b.queryCommandValue(a)||""}catch(e){c=""}(d=l.isString(c)&&c.match(/'([^']*)'/))&&(c=d[1]);if(a==="formatBlock")if(!c||c=="p"){c=null;var f;if((a=n.getSelection(this.editor.window))&&
a.rangeCount>0)if(a=a.getRangeAt(0))f=a.endContainer;for(;f&&f!==b.editNode&&f!==b.document;){if((a=f.tagName?f.tagName.toLowerCase():"")&&h.indexOf(this.button.values,a)>-1){c=a;break}f=f.parentNode}c||(c="noFormat")}else h.indexOf(this.button.values,c)<0&&(c="noFormat");c!==this.button.get("value")&&this.button.set("value",c,!1)}}}});h.forEach(["fontName","fontSize","formatBlock"],function(b){m.registry[b]=function(a){return new x({command:b,plainText:a.plainText})}})});