//>>built
define("dijit/_editor/plugins/FullScreen",["dojo/aspect","dojo/_base/declare","dojo/dom-class","dojo/dom-geometry","dojo/dom-style","dojo/_base/event","dojo/i18n","dojo/keys","dojo/_base/lang","dojo/on","dojo/_base/sniff","dojo/_base/window","dojo/window","../../focus","../_Plugin","../../form/ToggleButton","../../registry","dojo/i18n!../nls/commands"],function(s,t,o,i,f,k,u,p,g,v,l,n,j,q,m,w,x){var r=t("dijit._editor.plugins.FullScreen",m,{zIndex:500,_origState:null,_origiFrameState:null,_resizeHandle:null,
isFullscreen:!1,toggle:function(){this.button.set("checked",!this.button.get("checked"))},_initButton:function(){var a=u.getLocalization("dijit._editor","commands"),c=this.editor;this.button=new w({label:a.fullScreen,dir:c.dir,lang:c.lang,showLabel:!1,iconClass:this.iconClassPrefix+" "+this.iconClassPrefix+"FullScreen",tabIndex:"-1",onChange:g.hitch(this,"_setFullScreen")})},setEditor:function(a){this.editor=a;this._initButton();this.editor.addKeyHandler(p.F11,!0,!0,g.hitch(this,function(a){this.toggle();
k.stop(a);setTimeout(g.hitch(this,function(){this.editor.focus()}),250);return!0}));this.connect(this.editor.domNode,"onkeydown","_containFocus")},_containFocus:function(a){if(this.isFullscreen){var c=this.editor;if(!c.isTabIndent&&c._fullscreen_oldOnKeyDown&&a.keyCode===p.TAB){var b=q.curNode,e=this._getAltViewNode();b==c.iframe||e&&b===e?setTimeout(g.hitch(this,function(){c.toolbar.focus()}),10):e&&f.get(c.iframe,"display")==="none"?setTimeout(g.hitch(this,function(){q.focus(e)}),10):setTimeout(g.hitch(this,
function(){c.focus()}),10);k.stop(a)}else c._fullscreen_oldOnKeyDown&&c._fullscreen_oldOnKeyDown(a)}},_resizeEditor:function(){var a=j.getBox();i.setMarginBox(this.editor.domNode,{w:a.w,h:a.h});var c=this.editor.getHeaderHeight(),b=this.editor.getFooterHeight(),e=i.getPadBorderExtents(this.editor.domNode),d=i.getPadBorderExtents(this.editor.iframe.parentNode),f=i.getMarginExtents(this.editor.iframe.parentNode),c=a.h-(c+e.h+b);i.setMarginBox(this.editor.iframe.parentNode,{h:c,w:a.w});i.setMarginBox(this.editor.iframe,
{h:c-(d.h+f.h)})},_getAltViewNode:function(){},_setFullScreen:function(a){var c=j.getBox(),b=this.editor,e=n.body(),d=b.domNode.parentNode;if(this.isFullscreen=a){for(;d&&d!==n.body();)o.add(d,"dijitForceStatic"),d=d.parentNode;this._editorResizeHolder=this.editor.resize;b.resize=function(){};b._fullscreen_oldOnKeyDown=b.onKeyDown;b.onKeyDown=g.hitch(this,this._containFocus);this._origState={};this._origiFrameState={};d=(a=b.domNode)&&a.style||{};this._origState={width:d.width||"",height:d.height||
"",top:f.get(a,"top")||"",left:f.get(a,"left")||"",position:f.get(a,"position")||"static",marginBox:i.getMarginBox(b.domNode)};a=(a=b.iframe)&&a.style||{};d=f.get(b.iframe,"backgroundColor");this._origiFrameState={backgroundColor:d||"transparent",width:a.width||"auto",height:a.height||"auto",zIndex:a.zIndex||""};f.set(b.domNode,{position:"absolute",top:"0px",left:"0px",zIndex:this.zIndex,width:c.w+"px",height:c.h+"px"});f.set(b.iframe,{height:"100%",width:"100%",zIndex:this.zIndex,backgroundColor:d!==
"transparent"&&d!=="rgba(0, 0, 0, 0)"?d:"white"});f.set(b.iframe.parentNode,{height:"95%",width:"100%"});this._oldOverflow=e.style&&e.style.overflow?f.get(e,"overflow"):"";if(l("ie")&&!l("quirks")){if(e.parentNode&&e.parentNode.style&&e.parentNode.style.overflow)this._oldBodyParentOverflow=e.parentNode.style.overflow;else try{this._oldBodyParentOverflow=f.get(e.parentNode,"overflow")}catch(m){this._oldBodyParentOverflow="scroll"}f.set(e.parentNode,"overflow","hidden")}f.set(e,"overflow","hidden");
this._resizeHandle=v(window,"resize",g.hitch(this,function(){var a=j.getBox();if("_prevW"in this&&"_prevH"in this){if(a.w===this._prevW&&a.h===this._prevH)return}else this._prevW=a.w,this._prevH=a.h;this._resizer&&(clearTimeout(this._resizer),delete this._resizer);this._resizer=setTimeout(g.hitch(this,function(){delete this._resizer;this._resizeEditor()}),10)}));this._resizeHandle2=s.after(b,"onResize",g.hitch(this,function(){this._resizer&&(clearTimeout(this._resizer),delete this._resizer);this._resizer=
setTimeout(g.hitch(this,function(){delete this._resizer;this._resizeEditor()}),10)}));this._resizeEditor();var k=this.editor.toolbar.domNode;setTimeout(function(){j.scrollIntoView(k)},250)}else{if(this._resizeHandle)this._resizeHandle.remove(),this._resizeHandle=null;if(this._resizeHandle2)this._resizeHandle2.remove(),this._resizeHandle2=null;if(this._rst)clearTimeout(this._rst),this._rst=null;for(;d&&d!==n.body();)o.remove(d,"dijitForceStatic"),d=d.parentNode;if(this._editorResizeHolder)this.editor.resize=
this._editorResizeHolder;if(this._origState||this._origiFrameState){if(b._fullscreen_oldOnKeyDown)b.onKeyDown=b._fullscreen_oldOnKeyDown,delete b._fullscreen_oldOnKeyDown;var h=this;setTimeout(function(){var a=h._origState.marginBox,d=h._origState.height;if(l("ie")&&!l("quirks"))e.parentNode.style.overflow=h._oldBodyParentOverflow,delete h._oldBodyParentOverflow;f.set(e,"overflow",h._oldOverflow);delete h._oldOverflow;f.set(b.domNode,h._origState);f.set(b.iframe.parentNode,{height:"",width:""});f.set(b.iframe,
h._origiFrameState);delete h._origState;delete h._origiFrameState;var c=x.getEnclosingWidget(b.domNode.parentNode);c&&c.resize?c.resize():(!d||d.indexOf("%")<0)&&setTimeout(g.hitch(this,function(){b.resize({h:a.h})}),0);j.scrollIntoView(h.editor.toolbar.domNode)},100)}}},updateState:function(){this.button.set("disabled",this.get("disabled"))},destroy:function(){if(this._resizeHandle)this._resizeHandle.remove(),this._resizeHandle=null;if(this._resizeHandle2)this._resizeHandle2.remove(),this._resizeHandle2=
null;if(this._resizer)clearTimeout(this._resizer),this._resizer=null;this.inherited(arguments)}});m.registry.fullScreen=m.registry.fullscreen=function(a){return new r({zIndex:"zIndex"in a?a.zIndex:500})};return r});