//>>built
require({cache:{"url:dijit/templates/TimePicker.html":'<div id="widget_${id}" class="dijitMenu"\n    ><div data-dojo-attach-point="upArrow" class="dijitButtonNode dijitUpArrowButton" data-dojo-attach-event="onmouseenter:_buttonMouse,onmouseleave:_buttonMouse"\n\t\t><div class="dijitReset dijitInline dijitArrowButtonInner" role="presentation">&#160;</div\n\t\t><div class="dijitArrowButtonChar">&#9650;</div></div\n    ><div data-dojo-attach-point="timeMenu,focusNode" data-dojo-attach-event="onclick:_onOptionSelected,onmouseover,onmouseout"></div\n    ><div data-dojo-attach-point="downArrow" class="dijitButtonNode dijitDownArrowButton" data-dojo-attach-event="onmouseenter:_buttonMouse,onmouseleave:_buttonMouse"\n\t\t><div class="dijitReset dijitInline dijitArrowButtonInner" role="presentation">&#160;</div\n\t\t><div class="dijitArrowButtonChar">&#9660;</div></div\n></div>\n'}});
define("dijit/_TimePicker",["dojo/_base/array","dojo/date","dojo/date/locale","dojo/date/stamp","dojo/_base/declare","dojo/dom-class","dojo/dom-construct","dojo/_base/event","dojo/_base/kernel","dojo/keys","dojo/_base/lang","dojo/_base/sniff","dojo/query","dijit/typematic","./_Widget","./_TemplatedMixin","./form/_FormValueWidget","dojo/text!./templates/TimePicker.html"],function(l,m,n,h,o,e,i,g,p,f,q,j,r,k,s,t,v,u){return o("dijit._TimePicker",[s,t],{templateString:u,baseClass:"dijitTimePicker",clickableIncrement:"T00:15:00",
visibleIncrement:"T01:00:00",visibleRange:"T05:00:00",value:new Date,_visibleIncrement:2,_clickableIncrement:1,_totalIncrements:10,constraints:{},serialize:h.toISOString,setValue:function(a){p.deprecated("dijit._TimePicker:setValue() is deprecated.  Use set('value', ...) instead.","","2.0");this.set("value",a)},_setValueAttr:function(a){this._set("value",a);this._showText()},_setFilterStringAttr:function(a){this._set("filterString",a);this._showText()},isDisabledDate:function(){return!1},_getFilteredNodes:function(a,
b,c,d){var e=[],d=d?d.date:this._refDate,f=a,h=this._maxIncrement+Math.abs(f),i=c?-1:1,g=c?1:0,j=1-g;do{f-=g;if(a=this._createOption(f)){if(c&&a.date>d||!c&&a.date<d)break;e[c?"unshift":"push"](a);d=a.date}f+=j}while(e.length<b&&f*i<h);return e},_showText:function(){var a=h.fromISOString;this.timeMenu.innerHTML="";this._clickableIncrementDate=a(this.clickableIncrement);this._visibleIncrementDate=a(this.visibleIncrement);this._visibleRangeDate=a(this.visibleRange);var b=function(a){return a.getHours()*
3600+a.getMinutes()*60+a.getSeconds()},a=b(this._clickableIncrementDate),c=b(this._visibleIncrementDate),b=b(this._visibleRangeDate),d=(this.value||this.currentFocus).getTime();this._refDate=new Date(d-d%(a*1E3));this._refDate.setFullYear(1970,0,1);this._clickableIncrement=1;this._totalIncrements=b/a;this._visibleIncrement=c/a;this._maxIncrement=86400/a;b=Math.min(this._totalIncrements,10);a=this._getFilteredNodes(0,(b>>1)+1,!1);c=[];b-=a.length;d=this._getFilteredNodes(0,b,!0,a[0]);d.length<b&&(c=
this._getFilteredNodes(a.length,b-d.length,!1));l.forEach(d.concat(a,c),function(a){this.timeMenu.appendChild(a)},this)},constructor:function(){this.constraints={}},postMixInProperties:function(){this.inherited(arguments);this._setConstraintsAttr(this.constraints)},_setConstraintsAttr:function(a){q.mixin(this,a);if(!a.locale)a.locale=this.lang},postCreate:function(){this.connect(this.timeMenu,j("ie")?"onmousewheel":"DOMMouseScroll","_mouseWheeled");this._connects.push(k.addMouseListener(this.upArrow,
this,"_onArrowUp",33,250));this._connects.push(k.addMouseListener(this.downArrow,this,"_onArrowDown",33,250));this.inherited(arguments)},_buttonMouse:function(a){e.toggle(a.currentTarget,a.currentTarget==this.upArrow?"dijitUpArrowHover":"dijitDownArrowHover",a.type=="mouseenter"||a.type=="mouseover")},_createOption:function(a){var b=new Date(this._refDate),c=this._clickableIncrementDate;b.setHours(b.getHours()+c.getHours()*a,b.getMinutes()+c.getMinutes()*a,b.getSeconds()+c.getSeconds()*a);this.constraints.selector==
"time"&&b.setFullYear(1970,0,1);c=n.format(b,this.constraints);if(this.filterString&&c.toLowerCase().indexOf(this.filterString)!==0)return null;var d=i.create("div",{"class":this.baseClass+"Item"});d.date=b;d.index=a;i.create("div",{"class":this.baseClass+"ItemInner",innerHTML:c},d);a%this._visibleIncrement<1&&a%this._visibleIncrement>-1?e.add(d,this.baseClass+"Marker"):a%this._clickableIncrement||e.add(d,this.baseClass+"Tick");this.isDisabledDate(b)&&e.add(d,this.baseClass+"ItemDisabled");if(this.value&&
!m.compare(this.value,b,this.constraints.selector))d.selected=!0,e.add(d,this.baseClass+"ItemSelected"),e.contains(d,this.baseClass+"Marker")?e.add(d,this.baseClass+"MarkerSelected"):e.add(d,this.baseClass+"TickSelected"),this._highlightOption(d,!0);return d},_onOptionSelected:function(a){if((a=a.target.date||a.target.parentNode.date)&&!this.isDisabledDate(a))this._highlighted_option=null,this.set("value",a),this.onChange(a)},onChange:function(){},_highlightOption:function(a,b){if(a){if(b)this._highlighted_option&&
this._highlightOption(this._highlighted_option,!1),this._highlighted_option=a;else if(this._highlighted_option!==a)return;else this._highlighted_option=null;e.toggle(a,this.baseClass+"ItemHover",b);e.contains(a,this.baseClass+"Marker")?e.toggle(a,this.baseClass+"MarkerHover",b):e.toggle(a,this.baseClass+"TickHover",b)}},onmouseover:function(a){this._keyboardSelected=null;a=a.target.parentNode===this.timeMenu?a.target:a.target.parentNode;e.contains(a,this.baseClass+"Item")&&this._highlightOption(a,
!0)},onmouseout:function(a){this._keyboardSelected=null;this._highlightOption(a.target.parentNode===this.timeMenu?a.target:a.target.parentNode,!1)},_mouseWheeled:function(a){this._keyboardSelected=null;g.stop(a);this[(j("ie")?a.wheelDelta:-a.detail)>0?"_onArrowUp":"_onArrowDown"]()},_onArrowUp:function(a){!(typeof a=="number"&&a==-1)&&this.timeMenu.childNodes.length&&(a=this._getFilteredNodes(this.timeMenu.childNodes[0].index,1,!0,this.timeMenu.childNodes[0]),a.length&&(this.timeMenu.removeChild(this.timeMenu.childNodes[this.timeMenu.childNodes.length-
1]),this.timeMenu.insertBefore(a[0],this.timeMenu.childNodes[0])))},_onArrowDown:function(a){!(typeof a=="number"&&a==-1)&&this.timeMenu.childNodes.length&&(a=this._getFilteredNodes(this.timeMenu.childNodes[this.timeMenu.childNodes.length-1].index+1,1,!1,this.timeMenu.childNodes[this.timeMenu.childNodes.length-1]),a.length&&(this.timeMenu.removeChild(this.timeMenu.childNodes[0]),this.timeMenu.appendChild(a[0])))},handleKey:function(a){if(a.charOrCode==f.DOWN_ARROW||a.charOrCode==f.UP_ARROW){g.stop(a);
if(this._highlighted_option&&!this._highlighted_option.parentNode)this._highlighted_option=null;var b=this.timeMenu,c=this._highlighted_option||r("."+this.baseClass+"ItemSelected",b)[0];c?b.childNodes.length&&(a.charOrCode==f.DOWN_ARROW&&!c.nextSibling?this._onArrowDown():a.charOrCode==f.UP_ARROW&&!c.previousSibling&&this._onArrowUp(),c=a.charOrCode==f.DOWN_ARROW?c.nextSibling:c.previousSibling):c=b.childNodes[0];this._highlightOption(c,!0);this._keyboardSelected=c;return!1}else if(a.charOrCode==
f.ENTER||a.charOrCode===f.TAB){if(!this._keyboardSelected&&a.charOrCode===f.TAB)return!0;this._highlighted_option&&this._onOptionSelected({target:this._highlighted_option});return a.charOrCode===f.TAB}}})});