//>>built
define("dijit/Calendar",["dojo/_base/array","dojo/date","dojo/date/locale","dojo/_base/declare","dojo/dom-attr","dojo/dom-class","dojo/_base/event","dojo/_base/kernel","dojo/keys","dojo/_base/lang","dojo/_base/sniff","./CalendarLite","./_Widget","./_CssStateMixin","./_TemplatedMixin","./form/DropDownButton","./hccss"],function(i,s,t,g,j,b,k,l,c,m,n,o,h,p,q,r){var e=g("dijit.Calendar",[o,h,p],{cssStateNodes:{decrementMonth:"dijitCalendarArrow",incrementMonth:"dijitCalendarArrow",previousYearLabelNode:"dijitCalendarPreviousYear",
nextYearLabelNode:"dijitCalendarNextYear"},setValue:function(a){l.deprecated("dijit.Calendar:setValue() is deprecated.  Use set('value', ...) instead.","","2.0");this.set("value",a)},_createMonthWidget:function(){return new e._MonthDropDownButton({id:this.id+"_mddb",tabIndex:-1,onMonthSelect:m.hitch(this,"_onMonthSelect"),lang:this.lang,dateLocaleModule:this.dateLocaleModule},this.monthNode)},postCreate:function(){this.inherited(arguments);this.connect(this.domNode,"onkeypress","_onKeyPress");this.connect(this.dateRowsNode,
"onmouseover","_onDayMouseOver");this.connect(this.dateRowsNode,"onmouseout","_onDayMouseOut");this.connect(this.dateRowsNode,"onmousedown","_onDayMouseDown");this.connect(this.dateRowsNode,"onmouseup","_onDayMouseUp")},_onMonthSelect:function(a){this._setCurrentFocusAttr(this.dateFuncObj.add(this.currentFocus,"month",a-this.currentFocus.getMonth()))},_onDayMouseOver:function(a){if((a=b.contains(a.target,"dijitCalendarDateLabel")?a.target.parentNode:a.target)&&(a.dijitDateValue&&!b.contains(a,"dijitCalendarDisabledDate")||
a==this.previousYearLabelNode||a==this.nextYearLabelNode))b.add(a,"dijitCalendarHoveredDate"),this._currentNode=a},_onDayMouseOut:function(a){if(this._currentNode&&!(a.relatedTarget&&a.relatedTarget.parentNode==this._currentNode))a="dijitCalendarHoveredDate",b.contains(this._currentNode,"dijitCalendarActiveDate")&&(a+=" dijitCalendarActiveDate"),b.remove(this._currentNode,a),this._currentNode=null},_onDayMouseDown:function(a){if((a=a.target.parentNode)&&a.dijitDateValue&&!b.contains(a,"dijitCalendarDisabledDate"))b.add(a,
"dijitCalendarActiveDate"),this._currentNode=a},_onDayMouseUp:function(a){(a=a.target.parentNode)&&a.dijitDateValue&&b.remove(a,"dijitCalendarActiveDate")},handleKey:function(a){var f=-1,b,d=this.currentFocus;switch(a.charOrCode){case c.RIGHT_ARROW:f=1;case c.LEFT_ARROW:b="day";this.isLeftToRight()||(f*=-1);break;case c.DOWN_ARROW:f=1;case c.UP_ARROW:b="week";break;case c.PAGE_DOWN:f=1;case c.PAGE_UP:b=a.ctrlKey||a.altKey?"year":"month";break;case c.END:d=this.dateFuncObj.add(d,"month",1),b="day";
case c.HOME:d=new this.dateClassObj(d);d.setDate(1);break;case c.ENTER:case " ":this.set("value",this.currentFocus);break;default:return!0}b&&(d=this.dateFuncObj.add(d,b,f));this._setCurrentFocusAttr(d);return!1},_onKeyPress:function(a){this.handleKey(a)||k.stop(a)},onValueSelected:function(){},onChange:function(a){this.onValueSelected(a)},getClassForDate:function(){}});e._MonthDropDownButton=g("dijit.Calendar._MonthDropDownButton",r,{onMonthSelect:function(){},postCreate:function(){this.inherited(arguments);
this.dropDown=new e._MonthDropDown({id:this.id+"_mdd",onChange:this.onMonthSelect})},_setMonthAttr:function(a){var b=this.dateLocaleModule.getNames("months","wide","standAlone",this.lang,a);this.dropDown.set("months",b);this.containerNode.innerHTML=(n("ie")==6?"":"<div class='dijitSpacer'>"+this.dropDown.domNode.innerHTML+"</div>")+"<div class='dijitCalendarMonthLabel dijitCalendarCurrentMonthLabel'>"+b[a.getMonth()]+"</div>"}});e._MonthDropDown=g("dijit.Calendar._MonthDropDown",[h,q],{months:[],
templateString:"<div class='dijitCalendarMonthMenu dijitMenu' data-dojo-attach-event='onclick:_onClick,onmouseover:_onMenuHover,onmouseout:_onMenuHover'></div>",_setMonthsAttr:function(a){this.domNode.innerHTML=i.map(a,function(a,b){return a?"<div class='dijitCalendarMonthLabel' month='"+b+"'>"+a+"</div>":""}).join("")},_onClick:function(a){this.onChange(j.get(a.target,"month"))},onChange:function(){},_onMenuHover:function(a){b.toggle(a.target,"dijitCalendarMonthLabelHover",a.type=="mouseover")}});
return e});