//>>built
require({cache:{"url:dijit/templates/Dialog.html":'<div class="dijitDialog" role="dialog" aria-labelledby="${id}_title">\n\t<div data-dojo-attach-point="titleBar" class="dijitDialogTitleBar">\n\t<span data-dojo-attach-point="titleNode" class="dijitDialogTitle" id="${id}_title"></span>\n\t<span data-dojo-attach-point="closeButtonNode" class="dijitDialogCloseIcon" data-dojo-attach-event="ondijitclick: onCancel" title="${buttonCancel}" role="button" tabIndex="-1">\n\t\t<span data-dojo-attach-point="closeText" class="closeText" title="${buttonCancel}">x</span>\n\t</span>\n\t</div>\n\t\t<div data-dojo-attach-point="containerNode" class="dijitDialogPaneContent"></div>\n</div>\n'}});
define("dijit/Dialog",["require","dojo/_base/array","dojo/_base/connect","dojo/_base/declare","dojo/_base/Deferred","dojo/dom","dojo/dom-class","dojo/dom-geometry","dojo/dom-style","dojo/_base/event","dojo/_base/fx","dojo/i18n","dojo/_base/kernel","dojo/keys","dojo/_base/lang","dojo/on","dojo/ready","dojo/_base/sniff","dojo/_base/window","dojo/window","dojo/dnd/Moveable","dojo/dnd/TimedMoveable","./focus","./_base/manager","./_Widget","./_TemplatedMixin","./_CssStateMixin","./form/_FormMixin","./_DialogMixin",
"./DialogUnderlay","./layout/ContentPane","dojo/text!./templates/Dialog.html",".","dojo/i18n!./nls/common"],function(x,m,y,q,r,z,n,k,g,o,s,A,B,e,d,t,C,u,v,p,D,E,h,l,M,F,G,H,I,J,K,L,f){var l=q("dijit._DialogBase",[F,H,I,G],{templateString:L,baseClass:"dijitDialog",cssStateNodes:{closeButtonNode:"dijitDialogCloseIcon"},_setTitleAttr:[{node:"titleNode",type:"innerHTML"},{node:"titleBar",type:"attribute"}],open:!1,duration:l.defaultDuration,refocus:!0,autofocus:!0,_firstFocusItem:null,_lastFocusItem:null,
doLayout:!1,draggable:!0,_setDraggableAttr:function(a){this._set("draggable",a)},"aria-describedby":"",maxRatio:0.9,postMixInProperties:function(){var a=A.getLocalization("dijit","common");d.mixin(this,a);this.inherited(arguments)},postCreate:function(){g.set(this.domNode,{display:"none",position:"absolute"});v.body().appendChild(this.domNode);this.inherited(arguments);this.connect(this,"onExecute","hide");this.connect(this,"onCancel","hide");this._modalconnects=[]},onLoad:function(){this._position();
this.autofocus&&i.isTop(this)&&(this._getFocusItems(this.domNode),h.focus(this._firstFocusItem));this.inherited(arguments)},_endDrag:function(){var a=k.position(this.domNode),b=p.getBox();a.y=Math.min(Math.max(a.y,0),b.h-a.h);a.x=Math.min(Math.max(a.x,0),b.w-a.w);this._relativePosition=a;this._position()},_setup:function(){var a=this.domNode;this.titleBar&&this.draggable?(this._moveable=new (u("ie")==6?E:D)(a,{handle:this.titleBar}),this.connect(this._moveable,"onMoveStop","_endDrag")):n.add(a,"dijitDialogFixed");
this.underlayAttrs={dialogId:this.id,"class":m.map(this["class"].split(/\s/),function(a){return a+"_underlay"}).join(" ")}},_size:function(){this._checkIfSingleChild();if(this._singleChild){if(typeof this._singleChildOriginalStyle!="undefined")this._singleChild.domNode.style.cssText=this._singleChildOriginalStyle,delete this._singleChildOriginalStyle}else g.set(this.containerNode,{width:"auto",height:"auto"});var a=k.position(this.domNode),b=p.getBox();b.w*=this.maxRatio;b.h*=this.maxRatio;if(a.w>=
b.w||a.h>=b.h){var w=k.position(this.containerNode),c=Math.min(a.w,b.w)-(a.w-w.w),a=Math.min(a.h,b.h)-(a.h-w.h);if(this._singleChild&&this._singleChild.resize){if(typeof this._singleChildOriginalStyle=="undefined")this._singleChildOriginalStyle=this._singleChild.domNode.style.cssText;this._singleChild.resize({w:c,h:a})}else g.set(this.containerNode,{width:c+"px",height:a+"px",overflow:"auto",position:"relative"})}else this._singleChild&&this._singleChild.resize&&this._singleChild.resize()},_position:function(){if(!n.contains(v.body(),
"dojoMove")){var a=this.domNode,b=p.getBox(),c=this._relativePosition,d=c?null:k.position(a);g.set(a,{left:Math.floor(b.l+(c?c.x:(b.w-d.w)/2))+"px",top:Math.floor(b.t+(c?c.y:(b.h-d.h)/2))+"px"})}},_onKey:function(a){if(a.charOrCode){var b=a.target;a.charOrCode===e.TAB&&this._getFocusItems(this.domNode);var c=this._firstFocusItem==this._lastFocusItem;if(b==this._firstFocusItem&&a.shiftKey&&a.charOrCode===e.TAB)c||h.focus(this._lastFocusItem),o.stop(a);else if(b==this._lastFocusItem&&a.charOrCode===
e.TAB&&!a.shiftKey)c||h.focus(this._firstFocusItem),o.stop(a);else{for(;b;){if(b==this.domNode||n.contains(b,"dijitPopup"))if(a.charOrCode==e.ESCAPE)this.onCancel();else return;b=b.parentNode}if(a.charOrCode!==e.TAB)o.stop(a);else if(!u("opera"))try{this._firstFocusItem.focus()}catch(d){}}}},show:function(){if(!this.open){this._started||this.startup();if(!this._alreadyInitialized)this._setup(),this._alreadyInitialized=!0;this._fadeOutDeferred&&this._fadeOutDeferred.cancel();this._modalconnects.push(t(window,
"scroll",d.hitch(this,"resize")));this._modalconnects.push(t(this.domNode,y._keypress,d.hitch(this,"_onKey")));g.set(this.domNode,{opacity:0,display:""});this._set("open",!0);this._onShow();this._size();this._position();var a;this._fadeInDeferred=new r(d.hitch(this,function(){a.stop();delete this._fadeInDeferred}));a=s.fadeIn({node:this.domNode,duration:this.duration,beforeBegin:d.hitch(this,function(){i.show(this,this.underlayAttrs)}),onEnd:d.hitch(this,function(){this.autofocus&&i.isTop(this)&&
(this._getFocusItems(this.domNode),h.focus(this._firstFocusItem));this._fadeInDeferred.callback(!0);delete this._fadeInDeferred})}).play();return this._fadeInDeferred}},hide:function(){if(this._alreadyInitialized&&this.open){this._fadeInDeferred&&this._fadeInDeferred.cancel();var a;this._fadeOutDeferred=new r(d.hitch(this,function(){a.stop();delete this._fadeOutDeferred}));this._fadeOutDeferred.then(d.hitch(this,"onHide"));a=s.fadeOut({node:this.domNode,duration:this.duration,onEnd:d.hitch(this,function(){this.domNode.style.display=
"none";i.hide(this);this._fadeOutDeferred.callback(!0);delete this._fadeOutDeferred})}).play();if(this._scrollConnected)this._scrollConnected=!1;for(var b;b=this._modalconnects.pop();)b.remove();this._relativePosition&&delete this._relativePosition;this._set("open",!1);return this._fadeOutDeferred}},resize:function(){this.domNode.style.display!="none"&&(f._underlay&&f._underlay.layout(),this._position(),this._size())},destroy:function(){this._fadeInDeferred&&this._fadeInDeferred.cancel();this._fadeOutDeferred&&
this._fadeOutDeferred.cancel();this._moveable&&this._moveable.destroy();for(var a;a=this._modalconnects.pop();)a.remove();i.hide(this);this.inherited(arguments)}}),j=q("dijit.Dialog",[K,l],{});j._DialogBase=l;var i=j._DialogLevelManager={_beginZIndex:950,show:function(a,b){c[c.length-1].focus=h.curNode;var d=f._underlay;!d||d._destroyed?d=f._underlay=new J(b):d.set(a.underlayAttrs);var e=c[c.length-1].dialog?c[c.length-1].zIndex+2:j._DialogLevelManager._beginZIndex;c.length==1&&d.show();g.set(f._underlay.domNode,
"zIndex",e-1);g.set(a.domNode,"zIndex",e);c.push({dialog:a,underlayAttrs:b,zIndex:e})},hide:function(a){if(c[c.length-1].dialog==a){c.pop();var b=c[c.length-1];c.length==1?f._underlay._destroyed||f._underlay.hide():(g.set(f._underlay.domNode,"zIndex",b.zIndex-1),f._underlay.set(b.underlayAttrs));if(a.refocus){a=b.focus;if(b.dialog&&(!a||!z.isDescendant(a,b.dialog.domNode)))b.dialog._getFocusItems(b.dialog.domNode),a=b.dialog._firstFocusItem;a&&a.focus()}}else b=m.indexOf(m.map(c,function(a){return a.dialog}),
a),b!=-1&&c.splice(b,1)},isTop:function(a){return c[c.length-1].dialog==a}},c=j._dialogStack=[{dialog:null,focus:null,underlayAttrs:null}];B.isAsync||C(0,function(){x(["dijit/TooltipDialog"])});return j});