//>>built
require({cache:{"url:dijit/templates/InlineEditBox.html":'<span data-dojo-attach-point="editNode" role="presentation" style="position: absolute; visibility:hidden" class="dijitReset dijitInline"\n\tdata-dojo-attach-event="onkeypress: _onKeyPress"\n\t><span data-dojo-attach-point="editorPlaceholder"></span\n\t><span data-dojo-attach-point="buttonContainer"\n\t\t><button data-dojo-type="dijit.form.Button" data-dojo-props="label: \'${buttonSave}\', \'class\': \'saveButton\'"\n\t\t\tdata-dojo-attach-point="saveButton" data-dojo-attach-event="onClick:save"></button\n\t\t><button data-dojo-type="dijit.form.Button"  data-dojo-props="label: \'${buttonCancel}\', \'class\': \'cancelButton\'"\n\t\t\tdata-dojo-attach-point="cancelButton" data-dojo-attach-event="onClick:cancel"></button\n\t></span\n></span>\n'}});
define("dijit/InlineEditBox",["dojo/_base/array","dojo/_base/declare","dojo/_base/Deferred","dojo/dom-attr","dojo/dom-class","dojo/dom-construct","dojo/dom-style","dojo/_base/event","dojo/i18n","dojo/_base/kernel","dojo/keys","dojo/_base/lang","dojo/_base/sniff","./focus","./_Widget","./_TemplatedMixin","./_WidgetsInTemplateMixin","./_Container","./form/Button","./form/_TextBoxMixin","./form/TextBox","dojo/text!./templates/InlineEditBox.html","dojo/i18n!./nls/common"],function(i,d,q,j,g,m,e,k,r,l,
n,c,s,o,p,h,t,x,y,u,v,w){h=d("dijit._InlineEditor",[p,h,t],{templateString:w,postMixInProperties:function(){this.inherited(arguments);this.messages=r.getLocalization("dijit","common",this.lang);i.forEach(["buttonSave","buttonCancel"],function(a){this[a]||(this[a]=this.messages[a])},this)},buildRendering:function(){this.inherited(arguments);var a=typeof this.editor=="string"?c.getObject(this.editor):this.editor,b=this.sourceStyle,d="line-height:"+b.lineHeight+";",g=e.getComputedStyle(this.domNode);
i.forEach(["Weight","Family","Size","Style"],function(a){g["font"+a]!=b["font"+a]&&(d+="font-"+a+":"+b["font"+a]+";")},this);i.forEach(["marginTop","marginBottom","marginLeft","marginRight"],function(a){this.domNode.style[a]=b[a]},this);var f=this.inlineEditBox.width;f=="100%"?(d+="width:100%;",this.domNode.style.display="block"):d+="width:"+(f+(Number(f)==f?"px":""))+";";f=c.delegate(this.inlineEditBox.editorParams,{style:d,dir:this.dir,lang:this.lang,textDir:this.textDir});f["displayedValue"in a.prototype?
"displayedValue":"value"]=this.value;this.editWidget=new a(f,this.editorPlaceholder);this.inlineEditBox.autoSave&&m.destroy(this.buttonContainer)},postCreate:function(){this.inherited(arguments);var a=this.editWidget;this.inlineEditBox.autoSave?(this.connect(a,"onChange","_onChange"),this.connect(a,"onKeyPress","_onKeyPress")):"intermediateChanges"in a&&(a.set("intermediateChanges",!0),this.connect(a,"onChange","_onIntermediateChange"),this.saveButton.set("disabled",!0))},_onIntermediateChange:function(){this.saveButton.set("disabled",
this.getValue()==this._resetValue||!this.enableSave())},destroy:function(){this.editWidget.destroy(!0);this.inherited(arguments)},getValue:function(){var a=this.editWidget;return String(a.get("displayedValue"in a?"displayedValue":"value"))},_onKeyPress:function(a){this.inlineEditBox.autoSave&&this.inlineEditBox.editing&&!a.altKey&&!a.ctrlKey&&(a.charOrCode==n.ESCAPE?(k.stop(a),this.cancel(!0)):a.charOrCode==n.ENTER&&a.target.tagName=="INPUT"&&(k.stop(a),this._onChange()))},_onBlur:function(){this.inherited(arguments);
this.inlineEditBox.autoSave&&this.inlineEditBox.editing&&(this.getValue()==this._resetValue?this.cancel(!1):this.enableSave()&&this.save(!1))},_onChange:function(){this.inlineEditBox.autoSave&&this.inlineEditBox.editing&&this.enableSave()&&o.focus(this.inlineEditBox.displayNode)},enableSave:function(){return this.editWidget.isValid?this.editWidget.isValid():!0},focus:function(){this.editWidget.focus();setTimeout(c.hitch(this,function(){this.editWidget.focusNode&&this.editWidget.focusNode.tagName==
"INPUT"&&u.selectInputText(this.editWidget.focusNode)}),0)}});d=d("dijit.InlineEditBox",p,{editing:!1,autoSave:!0,buttonSave:"",buttonCancel:"",renderAsHtml:!1,editor:v,editorWrapper:h,editorParams:{},disabled:!1,onChange:function(){},onCancel:function(){},width:"100%",value:"",noValueIndicator:s("ie")<=6?"<span style='font-family: wingdings; text-decoration: underline;'>&#160;&#160;&#160;&#160;&#x270d;&#160;&#160;&#160;&#160;</span>":"<span style='text-decoration: underline;'>&#160;&#160;&#160;&#160;&#x270d;&#160;&#160;&#160;&#160;</span>",
constructor:function(){this.editorParams={}},postMixInProperties:function(){this.inherited(arguments);this.displayNode=this.srcNodeRef;var a={ondijitclick:"_onClick",onmouseover:"_onMouseOver",onmouseout:"_onMouseOut",onfocus:"_onMouseOver",onblur:"_onMouseOut"},b;for(b in a)this.connect(this.displayNode,b,a[b]);this.displayNode.setAttribute("role","button");this.displayNode.getAttribute("tabIndex")||this.displayNode.setAttribute("tabIndex",0);if(!this.value&&!("value"in this.params))this.value=c.trim(this.renderAsHtml?
this.displayNode.innerHTML:this.displayNode.innerText||this.displayNode.textContent||"");if(!this.value)this.displayNode.innerHTML=this.noValueIndicator;g.add(this.displayNode,"dijitInlineEditBoxDisplayMode")},setDisabled:function(a){l.deprecated("dijit.InlineEditBox.setDisabled() is deprecated.  Use set('disabled', bool) instead.","","2.0");this.set("disabled",a)},_setDisabledAttr:function(a){this.domNode.setAttribute("aria-disabled",a?"true":"false");a?this.displayNode.removeAttribute("tabIndex"):
this.displayNode.setAttribute("tabIndex",0);g.toggle(this.displayNode,"dijitInlineEditBoxDisplayModeDisabled",a);this._set("disabled",a)},_onMouseOver:function(){this.disabled||g.add(this.displayNode,"dijitInlineEditBoxDisplayModeHover")},_onMouseOut:function(){g.remove(this.displayNode,"dijitInlineEditBoxDisplayModeHover")},_onClick:function(a){this.disabled||(a&&k.stop(a),this._onMouseOut(),setTimeout(c.hitch(this,"edit"),0))},edit:function(){if(!this.disabled&&!this.editing){this._set("editing",
!0);this._savedPosition=e.get(this.displayNode,"position")||"static";this._savedOpacity=e.get(this.displayNode,"opacity")||"1";this._savedTabIndex=j.get(this.displayNode,"tabIndex")||"0";if(this.wrapperWidget){var a=this.wrapperWidget.editWidget;a.set("displayedValue"in a?"displayedValue":"value",this.value)}else a=m.create("span",null,this.domNode,"before"),this.wrapperWidget=new (typeof this.editorWrapper=="string"?c.getObject(this.editorWrapper):this.editorWrapper)({value:this.value,buttonSave:this.buttonSave,
buttonCancel:this.buttonCancel,dir:this.dir,lang:this.lang,tabIndex:this._savedTabIndex,editor:this.editor,inlineEditBox:this,sourceStyle:e.getComputedStyle(this.displayNode),save:c.hitch(this,"save"),cancel:c.hitch(this,"cancel"),textDir:this.textDir},a),this._started||this.startup();var b=this.wrapperWidget;e.set(this.displayNode,{position:"absolute",opacity:"0"});e.set(b.domNode,{position:this._savedPosition,visibility:"visible",opacity:"1"});j.set(this.displayNode,"tabIndex","-1");q.when(b.editWidget.onLoadDeferred,
function(){setTimeout(function(){b.focus();b._resetValue=b.getValue()},0)})}},_onBlur:function(){this.inherited(arguments)},destroy:function(){this.wrapperWidget&&!this.wrapperWidget._destroyed&&(this.wrapperWidget.destroy(),delete this.wrapperWidget);this.inherited(arguments)},_showText:function(a){e.set(this.wrapperWidget.domNode,{position:"absolute",visibility:"hidden",opacity:"0"});e.set(this.displayNode,{position:this._savedPosition,opacity:this._savedOpacity});j.set(this.displayNode,"tabIndex",
this._savedTabIndex);a&&o.focus(this.displayNode)},save:function(a){!this.disabled&&this.editing&&(this._set("editing",!1),this.set("value",this.wrapperWidget.getValue()),this._showText(a))},setValue:function(a){l.deprecated("dijit.InlineEditBox.setValue() is deprecated.  Use set('value', ...) instead.","","2.0");return this.set("value",a)},_setValueAttr:function(a){a=c.trim(a);this.displayNode.innerHTML=(this.renderAsHtml?a:a.replace(/&/gm,"&amp;").replace(/</gm,"&lt;").replace(/>/gm,"&gt;").replace(/"/gm,
"&quot;").replace(/\n/g,"<br>"))||this.noValueIndicator;this._set("value",a);this._started&&setTimeout(c.hitch(this,"onChange",a),0);this.textDir=="auto"&&this.applyTextDir(this.displayNode,this.displayNode.innerText)},getValue:function(){l.deprecated("dijit.InlineEditBox.getValue() is deprecated.  Use get('value') instead.","","2.0");return this.get("value")},cancel:function(a){!this.disabled&&this.editing&&(this._set("editing",!1),setTimeout(c.hitch(this,"onCancel"),0),this._showText(a))},_setTextDirAttr:function(a){if(!this._created||
this.textDir!=a)this._set("textDir",a),this.applyTextDir(this.displayNode,this.displayNode.innerText),this.displayNode.align=this.dir=="rtl"?"right":"left"}});d._InlineEditor=h;return d});