//>>built
define("dojo/_base/declare",["./kernel","../has","./lang"],function(t,B,v){function p(e,d){throw Error("declare"+(d?" "+d:"")+": "+e);}function C(e,d,a){var b,c,f,h,i,g,j,m=this._inherited=this._inherited||{};typeof e=="string"&&(b=e,e=d,d=a);a=0;h=e.callee;(b=b||h.nom)||p("can't deduce a name to call inherited()",this.declaredClass);i=this.constructor._meta;f=i.bases;j=m.p;if(b!=q){if(m.c!==h&&(j=0,g=f[0],i=g._meta,i.hidden[b]!==h)){(c=i.chains)&&typeof c[b]=="string"&&p("calling chained method with inherited: "+
b,this.declaredClass);do if(i=g._meta,c=g.prototype,i&&(c[b]===h&&c.hasOwnProperty(b)||i.hidden[b]===h))break;while(g=f[++j]);j=g?j:-1}if(g=f[++j])if(c=g.prototype,g._meta&&c.hasOwnProperty(b))a=c[b];else{h=r[b];do if(c=g.prototype,(a=c[b])&&(g._meta?c.hasOwnProperty(b):a!==h))break;while(g=f[++j])}a=g&&a||r[b]}else{if(m.c!==h&&(j=0,(i=f[0]._meta)&&i.ctor!==h)){c=i.chains;for((!c||c.constructor!=="manual")&&p("calling chained constructor with inherited",this.declaredClass);g=f[++j];)if((i=g._meta)&&
i.ctor===h)break;j=g?j:-1}for(;g=f[++j];)if(a=(i=g._meta)?i.ctor:g)break;a=g&&a}m.c=a;m.p=j;if(a)return d===!0?a:a.apply(this,d||e)}function E(e,d){if(typeof e=="string")return this.__inherited(e,d,!0);return this.__inherited(e,!0)}function F(e,d,a){var b=this.getInherited(e,d);if(b)return b.apply(this,a||d||e)}function G(e){for(var d=this.constructor._meta.bases,a=0,b=d.length;a<b;++a)if(d[a]===e)return!0;return this instanceof e}function H(e,d){for(var a in d)a!=q&&d.hasOwnProperty(a)&&(e[a]=d[a]);
if(B("bug-for-in-skips-shadowed"))for(var b=v._extraNames,c=b.length;c;)a=b[--c],a!=q&&d.hasOwnProperty(a)&&(e[a]=d[a])}function I(e){w.safeMixin(this.prototype,e);return this}function J(e,d){return function(){var g;var a=arguments,b=a,c=a[0],f,h;h=e.length;var i;if(!(this instanceof a.callee))return s(a);if(d&&(c&&c.preamble||this.preamble)){i=Array(e.length);i[0]=a;for(f=0;;){if(c=a[0])(c=c.preamble)&&(a=c.apply(this,a)||a);c=e[f].prototype;(c=c.hasOwnProperty("preamble")&&c.preamble)&&(a=c.apply(this,
a)||a);if(++f==h)break;i[f]=a}}for(f=h-1;f>=0;--f)c=e[f],(g=(h=c._meta)?h.ctor:c,c=g)&&c.apply(this,i?i[f]:a);(c=this.postscript)&&c.apply(this,b)}}function K(e,d){return function(){var a=arguments,b=a,c=a[0];if(!(this instanceof a.callee))return s(a);if(d){if(c)(c=c.preamble)&&(b=c.apply(this,b)||b);(c=this.preamble)&&c.apply(this,b)}e&&e.apply(this,a);(c=this.postscript)&&c.apply(this,a)}}function L(e){return function(){var f;var d=arguments,a=0,b,c;if(!(this instanceof d.callee))return s(d);for(;b=
e[a];++a)if(f=(c=b._meta)?c.ctor:b,b=f){b.apply(this,d);break}(b=this.postscript)&&b.apply(this,d)}}function M(e,d,a){return function(){var b,c,f=0,h=1;a&&(f=d.length-1,h=-1);for(;b=d[f];f+=h)c=b._meta,(b=(c?c.hidden:b.prototype)[e])&&b.apply(this,arguments)}}function D(e){z.prototype=e.prototype;e=new z;z.prototype=null;return e}function s(e){var d=e.callee,a=D(d);d.apply(a,e);return a}function w(e,d,a){typeof e!="string"&&(a=d,d=e,e="");var a=a||{},b,c,f,h,i,g,j,m=1,t=d;if(u.call(d)=="[object Array]"){m=
e;f=[];h=[{cls:0,refs:[]}];g={};for(var x=1,s=d.length,o=0,l,y,k,n;o<s;++o){(l=d[o])?u.call(l)!="[object Function]"&&p("mixin #"+o+" is not a callable constructor.",m):p("mixin #"+o+" is unknown. Did you use dojo.require to pull it in?",m);y=l._meta?l._meta.bases:[l];k=0;for(l=y.length-1;l>=0;--l){n=y[l].prototype;if(!n.hasOwnProperty("declaredClass"))n.declaredClass="uniqName_"+N++;n=n.declaredClass;g.hasOwnProperty(n)||(g[n]={count:0,refs:[],cls:y[l]},++x);n=g[n];k&&k!==n&&(n.refs.push(k),++k.count);
k=n}++k.count;h[0].refs.push(k)}for(;h.length;){k=h.pop();f.push(k.cls);for(--x;c=k.refs,c.length==1;){k=c[0];if(!k||--k.count){k=0;break}f.push(k.cls);--x}if(k){o=0;for(s=c.length;o<s;++o)k=c[o],--k.count||h.push(k)}}x&&p("can't build consistent linearization",m);l=d[0];f[0]=l?l._meta&&l===f[f.length-l._meta.bases.length]?l._meta.bases.length:1:0;g=f;f=g[0];m=g.length-f;d=g[m]}else g=[0],d?u.call(d)=="[object Function]"?(f=d._meta,g=g.concat(f?f.bases:d)):p("base class is not a callable constructor.",
e):d!==null&&p("unknown base class. Did you use dojo.require to pull it in?",e);if(d)for(c=m-1;;--c){b=D(d);if(!c)break;f=g[c];(f._meta?H:A)(b,f.prototype);h=new Function;h.superclass=d;h.prototype=b;d=b.constructor=h}else b={};w.safeMixin(b,a);f=a.constructor;if(f!==r.constructor)f.nom=q,b.constructor=f;for(c=m-1;c;--c)(f=g[c]._meta)&&f.chains&&(j=A(j||{},f.chains));b["-chains-"]&&(j=A(j||{},b["-chains-"]));f=!j||!j.hasOwnProperty(q);g[0]=h=j&&j.constructor==="manual"?L(g):g.length==1?K(a.constructor,
f):J(g,f);h._meta={bases:g,hidden:a,chains:j,parents:t,ctor:a.constructor};h.superclass=d&&d.prototype;h.extend=I;h.prototype=b;b.constructor=h;b.getInherited=E;b.isInstanceOf=G;b.inherited=O;b.__inherited=C;if(e)b.declaredClass=e,v.setObject(e,h);if(j)for(i in j)if(b[i]&&typeof j[i]=="string"&&i!=q)f=b[i]=M(i,g,j[i]==="after"),f.nom=i;return h}var A=v.mixin,r=Object.prototype,u=r.toString,z=new Function,N=0,q="constructor",O=t.config.isDebug?F:C;t.safeMixin=w.safeMixin=function(e,d){var a,b;for(a in d)if(b=
d[a],(b!==r[a]||!(a in r))&&a!=q){if(u.call(b)=="[object Function]")b.nom=a;e[a]=b}if(B("bug-for-in-skips-shadowed"))for(var c=v._extraNames,f=c.length;f;)if(a=c[--f],b=d[a],(b!==r[a]||!(a in r))&&a!=q){if(u.call(b)=="[object Function]")b.nom=a;e[a]=b}return e};return t.declare=w});