//>>built
define("dojo/_base/fx",["./kernel","./config","./lang","../Evented","./Color","./connect","./sniff","../dom","../dom-style"],function(b,q,e,r,i,g,s,n,l){var j=e.mixin;b._Line=function(a,d){this.start=a;this.end=d};b._Line.prototype.getValue=function(a){return(this.end-this.start)*a+this.start};b.Animation=function(a){j(this,a);if(e.isArray(this.curve))this.curve=new b._Line(this.curve[0],this.curve[1])};b.Animation.prototype=new r;b._Animation=b.Animation;e.extend(b.Animation,{duration:350,repeat:0,
rate:20,_percent:0,_startRepeatCount:0,_getStep:function(){var a=this._percent,d=this.easing;return d?d(a):a},_fire:function(a,d){var b=d||[];if(this[a])if(q.debugAtAllCosts)this[a].apply(this,b);else try{this[a].apply(this,b)}catch(f){}return this},play:function(a,d){this._delayTimer&&this._clearTimer();if(d)this._stopTimer(),this._active=this._paused=!1,this._percent=0;else if(this._active&&!this._paused)return this;this._fire("beforeBegin",[this.node]);var b=a||this.delay,f=e.hitch(this,"_play",
d);if(b>0)return this._delayTimer=setTimeout(f,b),this;f();return this},_play:function(){this._delayTimer&&this._clearTimer();this._startTime=(new Date).valueOf();this._paused&&(this._startTime-=this.duration*this._percent);this._active=!0;this._paused=!1;var a=this.curve.getValue(this._getStep());if(!this._percent){if(!this._startRepeatCount)this._startRepeatCount=this.repeat;this._fire("onBegin",[a])}this._fire("onPlay",[a]);this._cycle();return this},pause:function(){this._delayTimer&&this._clearTimer();
this._stopTimer();if(!this._active)return this;this._paused=!0;this._fire("onPause",[this.curve.getValue(this._getStep())]);return this},gotoPercent:function(a,b){this._stopTimer();this._active=this._paused=!0;this._percent=a;b&&this.play();return this},stop:function(a){this._delayTimer&&this._clearTimer();if(!this._timer)return this;this._stopTimer();if(a)this._percent=1;this._fire("onStop",[this.curve.getValue(this._getStep())]);this._active=this._paused=!1;return this},status:function(){if(this._active)return this._paused?
"paused":"playing";return"stopped"},_cycle:function(){if(this._active){var a=((new Date).valueOf()-this._startTime)/this.duration;a>=1&&(a=1);this._percent=a;this.easing&&(a=this.easing(a));this._fire("onAnimate",[this.curve.getValue(a)]);if(this._percent<1)this._startTimer();else{this._active=!1;if(this.repeat>0)this.repeat--,this.play(null,!0);else if(this.repeat==-1)this.play(null,!0);else if(this._startRepeatCount)this.repeat=this._startRepeatCount,this._startRepeatCount=0;this._percent=0;this._fire("onEnd",
[this.node]);!this.repeat&&this._stopTimer()}}return this},_clearTimer:function(){clearTimeout(this._delayTimer);delete this._delayTimer}});var h=0,m=null,o={run:function(){}};e.extend(b.Animation,{_startTimer:function(){if(!this._timer)this._timer=g.connect(o,"run",this,"_cycle"),h++;m||(m=setInterval(e.hitch(o,"run"),this.rate))},_stopTimer:function(){if(this._timer)g.disconnect(this._timer),this._timer=null,h--;h<=0&&(clearInterval(m),m=null,h=0)}});var t=s("ie")?function(a){var b=a.style;if(!b.width.length&&
l.get(a,"width")=="auto")b.width="auto"}:function(){};b._fade=function(a){a.node=n.byId(a.node);var d=j({properties:{}},a),a=d.properties.opacity={};a.start=!("start"in d)?function(){return+l.get(d.node,"opacity")||0}:d.start;a.end=d.end;a=b.animateProperty(d);g.connect(a,"beforeBegin",e.partial(t,d.node));return a};b.fadeIn=function(a){return b._fade(j({end:1},a))};b.fadeOut=function(a){return b._fade(j({end:0},a))};b._defaultEasing=function(a){return 0.5+Math.sin((a+1.5)*Math.PI)/2};var p=function(a){this._properties=
a;for(var b in a){var e=a[b];if(e.start instanceof i)e.tempColor=new i}};p.prototype.getValue=function(a){var b={},k;for(k in this._properties){var f=this._properties[k],c=f.start;c instanceof i?b[k]=i.blendColors(c,f.end,a,f.tempColor).toCss():e.isArray(c)||(b[k]=(f.end-c)*a+c+(k!="opacity"?f.units||"px":0))}return b};b.animateProperty=function(a){var d=a.node=n.byId(a.node);if(!a.easing)a.easing=b._defaultEasing;a=new b.Animation(a);g.connect(a,"beforeBegin",a,function(){var a={},b;for(b in this.properties){if(b==
"width"||b=="height")this.node.display="block";var c=this.properties[b];e.isFunction(c)&&(c=c(d));c=a[b]=j({},e.isObject(c)?c:{end:c});if(e.isFunction(c.start))c.start=c.start(d);if(e.isFunction(c.end))c.end=c.end(d);var g=b.toLowerCase().indexOf("color")>=0,h=function(a,b){var c={height:a.offsetHeight,width:a.offsetWidth}[b];if(c!==void 0)return c;c=l.get(a,b);return b=="opacity"?+c:g?c:parseFloat(c)};if("end"in c){if(!("start"in c))c.start=h(d,b)}else c.end=h(d,b);g?(c.start=new i(c.start),c.end=
new i(c.end)):c.start=b=="opacity"?+c.start:parseFloat(c.start)}this.curve=new p(a)});g.connect(a,"onAnimate",e.hitch(l,"set",a.node));return a};b.anim=function(a,d,e,f,c,g){return b.animateProperty({node:a,duration:e||b.Animation.prototype.duration,properties:d,easing:f,onEnd:c}).play(g||0)};return{_Line:b._Line,Animation:b.Animation,_fade:b._fade,fadeIn:b.fadeIn,fadeOut:b.fadeOut,_defaultEasing:b._defaultEasing,animateProperty:b.animateProperty,anim:b.anim}});