//>>built
define("dijit/tree/dndSource",["dojo/_base/array","dojo/_base/connect","dojo/_base/declare","dojo/dom-class","dojo/dom-geometry","dojo/_base/lang","dojo/on","dojo/touch","dojo/topic","dojo/dnd/Manager","./_dndSelector"],function(m,q,r,l,s,j,u,v,k,i,t){return r("dijit.tree.dndSource",t,{isSource:!0,accept:["text","treeNode"],copyOnly:!1,dragThreshold:5,betweenThreshold:0,constructor:function(a,c){c||(c={});j.mixin(this,c);this.isSource=typeof c.isSource=="undefined"?!0:c.isSource;var e=c.accept instanceof
Array?c.accept:["text","treeNode"];this.accept=null;if(e.length){this.accept={};for(var b=0;b<e.length;++b)this.accept[e[b]]=1}this.mouseDown=this.isDragging=!1;this.targetBox=this.targetAnchor=null;this.dropPosition="";this._lastY=this._lastX=0;this.sourceState="";this.isSource&&l.add(this.node,"dojoDndSource");this.targetState="";this.accept&&l.add(this.node,"dojoDndTarget");this.topics=[k.subscribe("/dnd/source/over",j.hitch(this,"onDndSourceOver")),k.subscribe("/dnd/start",j.hitch(this,"onDndStart")),
k.subscribe("/dnd/drop",j.hitch(this,"onDndDrop")),k.subscribe("/dnd/cancel",j.hitch(this,"onDndCancel"))]},checkAcceptance:function(){return!0},copyState:function(a){return this.copyOnly||a},destroy:function(){this.inherited(arguments);for(var a;a=this.topics.pop();)a.remove();this.targetAnchor=null},_onDragMouse:function(a){var c=i.manager(),e=this.targetAnchor,b=this.current,f=this.dropPosition,d="Over";if(b&&this.betweenThreshold>0){if(!this.targetBox||e!=b)this.targetBox=s.position(b.rowNode,
!0);a.pageY-this.targetBox.y<=this.betweenThreshold?d="Before":a.pageY-this.targetBox.y>=this.targetBox.h-this.betweenThreshold&&(d="After")}if(b!=e||d!=f){e&&this._removeItemClass(e.rowNode,f);b&&this._addItemClass(b.rowNode,d);if(b)if(b==this.tree.rootNode&&d!="Over")c.canDrop(!1);else{a=!1;if(c.source==this)for(var h in this.selection)if(this.selection[h].item===b.item){a=!0;break}a?c.canDrop(!1):this.checkItemAcceptance(b.rowNode,c.source,d.toLowerCase())&&!this._isParentChildDrop(c.source,b.rowNode)?
c.canDrop(!0):c.canDrop(!1)}else c.canDrop(!1);this.targetAnchor=b;this.dropPosition=d}},onMouseMove:function(a){if(!(this.isDragging&&this.targetState=="Disabled")){this.inherited(arguments);var c=i.manager();if(this.isDragging)this._onDragMouse(a);else if(this.mouseDown&&this.isSource&&(Math.abs(a.pageX-this._lastX)>=this.dragThreshold||Math.abs(a.pageY-this._lastY)>=this.dragThreshold)){var e=this.getSelectedTreeNodes();if(e.length){if(e.length>1){var b=this.selection,f=0,d=[],h,g;a:for(;h=e[f++];){for(g=
h.getParent();g&&g!==this.tree;g=g.getParent())if(b[g.id])continue a;d.push(h)}e=d}e=m.map(e,function(a){return a.domNode});c.startDrag(this,e,this.copyState(q.isCopyKey(a)))}}}},onMouseDown:function(a){this.mouseDown=!0;this.mouseButton=a.button;this._lastX=a.pageX;this._lastY=a.pageY;this.inherited(arguments)},onMouseUp:function(){if(this.mouseDown)this.mouseDown=!1,this.inherited(arguments)},onMouseOut:function(){this.inherited(arguments);this._unmarkTargetAnchor()},checkItemAcceptance:function(){return!0},
onDndSourceOver:function(a){this!=a?(this.mouseDown=!1,this._unmarkTargetAnchor()):this.isDragging&&i.manager().canDrop(!1)},onDndStart:function(a,c,e){this.isSource&&this._changeState("Source",this==a?e?"Copied":"Moved":"");this._changeState("Target",this.checkAcceptance(a,c)?"":"Disabled");this==a&&i.manager().overSource(this);this.isDragging=!0},itemCreator:function(a){return m.map(a,function(a){return{id:a.id,name:a.textContent||a.innerText||""}})},onDndDrop:function(a,c,e){if(this.containerState==
"Over"){var b=this.tree,f=b.model,d=this.targetAnchor;this.isDragging=!1;var h,g,i;h=d&&d.item||b.item;this.dropPosition=="Before"||this.dropPosition=="After"?(h=d.getParent()&&d.getParent().item||b.item,g=d.getIndexInParent(),this.dropPosition=="After"?(g=d.getIndexInParent()+1,i=d.getNextSibling()&&d.getNextSibling().item):i=d.item):h=d&&d.item||b.item;var j;m.forEach(c,function(b,k){var l=a.getItem(b.id);if(m.indexOf(l.type,"treeNode")!=-1)var n=l.data,o=n.item,p=n.getParent().item;a==this?(typeof g==
"number"&&h==p&&n.getIndexInParent()<g&&(g-=1),f.pasteItem(o,p,h,e,g,i)):f.isItem(o)?f.pasteItem(o,p,h,e,g,i):(j||(j=this.itemCreator(c,d.rowNode,a)),f.newItem(j[k],h,g,i))},this);this.tree._expandNode(d)}this.onDndCancel()},onDndCancel:function(){this._unmarkTargetAnchor();this.mouseDown=this.isDragging=!1;delete this.mouseButton;this._changeState("Source","");this._changeState("Target","")},onOverEvent:function(){this.inherited(arguments);i.manager().overSource(this)},onOutEvent:function(){this._unmarkTargetAnchor();
var a=i.manager();this.isDragging&&a.canDrop(!1);a.outSource(this);this.inherited(arguments)},_isParentChildDrop:function(a,c){if(!a.tree||a.tree!=this.tree)return!1;for(var e=a.tree.domNode,b=a.selection,f=c.parentNode;f!=e&&!b[f.id];)f=f.parentNode;return f.id&&b[f.id]},_unmarkTargetAnchor:function(){if(this.targetAnchor)this._removeItemClass(this.targetAnchor.rowNode,this.dropPosition),this.dropPosition=this.targetBox=this.targetAnchor=null},_markDndStatus:function(a){this._changeState("Source",
a?"Copied":"Moved")}})});