//>>built
define("dojo/dnd/Container",["../_base/array","../_base/connect","../_base/declare","../_base/event","../_base/kernel","../_base/lang","../dom","../dom-class","../dom-construct","../Evented","../query","./common"],function(m,g,j,n,o,k,l,h,i,p,q,e){j=j("dojo.dnd.Container",p,{skipForm:!1,constructor:function(a,b){this.node=l.byId(a);b||(b={});this.creator=b.creator||null;this.skipForm=b.skipForm;this.parent=b.dropParent&&l.byId(b.dropParent);this.map={};this.current=null;this.containerState="";h.add(this.node,
"dojoDndContainer");(!b||!b._skipStartup)&&this.startup();this.events=[g.connect(this.node,"onmouseover",this,"onMouseOver"),g.connect(this.node,"onmouseout",this,"onMouseOut"),g.connect(this.node,"ondragstart",this,"onSelectStart"),g.connect(this.node,"onselectstart",this,"onSelectStart")]},creator:function(){},getItem:function(a){return this.map[a]},setItem:function(a,b){this.map[a]=b},delItem:function(a){delete this.map[a]},forInItems:function(a,b){var b=b||o.global,c=this.map,d=e._empty,f;for(f in c)f in
d||a.call(b,c[f],f,this);return b},clearItems:function(){this.map={}},getAllNodes:function(){return q("> .dojoDndItem",this.parent)},sync:function(){var a={};this.getAllNodes().forEach(function(b){if(b.id){var c=this.getItem(b.id);if(c){a[b.id]=c;return}}else b.id=e.getUniqueId();var c=b.getAttribute("dndType"),d=b.getAttribute("dndData");a[b.id]={data:d||b.innerHTML,type:c?c.split(/\s*,\s*/):["text"]}},this);this.map=a;return this},insertNodes:function(a,b,c){if(this.parent.firstChild)if(b){if(!c)c=
this.parent.firstChild}else{if(c)c=c.nextSibling}else c=null;var d;if(c)for(b=0;b<a.length;++b)d=this._normalizedCreator(a[b]),this.setItem(d.node.id,{data:d.data,type:d.type}),this.parent.insertBefore(d.node,c);else for(b=0;b<a.length;++b)d=this._normalizedCreator(a[b]),this.setItem(d.node.id,{data:d.data,type:d.type}),this.parent.appendChild(d.node);return this},destroy:function(){m.forEach(this.events,g.disconnect);this.clearItems();this.node=this.parent=this.current=null},markupFactory:function(a,
b,c){a._skipStartup=!0;return new c(b,a)},startup:function(){if(!this.parent&&(this.parent=this.node,this.parent.tagName.toLowerCase()=="table")){var a=this.parent.getElementsByTagName("tbody");if(a&&a.length)this.parent=a[0]}this.defaultCreator=e._defaultCreator(this.parent);this.sync()},onMouseOver:function(a){for(var b=a.relatedTarget;b;){if(b==this.node)break;try{b=b.parentNode}catch(c){b=null}}b||(this._changeState("Container","Over"),this.onOverEvent());b=this._getChildByEvent(a);if(this.current!=
b)this.current&&this._removeItemClass(this.current,"Over"),b&&this._addItemClass(b,"Over"),this.current=b},onMouseOut:function(a){for(a=a.relatedTarget;a;){if(a==this.node)return;try{a=a.parentNode}catch(b){a=null}}if(this.current)this._removeItemClass(this.current,"Over"),this.current=null;this._changeState("Container","");this.onOutEvent()},onSelectStart:function(a){(!this.skipForm||!e.isFormElement(a))&&n.stop(a)},onOverEvent:function(){},onOutEvent:function(){},_changeState:function(a,b){var c=
"dojoDnd"+a,d=a.toLowerCase()+"State";h.replace(this.node,c+b,c+this[d]);this[d]=b},_addItemClass:function(a,b){h.add(a,"dojoDndItem"+b)},_removeItemClass:function(a,b){h.remove(a,"dojoDndItem"+b)},_getChildByEvent:function(a){if(a=a.target)for(var b=a.parentNode;b;a=b,b=a.parentNode)if(b==this.parent&&h.contains(a,"dojoDndItem"))return a;return null},_normalizedCreator:function(a,b){var c=(this.creator||this.defaultCreator).call(this,a,b);if(!k.isArray(c.type))c.type=["text"];if(!c.node.id)c.node.id=
e.getUniqueId();h.add(c.node,"dojoDndItem");return c}});e._createNode=function(a){if(!a)return e._createSpan;return function(b){return i.create(a,{innerHTML:b})}};e._createTrTd=function(a){var b=i.create("tr");i.create("td",{innerHTML:a},b);return b};e._createSpan=function(a){return i.create("span",{innerHTML:a})};e._defaultCreatorNodes={ul:"li",ol:"li",div:"div",p:"div"};e._defaultCreator=function(a){var a=a.tagName.toLowerCase(),b=a=="tbody"||a=="thead"?e._createTrTd:e._createNode(e._defaultCreatorNodes[a]);
return function(a,d){var f=a&&k.isObject(a),h,g;f&&a.tagName&&a.nodeType&&a.getAttribute?(h=a.getAttribute("dndData")||a.innerHTML,f=(f=a.getAttribute("dndType"))?f.split(/\s*,\s*/):["text"],g=a):(h=f&&a.data?a.data:a,f=f&&a.type?a.type:["text"],g=(d=="avatar"?e._createSpan:b)(String(h)));if(!g.id)g.id=e.getUniqueId();return{node:g,data:h,type:f}}};return j});