//>>built
define("dojo/_firebug/firebug",["../_base/kernel","require","../_base/html","../_base/sniff","../_base/array","../_base/lang","../_base/event","../_base/unload"],function(e,Z){function t(a){x=a||!x;if(l)l.style.display=x?"block":"none"}function $(a,b,c,d){(a=window.open("","_firebug","status=0,menubar=0,resizable=1,top="+b+",left="+a+",width="+c+",height="+d+",scrollbars=1,addressbar=0"))||alert("Firebug Lite could not open a pop-up window, most likely because of a blocker.\nEither enable pop-ups for this domain, or change the djConfig to popup=false.");
aa(a);b=a.document;b.write('<html style="height:100%;"><head><title>Firebug Lite</title></head>\n<body bgColor="#ccc" style="height:97%;" onresize="opener.onFirebugResize()">\n<div id="fb"></div></body></html>');b.close();return a}function aa(a){var b=new Date;b.setTime(b.getTime()+5184E6);var b=b.toUTCString(),c=a.document,d;a.innerWidth?d=function(){return{w:a.innerWidth,h:a.innerHeight}}:c.documentElement&&c.documentElement.clientWidth?d=function(){return{w:c.documentElement.clientWidth,h:c.documentElement.clientHeight}}:
c.body&&(d=function(){return{w:c.body.clientWidth,h:c.body.clientHeight}});window.onFirebugResize=function(){R(d().h);clearInterval(a._firebugWin_resize);a._firebugWin_resize=setTimeout(function(){document.cookie="_firebugPosition="+[a.screenLeft,a.screenTop,a.outerWidth||a.document.body.offsetWidth,a.outerHeight||a.document.body.offsetHeight].join(",")+"; expires="+b+"; path=/"},5E3)}}function ba(){j=null;p.console&&p.console.clear();i=q=r=h=l=p=null;C=[];n=[];y={}}function ca(){var a=i.value;i.value=
"";u([">  ",a],"command");try{eval(a)}catch(b){}}function R(a){a=a?a-(25+i.offsetHeight+25+a*0.01)+"px":l.offsetHeight-25-i.offsetHeight+"px";h.style.top="25px";h.style.height=a;r.style.height=a;r.style.top="25px";q.style.height=a;q.style.top="25px";i.style.bottom=0;e.addOnWindowUnload(ba)}function u(a,b,c){h?S(a,b,c):C.push([a,b,c])}function da(){var a=C;C=[];for(var b=0;b<a.length;++b)S(a[b][0],a[b][1],a[b][2])}function S(a,b,c){var d=h.scrollTop+h.offsetHeight>=h.scrollHeight,c=c||ea;c(a,b);if(d)h.scrollTop=
h.scrollHeight-h.offsetHeight}function ea(a,b){var c=h.ownerDocument.createElement("div");c.className="logRow"+(b?" logRow-"+b:"");c.innerHTML=a.join("");(n.length?n[n.length-1]:h).appendChild(c)}function fa(a,b){o(a,b);var c=h.ownerDocument.createElement("div");c.className="logGroupBox";(n.length?n[n.length-1]:h).appendChild(c);n.push(c)}function ga(){n.pop()}function o(a,b){var c=[],d=a[0],f=0;typeof d!="string"&&(d="",f=-1);for(var v=ha(d),d=0;d<v.length;++d){var h=v[d];h&&typeof h=="object"?h.appender(a[++f],
c):s(h,c)}v=[];h=[];for(d=f+1;d<a.length;++d)if(s(" ",c),f=a[d],f===void 0||f===null)L(f,c);else if(typeof f=="string")s(f,c);else if(f instanceof Date)s(f.toString(),c);else if(f.nodeType==9)s("[ XmlDoc ]",c);else{var i="_a"+ia++;v.push(i);h.push(f);f='<a id="'+i+'" href="javascript:void(0);">'+D(f)+"</a>";c.push(f+"")}u(c,b);for(d=0;d<v.length;d++)if(c=j.getElementById(v[d]))c.obj=h[d],p.console._connects.push(e.connect(c,"onclick",function(){console.openObjectInspector();try{E(this.obj)}catch(a){this.obj=
a}r.innerHTML="<pre>"+E(this.obj)+"</pre>"}))}function ha(a){for(var b=[],c=/((^%|[^\\]%)(\d+)?(\.)([a-zA-Z]))|((^%|[^\\]%)([a-zA-Z]))/,d={s:s,d:M,i:M,f:ja},f=c.exec(a);f;f=c.exec(a)){var e=f[8]?f[8]:f[5],e=e in d?d[e]:ka,h=f[3]?parseInt(f[3]):f[4]=="."?-1:0;b.push(a.substr(0,f[0][0]=="%"?f.index:f.index+1));b.push({appender:e,precision:h});a=a.substr(f.index+f[0].length)}b.push(a);return b}function k(a){return String(a).replace(/[<>&"']/g,function(a){switch(a){case "<":return"&lt;";case ">":return"&gt;";
case "&":return"&amp;";case "'":return"&#39;";case '"':return"&quot;"}return"?"})}function s(a,b){b.push(k(a+""))}function L(a,b){b.push('<span class="objectBox-null">',k(a+""),"</span>")}function M(a,b){b.push('<span class="objectBox-number">',k(a+""),"</span>")}function ja(a,b){b.push('<span class="objectBox-number">',k(a+""),"</span>")}function ka(a,b){try{if(a===void 0)L("undefined",b);else if(a===null)L("null",b);else if(typeof a=="string")b.push('<span class="objectBox-string">&quot;',k(a+""),
"&quot;</span>");else if(typeof a=="number")M(a,b);else if(typeof a=="function")b.push('<span class="objectBox-function">',D(a),"</span>");else if(a.nodeType==1)b.push('<span class="objectBox-selector">'),b.push('<span class="selectorTag">',k(a.nodeName.toLowerCase()),"</span>"),a.id&&b.push('<span class="selectorId">#',k(a.id),"</span>"),a.className&&b.push('<span class="selectorClass">.',k(a.className),"</span>"),b.push("</span>");else if(typeof a=="object"){var c=a+"",d=/\[object (.*?)\]/.exec(c);
b.push('<span class="objectBox-object">',d?d[1]:c,"</span>")}else s(a,b)}catch(f){}}function F(a,b){if(a.nodeType==1){b.push('<div class="objectBox-element">','&lt;<span class="nodeTag">',a.nodeName.toLowerCase(),"</span>");for(var c=0;c<a.attributes.length;++c){var d=a.attributes[c];d.specified&&b.push('&nbsp;<span class="nodeName">',d.nodeName.toLowerCase(),'</span>=&quot;<span class="nodeValue">',k(d.nodeValue),"</span>&quot;")}if(a.firstChild){b.push('&gt;</div><div class="nodeChildren">');for(c=
a.firstChild;c;c=c.nextSibling)F(c,b);b.push('</div><div class="objectBox-element">&lt;/<span class="nodeTag">',a.nodeName.toLowerCase(),"&gt;</span></div>")}else b.push("/&gt;</div>")}else a.nodeType==3&&b.push('<div class="nodeText">',k(a.nodeValue),"</div>")}function N(a,b,c){document.all?a.attachEvent("on"+b,c):a.addEventListener(b,c,!1)}function G(a){var b=(new Date).getTime();if(b>T+200){var a=e.fixEvent(a),c=e.keys,d=a.keyCode;T=b;if(d==c.F12)t();else if((d==c.NUMPAD_ENTER||d==76)&&a.shiftKey&&
(a.metaKey||a.ctrlKey))t(!0),i&&i.focus();else return;document.all?a.cancelBubble=!0:a.stopPropagation()}}function la(a){var b=e.keys;if(a.keyCode==13&&i.value){var a=i.value,b=(b=z("firebug_history"))?e.fromJson(b):[],c=e.indexOf(b,a);c!=-1&&b.splice(c,1);b.push(a);for(z("firebug_history",e.toJson(b),30);b.length&&!z("firebug_history");)b.shift(),z("firebug_history",e.toJson(b),30);A=null;m=-1;ca()}else if(a.keyCode==27)i.value="";else if(a.keyCode==b.UP_ARROW||a.charCode==b.UP_ARROW)H("older");
else if(a.keyCode==b.DOWN_ARROW||a.charCode==b.DOWN_ARROW)H("newer");else if(a.keyCode==b.HOME||a.charCode==b.HOME)m=1,H("older");else if(a.keyCode==b.END||a.charCode==b.END)m=999999,H("newer")}function H(a){var b=z("firebug_history"),b=b?e.fromJson(b):[];if(b.length){if(A===null)A=i.value;if(m==-1)m=b.length;if(a=="older")--m,m<0&&(m=0);else if(a=="newer"&&(++m,m>b.length))m=b.length;m==b.length?(i.value=A,A=null):i.value=b[m]}}function z(a,b){var c=document.cookie;if(arguments.length==1)return(c=
c.match(RegExp("(?:^|; )"+a+"=([^;]*)")))?decodeURIComponent(c[1]):void 0;else c=new Date,c.setMonth(c.getMonth()+1),document.cookie=a+"="+encodeURIComponent(b)+(c.toUtcString?"; expires="+c.toUTCString():"")}function U(a){return a&&a instanceof Array||typeof a=="array"}function E(a,b,c,d){var c=c||"",b=b||" \t",d=d||[],f;if(a&&a.nodeType==1)return b=[],F(a,b),b.join("");var e=",\n",h=0,i;i=0;for(f in a)i++;if(a instanceof Date)return b+a.toString()+e;var g;a:for(g in a)if(h++,h==i&&(e="\n"),!(a[g]===
window||a[g]===document))if(a[g]===null)c+=b+g+" : NULL"+e;else if(a[g]&&a[g].nodeType)a[g].nodeType!=1&&a[g].nodeType==3&&(c+=b+g+" : [ TextNode "+a[g].data+" ]"+e);else if(typeof a[g]=="object"&&(a[g]instanceof String||a[g]instanceof Number||a[g]instanceof Boolean))c+=b+g+" : "+a[g]+","+e;else if(a[g]instanceof Date)c+=b+g+" : "+a[g].toString()+e;else if(typeof a[g]=="object"&&a[g]){f=0;for(var j;j=d[f];f++)if(a[g]===j){c+=b+g+" : RECURSION"+e;continue a}d.push(a[g]);f=U(a[g])?["[","]"]:["{","}"];
c+=b+g+" : "+f[0]+"\n";c+=E(a[g],b+" \t","",d);c+=b+f[1]+e}else typeof a[g]=="undefined"?c+=b+g+" : undefined"+e:g=="toString"&&typeof a[g]=="function"?(f=a[g](),typeof f=="string"&&f.match(/function ?(.*?)\(/)&&(f=k(D(a[g]))),c+=b+g+" : "+f+e):c+=b+g+" : "+k(D(a[g]))+e;return c}function D(a){var b=a instanceof Error;if(a.nodeType==1)return k("< "+a.tagName.toLowerCase()+' id="'+a.id+'" />');if(a.nodeType==3)return k('[TextNode: "'+a.nodeValue+'"]');var c=a&&(a.id||a.name||a.ObjectID||a.widgetId);
if(!b&&c)return"{"+c+"}";var d=0;if(b)c="[ Error: "+(a.message||a.description||a)+" ]";else if(U(a))c="["+a.slice(0,4).join(","),a.length>4&&(c+=" ... ("+a.length+" items)"),c+="]";else if(typeof a=="function")(a=/function\s*([^\(]*)(\([^\)]*\))[^\{]*\{/.exec(a+""))?(a[1]||(a[1]="function"),c=a[1]+a[2]):c="function()";else if(typeof a!="object"||typeof a=="string")c=a+"";else{var c="{",e;for(e in a){d++;if(d>2)break;c+=e+":"+k(a[e])+"  "}c+="}"}return c}var V=/Trident/.test(window.navigator.userAgent);
if(V){for(var O=["log","info","debug","warn","error"],I=0;I<O.length;I++){var J=O[I];if(console[J]&&!console[J]._fake){var W="_"+O[I];console[W]=console[J];console[J]=function(){var a=W;return function(){console[a](Array.prototype.join.call(arguments," "))}}()}}try{console.clear()}catch(ma){}}if(!e.isFF&&!e.isChrome&&!e.isSafari&&!V&&!window.firebug&&!(typeof console!="undefined"&&console.firebug||e.config.useCustomLogger||e.isAIR)){try{if(window!=window.parent){if(window.parent.console)window.console=
window.parent.console;return}}catch(na){}var j=document,p=window,ia=0,l=null,h=null,r=null,i=null,x=!1,C=[],n=[],y={},K={},q=null,X,P,B=!1,Q=null;document.createElement("div");var w,Y;window.console={_connects:[],log:function(){o(arguments,"")},debug:function(){o(arguments,"debug")},info:function(){o(arguments,"info")},warn:function(){o(arguments,"warning")},error:function(){o(arguments,"error")},assert:function(a,b){if(!a){for(var c=[],d=1;d<arguments.length;++d)c.push(arguments[d]);o(c.length?c:
["Assertion Failure"],"error");throw b?b:"Assertion Failure";}},dir:function(a){a=E(a);a=a.replace(/\n/g,"<br />");a=a.replace(/\t/g,"&nbsp;&nbsp;&nbsp;&nbsp;");u([a],"dir")},dirxml:function(a){var b=[];F(a,b);u(b,"dirxml")},group:function(){u(arguments,"group",fa)},groupEnd:function(){u(arguments,"",ga)},time:function(a){y[a]=(new Date).getTime()},timeEnd:function(a){if(a in y){var b=(new Date).getTime()-y[a];o([a+":",b+"ms"]);delete y[a]}},count:function(a){K[a]||(K[a]=0);K[a]++;o([a+": "+K[a]])},
trace:function(a){for(var a=a||3,b=console.trace.caller,c=0;c<a;c++){for(var d=[],e=0;e<b.arguments.length;e++)d.push(b.arguments[e]);b=b.caller}},profile:function(){this.warn(["profile() not supported."])},profileEnd:function(){},clear:function(){if(h)for(;h.childNodes.length;)e.destroy(h.firstChild);e.forEach(this._connects,e.disconnect)},open:function(){t(!0)},close:function(){x&&t()},_restoreBorder:function(){if(w)w.style.border=Y},openDomInspector:function(){B=!0;h.style.display="none";q.style.display=
"block";r.style.display="none";document.body.style.cursor="pointer";X=e.connect(document,"mousemove",function(a){if(B&&!Q&&(Q=setTimeout(function(){Q=null},50),(a=a.target)&&w!==a)){console._restoreBorder();var b=[];F(a,b);q.innerHTML=b.join("");w=a;Y=w.style.border;w.style.border="#0000FF 1px solid"}});setTimeout(function(){P=e.connect(document,"click",function(){document.body.style.cursor="";B=!B;e.disconnect(P)})},30)},_closeDomInspector:function(){document.body.style.cursor="";e.disconnect(X);
e.disconnect(P);B=!1;console._restoreBorder()},openConsole:function(){h.style.display="block";q.style.display="none";r.style.display="none";console._closeDomInspector()},openObjectInspector:function(){h.style.display="none";q.style.display="none";r.style.display="block";console._closeDomInspector()},recss:function(){var a,b,c;b=document.getElementsByTagName("link");for(a=0;a<b.length;a++)if(c=b[a],c.rel.toLowerCase().indexOf("stylesheet")>=0&&c.href){var d=c.href.replace(/(&|%5C?)forceReload=\d+/,
"");c.href=d+(d.indexOf("?")>=0?"&":"?")+"forceReload="+(new Date).valueOf()}}};e.addOnLoad(function(){if(!l){t(!0);if(e.config.popup){var a="100%",b=document.cookie.match(/(?:^|; )_firebugPosition=([^;]*)/),b=b?b[1].split(","):[2,2,320,480];p=$(b[0],b[1],b[2],b[3]);j=p.document;e.config.debugContainerId="fb";p.console=window.console;p.dojo=window.dojo}else j=document,a=(e.config.debugHeight||300)+"px";var c=j.createElement("link");c.href=Z.toUrl("./firebug.css");c.rel="stylesheet";c.type="text/css";
var d=j.getElementsByTagName("head");d&&(d=d[0]);d||(d=j.getElementsByTagName("html")[0]);e.isIE?window.setTimeout(function(){d.appendChild(c)},0):d.appendChild(c);e.config.debugContainerId&&(l=j.getElementById(e.config.debugContainerId));l||(l=j.createElement("div"),j.body.appendChild(l));l.className+=" firebug";l.style.height=a;l.style.display=x?"block":"none";a=function(a,b,c,d){return'<li class="'+d+'"><a href="javascript:void(0);" onclick="console.'+c+'(); return false;" title="'+b+'">'+a+"</a></li>"};
l.innerHTML='<div id="firebugToolbar">  <ul id="fireBugTabs" class="tabs">'+a("Clear","Remove All Console Logs","clear","")+a("ReCSS","Refresh CSS without reloading page","recss","")+a("Console","Show Console Logs","openConsole","gap")+a("DOM","Show DOM Inspector","openDomInspector","")+a("Object","Show Object Inspector","openObjectInspector","")+(e.config.popup?"":a("Close","Close the console","close","gap"))+'\t</ul></div><input type="text" id="firebugCommandLine" /><div id="firebugLog"></div><div id="objectLog" style="display:none;">Click on an object in the Log display</div><div id="domInspect" style="display:none;">Hover over HTML elements in the main page. Click to hold selection.</div>';
j.getElementById("firebugToolbar");i=j.getElementById("firebugCommandLine");N(i,"keydown",la);N(j,e.isIE||e.isSafari?"keydown":"keypress",G);h=j.getElementById("firebugLog");r=j.getElementById("objectLog");q=j.getElementById("domInspect");j.getElementById("fireBugTabs");R();da()}});var T=(new Date).getTime(),m=-1,A=null;N(document,e.isIE||e.isSafari?"keydown":"keypress",G);(document.documentElement.getAttribute("debug")=="true"||e.config.isDebug)&&t(!0);e.addOnWindowUnload(function(){var a=document,
b=e.isIE||e.isSafari?"keydown":"keypress";document.all?a.detachEvent("on"+b,G):a.removeEventListener(b,G,!1);window.onFirebugResize=null;window.console=null})}});