//>>built
define("dijit/form/_FormSelectWidget",["dojo/_base/array","dojo/aspect","dojo/data/util/sorter","dojo/_base/declare","dojo/dom","dojo/dom-class","dojo/_base/kernel","dojo/_base/lang","dojo/query","./_FormValueWidget"],function(d,i,j,k,l,m,n,e,o,p){return k("dijit.form._FormSelectWidget",p,{multiple:!1,options:null,store:null,query:null,queryOptions:null,onFetch:null,sortByLabel:!0,loadChildrenOnOpen:!1,getOptions:function(a){var b=a,c=this.options||[],f=c.length;if(b===void 0)return c;if(e.isArray(b))return d.map(b,
"return this.getOptions(item);",this);e.isObject(a)&&(d.some(this.options,function(a,c){if(a===b||a.value&&a.value===b.value)return b=c,!0;return!1})||(b=-1));if(typeof b=="string")for(a=0;a<f;a++)if(c[a].value===b){b=a;break}if(typeof b=="number"&&b>=0&&b<f)return this.options[b];return null},addOption:function(a){e.isArray(a)||(a=[a]);d.forEach(a,function(a){a&&e.isObject(a)&&this.options.push(a)},this);this._loadChildren()},removeOption:function(a){e.isArray(a)||(a=[a]);a=this.getOptions(a);d.forEach(a,
function(a){if(a)this.options=d.filter(this.options,function(c){return c.value!==a.value||c.label!==a.label}),this._removeOptionItem(a)},this);this._loadChildren()},updateOption:function(a){e.isArray(a)||(a=[a]);d.forEach(a,function(a){var c=this.getOptions(a),d;if(c)for(d in a)c[d]=a[d]},this);this._loadChildren()},setStore:function(a,b,c){var f=this.store,c=c||{};if(f!==a){for(var h;h=this._notifyConnections.pop();)h.remove();if(a&&a.getFeatures()["dojo.data.api.Notification"])this._notifyConnections=
[i.after(a,"onNew",e.hitch(this,"_onNewItem"),!0),i.after(a,"onDelete",e.hitch(this,"_onDeleteItem"),!0),i.after(a,"onSet",e.hitch(this,"_onSetItem"),!0)];this._set("store",a)}this._onChangeActive=!1;this.options&&this.options.length&&this.removeOption(this.options);a?(this._loadingStore=!0,a.fetch(e.delegate(c,{onComplete:function(g,e){this.sortByLabel&&!c.sort&&g.length&&g.sort(j.createSortFunction([{attribute:a.getLabelAttributes(g[0])[0]}],a));c.onFetch&&(g=c.onFetch.call(this,g,e));d.forEach(g,
function(a){this._addOptionForItem(a)},this);this._loadingStore=!1;this.set("value","_pendingValue"in this?this._pendingValue:b);delete this._pendingValue;this.loadChildrenOnOpen?this._pseudoLoadChildren(g):this._loadChildren();this._fetchedWith=e;this._lastValueReported=this.multiple?[]:null;this._onChangeActive=!0;this.onSetStore();this._handleOnChange(this.value)},scope:this}))):delete this._fetchedWith;return f},_setValueAttr:function(a,b){if(this._loadingStore)this._pendingValue=a;else{var c=
this.getOptions()||[];e.isArray(a)||(a=[a]);d.forEach(a,function(b,f){e.isObject(b)||(b+="");typeof b==="string"&&(a[f]=d.filter(c,function(a){return a.value===b})[0]||{value:"",label:""})},this);a=d.filter(a,function(a){return a&&a.value});if(!this.multiple&&(!a[0]||!a[0].value)&&c.length)a[0]=c[0];d.forEach(c,function(b){b.selected=d.some(a,function(a){return a.value===b.value})});var f=d.map(a,function(a){return a.value}),h=d.map(a,function(a){return a.label});this._set("value",this.multiple?f:
f[0]);this._setDisplay(this.multiple?h:h[0]);this._updateSelection();this._handleOnChange(this.value,b)}},_getDisplayedValueAttr:function(){var a=this.get("value");e.isArray(a)||(a=[a]);a=d.map(this.getOptions(a),function(a){if(a&&"label"in a)return a.label;else if(a)return a.value;return null},this);return this.multiple?a:a[0]},_loadChildren:function(){this._loadingStore||(d.forEach(this._getChildren(),function(a){a.destroyRecursive()}),d.forEach(this.options,this._addOptionItem,this),this._updateSelection())},
_updateSelection:function(){this._set("value",this._getValueFromOpts());var a=this.value;e.isArray(a)||(a=[a]);a&&a[0]&&d.forEach(this._getChildren(),function(b){var c=d.some(a,function(a){return b.option&&a===b.option.value});m.toggle(b.domNode,this.baseClass+"SelectedOption",c);b.domNode.setAttribute("aria-selected",c?"true":"false")},this)},_getValueFromOpts:function(){var a=this.getOptions()||[];if(!this.multiple&&a.length){var b=d.filter(a,function(a){return a.selected})[0];return b&&b.value?
b.value:(a[0].selected=!0,a[0].value)}else if(this.multiple)return d.map(d.filter(a,function(a){return a.selected}),function(a){return a.value})||[];return""},_onNewItem:function(a,b){(!b||!b.parent)&&this._addOptionForItem(a)},_onDeleteItem:function(a){this.removeOption(this.store.getIdentity(a))},_onSetItem:function(a){this.updateOption(this._getOptionObjForItem(a))},_getOptionObjForItem:function(a){var b=this.store,c=b.getLabel(a);return{value:c?b.getIdentity(a):null,label:c,item:a}},_addOptionForItem:function(a){var b=
this.store;b.isItemLoaded(a)?this.addOption(this._getOptionObjForItem(a)):b.loadItem({item:a,onItem:function(a){this._addOptionForItem(a)},scope:this})},constructor:function(a){this._oValue=(a||{}).value||null;this._notifyConnections=[]},buildRendering:function(){this.inherited(arguments);l.setSelectable(this.focusNode,!1)},_fillContent:function(){var a=this.options;if(!a)a=this.options=this.srcNodeRef?o("> *",this.srcNodeRef).map(function(a){if(a.getAttribute("type")==="separator")return{value:"",
label:"",selected:!1,disabled:!1};return{value:a.getAttribute("data-"+n._scopeName+"-value")||a.getAttribute("value"),label:String(a.innerHTML),selected:a.getAttribute("selected")||!1,disabled:a.getAttribute("disabled")||!1}},this):[];this.value?this.multiple&&typeof this.value=="string"&&this._set("value",this.value.split(",")):this._set("value",this._getValueFromOpts())},postCreate:function(){this.inherited(arguments);this.connect(this,"onChange","_updateSelection");this.connect(this,"startup",
"_loadChildren");this._setValueAttr(this.value,null)},startup:function(){this.inherited(arguments);var a=this.store,b={};d.forEach(["query","queryOptions","onFetch"],function(a){this[a]&&(b[a]=this[a]);delete this[a]},this);if(a&&a.getFeatures()["dojo.data.api.Identity"])this.store=null,this.setStore(a,this._oValue,b)},destroy:function(){for(var a;a=this._notifyConnections.pop();)a.remove();this.inherited(arguments)},_addOptionItem:function(){},_removeOptionItem:function(){},_setDisplay:function(){},
_getChildren:function(){return[]},_getSelectedOptionsAttr:function(){return this.getOptions(this.get("value"))},_pseudoLoadChildren:function(){},onSetStore:function(){}})});