//>>built
require({cache:{"url:dijit/form/templates/Select.html":'<table class="dijit dijitReset dijitInline dijitLeft"\n\tdata-dojo-attach-point="_buttonNode,tableNode,focusNode" cellspacing=\'0\' cellpadding=\'0\'\n\trole="combobox" aria-haspopup="true"\n\t><tbody role="presentation"><tr role="presentation"\n\t\t><td class="dijitReset dijitStretch dijitButtonContents dijitButtonNode" role="presentation"\n\t\t\t><span class="dijitReset dijitInline dijitButtonText"  data-dojo-attach-point="containerNode,_popupStateNode"></span\n\t\t\t><input type="hidden" ${!nameAttrSetting} data-dojo-attach-point="valueNode" value="${value}" aria-hidden="true"\n\t\t/></td><td class="dijitReset dijitRight dijitButtonNode dijitArrowButton dijitDownArrowButton"\n\t\t\t\tdata-dojo-attach-point="titleNode" role="presentation"\n\t\t\t><div class="dijitReset dijitArrowButtonInner" role="presentation"></div\n\t\t\t><div class="dijitReset dijitArrowButtonChar" role="presentation">&#9660;</div\n\t\t></td\n\t></tr></tbody\n></table>\n'}});
define("dijit/form/Select",["dojo/_base/array","dojo/_base/declare","dojo/dom-attr","dojo/dom-class","dojo/dom-construct","dojo/dom-geometry","dojo/_base/event","dojo/i18n","dojo/_base/lang","./_FormSelectWidget","../_HasDropDown","../Menu","../MenuItem","../MenuSeparator","../Tooltip","dojo/text!./templates/Select.html","dojo/i18n!./nls/validate"],function(i,c,j,e,k,l,f,m,n,o,p,q,g,r,d,s){var h=c("dijit.form._SelectMenu",q,{buildRendering:function(){this.inherited(arguments);var a=this.menuTableNode=
this.domNode,b=this.domNode=k.create("div",{style:{overflowX:"hidden",overflowY:"scroll"}});a.parentNode&&a.parentNode.replaceChild(b,a);e.remove(a,"dijitMenuTable");b.className=a.className+" dijitSelectMenu";a.className="dijitReset dijitMenuTable";a.setAttribute("role","listbox");b.setAttribute("role","presentation");b.appendChild(a)},postCreate:function(){this.inherited(arguments);this.connect(this.domNode,"onmousemove",f.stop)},resize:function(a){if(a&&(l.setMarginBox(this.domNode,a),"w"in a))this.menuTableNode.style.width=
"100%"}}),c=c("dijit.form.Select",[o,p],{baseClass:"dijitSelect",templateString:s,required:!1,state:"",message:"",tooltipPosition:[],emptyLabel:"&#160;",_isLoaded:!1,_childrenLoaded:!1,_fillContent:function(){this.inherited(arguments);if(this.options.length&&!this.value&&this.srcNodeRef){var a=this.srcNodeRef.selectedIndex||0;this.value=this.options[a>=0?a:0].value}this.dropDown=new h({id:this.id+"_menu"});e.add(this.dropDown.domNode,this.baseClass+"Menu")},_getMenuItemForOption:function(a){if(!a.value&&
!a.label)return new r;else{var b=n.hitch(this,"_setValueAttr",a),a=new g({option:a,label:a.label||this.emptyLabel,onClick:b,dir:this.dir,disabled:a.disabled||!1});a.focusNode.setAttribute("role","listitem");return a}},_addOptionItem:function(a){this.dropDown&&this.dropDown.addChild(this._getMenuItemForOption(a))},_getChildren:function(){if(!this.dropDown)return[];return this.dropDown.getChildren()},_loadChildren:function(a){a===!0?(this.dropDown&&delete this.dropDown.focusedChild,this.options.length?
this.inherited(arguments):(i.forEach(this._getChildren(),function(a){a.destroyRecursive()}),this.dropDown.addChild(new g({label:"&#160;"})))):this._updateSelection();this._isLoaded=!1;this._childrenLoaded=!0;this._loadingStore||this._setValueAttr(this.value)},_setValueAttr:function(){this.inherited(arguments);j.set(this.valueNode,"value",this.get("value"));this.validate(this.focused)},_setDisabledAttr:function(){this.inherited(arguments);this.validate(this.focused)},_setRequiredAttr:function(a){this._set("required",
a);this.focusNode.setAttribute("aria-required",a);this.validate(this.focused)},_setDisplay:function(a){a=a||this.emptyLabel;this.containerNode.innerHTML='<span class="dijitReset dijitInline '+this.baseClass+'Label">'+a+"</span>";this.focusNode.setAttribute("aria-valuetext",a)},validate:function(a){a=this.disabled||this.isValid(a);this._set("state",a?"":"Incomplete");this.focusNode.setAttribute("aria-invalid",a?"false":"true");var b=a?"":this._missingMsg;b&&this.focused&&this._hasBeenBlurred?d.show(b,
this.domNode,this.tooltipPosition,!this.isLeftToRight()):d.hide(this.domNode);this._set("message",b);return a},isValid:function(){return!this.required||this.value===0||!/^\s*$/.test(this.value||"")},reset:function(){this.inherited(arguments);d.hide(this.domNode);this.validate(this.focused)},postMixInProperties:function(){this.inherited(arguments);this._missingMsg=m.getLocalization("dijit.form","validate",this.lang).missingMessage},postCreate:function(){this.inherited(arguments);this.connect(this.domNode,
"onmousemove",f.stop)},_setStyleAttr:function(){this.inherited(arguments);e.toggle(this.domNode,this.baseClass+"FixedWidth",!!this.domNode.style.width)},isLoaded:function(){return this._isLoaded},loadDropDown:function(a){this._loadChildren(!0);this._isLoaded=!0;a()},closeDropDown:function(){this.inherited(arguments);if(this.dropDown&&this.dropDown.menuTableNode)this.dropDown.menuTableNode.style.width=""},uninitialize:function(a){this.dropDown&&!this.dropDown._destroyed&&(this.dropDown.destroyRecursive(a),
delete this.dropDown);this.inherited(arguments)},_onFocus:function(){this.validate(!0);this.inherited(arguments)},_onBlur:function(){d.hide(this.domNode);this.inherited(arguments)}});c._Menu=h;return c});