/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

/*
	This is an optimized version of Dojo, built for deployment and not for
	development. To get sources and documentation, please visit:

		http://dojotoolkit.org
*/

//>>built
(function(a,j){var i,n,g=function(){},c=function(a){for(var d in a)return 0;return 1},o={}.toString,f=function(a){return o.call(a)=="[object Function]"},h=function(a){return o.call(a)=="[object String]"},b=function(a){return o.call(a)=="[object Array]"},l=function(a,d){if(a)for(var b=0;b<a.length;)d(a[b++])},m=function(a,d){for(var b in d)a[b]=d[b];return a},r=function(a,d){return m(Error(a),{src:"dojoLoader",info:d})},p=1,e=function(){return"_"+p++},d=function(a,b,e){return Ca(a,b,e,0,d)},k=this,
q=k.document,t=q&&q.createElement("DiV"),s=d.has=function(a){return u[a]=f(u[a])?u[a](k,q,t):u[a]},u=s.cache=j.hasCache;s.add=function(a,d,b,e){(u[a]===void 0||e)&&(u[a]=d);return b&&s(a)};for(var B in a.has)s.add(B,a.has[B],0,1);var w=0,C=[],Q=0,G=g,S=g,T;d.isXdUrl=g;d.initSyncLoader=function(a,d,b){Q||(Q=a,G=d,S=b);return{sync:"sync",xd:"xd",arrived:2,nonmodule:3,executing:4,executed:5,syncExecStack:C,modules:H,execQ:L,getModule:X,injectModule:ha,setArrived:$,signal:I,finishExec:ca,execModule:da,
dojoRequirePlugin:Q,getLegacyMode:function(){return w},holdIdle:function(){U++},releaseIdle:function(){ea()}}};var O=location.protocol,v=location.host,z=!v;d.isXdUrl=function(a){if(z||/^\./.test(a))return!1;if(/^\/\//.test(a))return!0;return(a=a.match(/^([^\/\:]+\:)\/\/([^\/]+)/))&&(a[1]!=O||a[2]!=v)};s.add("dojo-force-activex-xhr",!q.addEventListener&&window.location.protocol=="file:");s.add("native-xhr",typeof XMLHttpRequest!="undefined");if(s("native-xhr")&&!s("dojo-force-activex-xhr"))T=function(){return new XMLHttpRequest};
else{B=["Msxml2.XMLHTTP","Microsoft.XMLHTTP","Msxml2.XMLHTTP.4.0"];var F;for(i=0;i<3;)try{if(F=B[i++],new ActiveXObject(F))break}catch(A){}T=function(){return new ActiveXObject(F)}}d.getXhr=T;s.add("dojo-gettext-api",1);d.getText=function(a,d,b){var e=T();e.open("GET",ia(a),!1);e.send(null);if(e.status==200||!location.host&&!e.status)b&&b(e.responseText,d);else throw r("xhrFailed",e.status);return e.responseText};var E=new Function("__text","return eval(__text);");d.eval=function(a,d){return E(a+
"\r\n////@ sourceURL="+d)};var J={},I=d.signal=function(a,d){var e=J[a];l(e&&e.slice(0),function(a){a.apply(null,b(d)?d:[d])})},V=d.on=function(a,d){var b=J[a]||(J[a]=[]);b.push(d);return{remove:function(){for(var a=0;a<b.length;a++)if(b[a]===d){b.splice(a,1);break}}}},Y=[],K={},D=[],N={},x={},y=[],H={},R="",Z={},W={};B={};var ka=function(a){for(var d in W){var b=d.match(/^url\:(.+)/);b?Z[Da(b[1],a)]=W[d]:d!="*noref"&&(Z[ja(d,a).mid]=W[d])}W={}},ta=function(a,d,b){d.splice(0,d.length);var e,k=0;for(e in a)d.push([e,
a[e]]),a[e]==b&&(k=e);d.sort(function(a,d){return d[0].length-a[0].length});for(a=0;a<d.length;)b=d[a++],b[2]=RegExp("^"+b[0].replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,function(a){return"\\"+a})+"(/|$)"),b[3]=b[0].length+1;return k},Ea=function(a,d){var b=a.name;b||(b=a,a={name:b});a=m({main:"main",mapProg:[]},a);a.location=(d||"")+(a.location?a.location:b);a.reverseName=ta(a.packageMap,a.mapProg,b);if(!a.main.indexOf("./"))a.main=a.main.substring(2);m(K,a.paths);N[b]=a;x[b]=b},la=function(a,b){for(var e in a){if(e==
"waitSeconds")d.waitms=(a[e]||0)*1E3;e=="cacheBust"&&(R=a[e]?h(a[e])?a[e]:(new Date).getTime()+"":"");if(e=="baseUrl"||e=="combo")d[e]=a[e];if(e=="async"){var k=a[e];d.legacyMode=w=h(k)&&/sync|legacyAsync/.test(k)?k:!k?"sync":!1;d.async=!w}a[e]!==u&&(d.rawConfig[e]=a[e],e!="has"&&s.add("config-"+e,a[e],0,b))}if(!d.baseUrl)d.baseUrl="./";/\/$/.test(d.baseUrl)||(d.baseUrl+="/");for(e in a.has)s.add(e,a.has[e],0,b);l(a.packages,Ea);for(n in a.packagePaths)l(a.packagePaths[n],function(a){Ea(a,n+"/")});
ta(m(K,a.paths),D);l(a.aliases,function(a){h(a[0])&&(a[0]=RegExp("^"+a[0].replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,function(a){return"\\"+a})+"$"));Y.push(a)});ta(m(x,a.packageMap),y);if(a.cache)ka(),W=a.cache,a.cache["*noref"]&&ka();I("config",[a,d.rawConfig])},P,ua,ma=q.getElementsByTagName("script");for(i=0;i<ma.length&&!ua;i++)if((P=ma[i].getAttribute("src"))&&(ua=P.match(/(.*)\/?dojo\.js(\W|$)/i)))a.baseUrl=a.baseUrl||j.baseUrl||ua[1],(P=ma[i].getAttribute("data-dojo-config")||ma[i].getAttribute("djConfig"))&&
(B=d.eval("({ "+P+" })","data-dojo-config"));d.rawConfig={};la(j,1);la(a,1);la(B,1);var fa=function(a){U++;l(a.deps,ha);ea()},Ca=function(a,k,l,c,f){if(h(a)){if((k=X(a,c,!0))&&k.executed)return k.result;throw r("undefinedModule",a);}b(a)||(la(a),a=k,k=l);if(b(a)){for(var l="require*"+e(),q,i=[],p=0;p<a.length;){q=a[p++];if(q in{exports:1,module:1})throw r("illegalModuleId",q);i.push(X(q,c))}k=m(na("",l,0,""),{injected:2,deps:i,def:k||g,require:c?c.require:d});H[k.mid]=k;fa(k);a=U&&d.async;U++;da(k,
a);ea();k.executed||L.push(k);aa()}return f},Fa=function(a){if(!a)return d;var b=a.require;if(!b)b=function(d,e,k){return Ca(d,e,k,a,b)},a.require=m(b,d),b.module=a,b.toUrl=function(d){return Da(d,a)},b.toAbsMid=function(d){return va(d,a)};return b},L=[],oa=[],M={},Ga=function(a){a.injected=1;M[a.mid]=1;a.url&&(M[a.url]=a.pack||1)},$=function(a){a.injected=2;delete M[a.mid];a.url&&delete M[a.url];c(M)&&(pa(),w=="xd"&&(w="sync"))},Ra=d.idle=function(){return!oa.length&&c(M)&&!L.length&&!U},wa=function(a,
d){for(var b=0;b<d.length;b++)if(d[b][2].test(a))return d[b];return 0},Ha=function(a){for(var d=[],b,e,a=a.replace(/\\/g,"/").split("/");a.length;)b=a.shift(),b==".."&&d.length&&e!=".."?(d.pop(),e=d[d.length-1]):b!="."&&d.push(e=b);return d.join("/")},na=function(a,b,e,k,c){var l=d.isXdUrl(k);return{pid:a,mid:b,pack:e,url:k,executed:0,def:0,isXd:l,isAmd:!!(l||N[a]&&N[a].isAmd),cacheId:c}},Ia=function(a,d,b,e,k,c,m,q){var h,g,i,p=0;i=/^\./.test(a);if(/(^\/)|(\:)|(\.js$)/.test(a)||i&&!d)return na(0,
a,0,a);else{a=Ha(i?d.mid+"/../"+a:a);if(/^\./.test(a))throw r("irrationalPath",a);if(i=(d=d&&d.pack&&d.pack.mapProg)&&wa(a,d)||wa(a,c)){d=i[1];a=a.substring(i[3]);h=b[d];if(!a)a=h.main;g=a;p=h.reverseName+"/"+a;a=d+"/"+a}else d="";var t=0;l(Y,function(d){var b=a.match(d[0]);b&&b.length>0&&(t=f(d[1])?a.replace(d[0],d[1]):d[1])});if(t)return Ia(t,0,b,e,k,c,m,q);if(b=e[a])return q?na(b.pid,b.mid,b.pack,b.url,p):e[a]}e=(i=wa(a,m))?i[1]+a.substring(i[3]-1):d?h.location+"/"+g:s("config-tlmSiblingOfDojo")?
"../"+a:a;/(^\/)|(\:)/.test(e)||(e=k+e);e+=".js";return na(d,a,h,Ha(e),p)},ja=function(a,b){return Ia(a,b,N,H,d.baseUrl,y,D)},Ja=function(a,d,b){return a.normalize?a.normalize(d,function(a){return va(a,b)}):va(d,b)},Ka=0,X=function(a,d,b){var e,k;(e=a.match(/^(.+?)\!(.*)$/))?(k=X(e[1],d,b),w=="sync"&&!k.executed&&(ha(k),k.injected===2&&!k.executed&&(U++,da(k),ea()),k.executed?qa(k):L.unshift(k)),k.executed===5&&!k.load&&qa(k),k.load?(e=Ja(k,e[2],d),a=k.mid+"!"+(k.dynamic?++Ka+"!":"")+e):(e=e[2],a=
k.mid+"!"+ ++Ka+"!waitingForPlugin"),a={plugin:k,mid:a,req:Fa(d),prid:e}):a=ja(a,d);return H[a.mid]||!b&&(H[a.mid]=a)},va=d.toAbsMid=function(a,d){return ja(a,d).mid},Da=d.toUrl=function(a,d){var b=a.match(/(.+)(\.[^\/\.]+?)$/),e=b&&b[2]||"",b=ja(b&&b[1]||a,d),k=b.url,k=typeof b.pid=="string"?k.substring(0,k.length-3):k;return ia(k+e)},La={injected:2,executed:5,def:3,result:3};P=function(a){return H[a]=m({mid:a},La)};var Sa=P("require"),Ta=P("exports"),Ua=P("module"),ra={},xa=0,qa=function(a){var d=
a.result;a.dynamic=d.dynamic;a.normalize=d.normalize;a.load=d.load;return a},Va=function(a){var d={};l(a.loadQ,function(b){var e=Ja(a,b.prid,b.req.module),k=a.dynamic?b.mid.replace(/waitingForPlugin$/,e):a.mid+"!"+e,e=m(m({},b),{mid:k,prid:e,injected:0});H[k]||Ma(H[k]=e);d[b.mid]=H[k];$(b);delete H[b.mid]});a.loadQ=0;var b=function(a){for(var b=a.deps||[],e=0;e<b.length;e++)(a=d[b[e].mid])&&(b[e]=a)},e;for(e in H)b(H[e]);l(L,b)},ca=function(a){d.trace("loader-finish-exec",[a.mid]);a.executed=5;a.defOrder=
xa++;l(a.provides,function(a){a()});a.loadQ&&(qa(a),Va(a));for(i=0;i<L.length;)L[i]===a?L.splice(i,1):i++},Wa=[],da=function(a,b){if(a.executed===4)return d.trace("loader-circular-dependency",[Wa.concat(e).join("->")]),!a.def||b?ra:a.cjs&&a.cjs.exports;if(!a.executed){if(!a.def)return ra;var e=a.mid,k=a.deps||[],c,l=[],m=0;for(a.executed=4;m<k.length;){c=k[m++];c=c===Sa?Fa(a):c===Ta?a.cjs.exports:c===Ua?a.cjs:da(c,b);if(c===ra)return a.executed=0,d.trace("loader-exec-module",["abort",e]),ra;l.push(c)}d.trace("loader-run-factory",
[a.mid]);var e=a.def,q;C.unshift(a);if(s("config-dojo-loader-catches"))try{q=f(e)?e.apply(null,l):e}catch(h){I("error",a.result=r("factoryThrew",[a,h]))}else q=f(e)?e.apply(null,l):e;a.result=q===void 0&&a.cjs?a.cjs.exports:q;C.shift(a);ca(a)}return a.result},U=0,aa=function(){if(!U){U++;G();for(var a,d,b=0;b<L.length;)a=xa,d=L[b],da(d),a!=xa?(G(),b=0):b++;ea()}},ea=function(){U--;Ra()&&I("idle",[])},ia=function(a){a+="";return a+(R?(/\?/.test(a)?"&":"?")+R:"")},Ma=function(a){var d=a.plugin;d.executed===
5&&!d.load&&qa(d);var b=function(d){a.result=d;$(a);ca(a);aa()};Ga(a);d.load?d.load(a.prid,a.req,b):d.loadQ?d.loadQ.push(a):(L.unshift(d),ha(d),d.load?d.load(a.prid,a.req,b):d.loadQ=[a])},ba=0,ga=0,ya=0,za=function(a,b){ya=1;if(s("config-dojo-loader-catches"))try{a===ba?ba.call(null):d.eval(a,b.mid)}catch(e){I("error",r("evalModuleThrew",b))}else a===ba?ba.call(null):d.eval(a,b.mid);ya=0},ha=function(a){var b=a.mid,e=a.url;if(!a.executed&&!a.injected&&!(M[b]||a.url&&(a.pack&&M[a.url]===a.pack||M[a.url]==
1)))if(a.plugin)Ma(a);else{Ga(a);var k=function(){Na(a);a.injected!==2&&($(a),m(a,La));w?!C.length&&aa():aa()};if(ba=Z[b]||Z[a.cacheId])d.trace("loader-inject",["cache",a.mid,e]),za(ba,a),k();else{if(w)if(a.isXd)w=="sync"&&(w="xd");else if(!(a.isAmd&&w!="sync")){var c=function(c){if(w=="sync"){C.unshift(a);za(c,a);C.shift();Na(a);a.cjs||($(a),ca(a));if(a.finish){var c=b+"*finish",m=a.finish;delete a.finish;Aa(c,["dojo",("dojo/require!"+m.join(",")).replace(/\./g,"/")],function(a){l(m,function(d){a.require(d)})});
L.unshift(X(c))}k()}else(c=S(a,c))?(za(c,a),k()):(ga=a,d.injectUrl(ia(e),k,a),ga=0)};d.trace("loader-inject",["xhr",a.mid,e,w!="sync"]);if(s("config-dojo-loader-catches"))try{d.getText(e,w!="sync",c)}catch(f){I("error",r("xhrInjectFailed",[a,f]))}else d.getText(e,w!="sync",c);return}d.trace("loader-inject",["script",a.mid,e]);ga=a;d.injectUrl(ia(e),k,a);ga=0}}},Ba=function(a,b,e){d.trace("loader-define-module",[a.mid,b]);var k=a.mid;if(a.injected===2)return I("error",r("multipleDefine",a)),a;m(a,
{deps:b,def:e,cjs:{id:a.mid,uri:a.url,exports:a.result={},setExports:function(d){a.cjs.exports=d}}});for(var c=0;c<b.length;c++)b[c]=X(b[c],a);w&&!M[k]&&(fa(a),L.push(a),aa());$(a);if(!f(e)&&!b.length)a.result=e,ca(a);return a},Na=function(a,d){ka(a);for(var b=[],e,k;oa.length;)k=oa.shift(),d&&(k[0]=d.shift()),e=k[0]&&X(k[0])||a,b.push(Ba(e,k[1],k[2]));l(b,fa)},sa=0,pa=g,Oa=g,pa=function(){sa&&clearTimeout(sa);sa=0},Oa=function(){pa();d.waitms&&(sa=setTimeout(function(){pa();I("error",r("timeout",
M))},d.waitms))};s.add("ie-event-behavior",q.attachEvent&&(typeof opera==="undefined"||opera.toString()!="[object Opera]"));var Pa=function(a,d,b,e){return s("ie-event-behavior")?(a.attachEvent(b,e),function(){a.detachEvent(b,e)}):(a.addEventListener(d,e,!1),function(){a.removeEventListener(d,e,!1)})},Xa=Pa(window,"load","onload",function(){d.pageLoaded=1;q.readyState!="complete"&&(q.readyState="complete");Xa()}),Qa=q.getElementsByTagName("script")[0],Ya=Qa.parentNode;d.injectUrl=function(a,d,b){Oa();
var b=b.node=q.createElement("script"),e=Pa(b,"load","onreadystatechange",function(a){var a=a||window.event,b=a.target||a.srcElement;if(a.type==="load"||/complete|loaded/.test(b.readyState))e(),d&&d()});b.type="text/javascript";b.charset="utf-8";b.src=a;Ya.insertBefore(b,Qa);return b};d.log=function(){try{for(var a=0;a<arguments.length;a++);}catch(d){}};d.trace=g;var Aa=function(a,e,k){var c=arguments.length,l=0,m=["require","exports","module"];l||(l=c==1?[0,m,a]:c==2?b(a)?[0,a,e]:f(e)?[a,m,e]:[a,
[],e]:[a,e,k]);d.trace("loader-define",l.slice(0,2));if((c=l[0]&&X(l[0]))&&!M[c.mid])fa(Ba(c,l[1],l[2]));else if(!s("ie-event-behavior")||ya)oa.push(l);else{c=c||ga;if(!c)for(a in M)if((m=H[a])&&m.node&&m.node.readyState==="interactive"){c=m;break}c?(ka(c),fa(Ba(c,l[1],l[2]))):I("error",r("ieDefineFailed",l[0]));aa()}};Aa.amd={vendor:"dojotoolkit.org"};m(m(d,j.loaderPatch),a.loaderPatch);V("error",function(a){try{if(a instanceof Error)for(var d in a);}catch(b){}});m(d,{uid:e,cache:Z,packs:N});k.define?
I("error",r("defineAlreadyDefined",0)):(k.define=Aa,k.require=d);P=j.deps||a.deps||B.deps;B=j.deps||a.callback||B.callback;d.boot=P||B?[P||[],B]:0})(this.dojoConfig||this.djConfig||this.require||{},{async:0,hasCache:{"config-selectorEngine":"acme","dojo-built":1,"dojo-loader":1,dom:1,"host-browser":1},packages:[{location:".",name:"dojo"},{location:"../dijit",name:"dijit"}]});
require({cache:{"dojo/main":function(){define(["./_base/kernel","./has","require","./_base/sniff","./_base/lang","./_base/array","./_base/config","./ready","./_base/declare","./_base/connect","./_base/Deferred","./_base/json","./_base/Color","./has!dojo-firebug?./_firebug/firebug","./_base/browser","./_base/loader"],function(a,j,i,n,g,c,o,f){o.isDebug&&i(["./_firebug/firebug"]);var h=o.require;h&&(h=c.map(g.isArray(h)?h:[h],function(a){return a.replace(/\./g,"/")}),a.isAsync?i(h):f(1,function(){i(h)}));
return a})},"dojo/_base/kernel":function(){define(["../has","./config","require","module"],function(a,j,i,n){var g,c={},o={},f={config:j,global:this,dijit:c,dojox:o},c={dojo:["dojo",f],dijit:["dijit",c],dojox:["dojox",o]},n=i.packs&&i.packs[n.id.match(/[^\/]+/)[0]].packageMap||{};for(g in n)c[g]?c[g][0]=n[g]:c[g]=[n[g],{}];for(g in c)n=c[g],n[1]._scopeName=n[0],j.noGlobals||(this[n[0]]=n[1]);f.scopeMap=c;f.baseUrl=f.config.baseUrl=i.baseUrl;f.isAsync=i.async;f.locale=j.locale;n="$Rev$".match(/\d+/);
f.version={major:1,minor:8,patch:0,flag:"dev",revision:n?+n[0]:NaN,toString:function(){var a=f.version;return a.major+"."+a.minor+"."+a.patch+a.flag+" ("+a.revision+")"}};f.eval=i.eval;f.exit=function(){};typeof console!="undefined"||(console={});for(var c=["assert","count","debug","dir","dirxml","error","group","groupEnd","info","profile","profileEnd","time","timeEnd","trace","warn","log"],h,n=0;h=c[n++];)console[h]||function(){var a=h+"";console[a]="log"in console?function(){var c=Array.apply({},
arguments);c.unshift(a+":");console.log(c.join(" "))}:function(){};console[a]._fake=!0}();a.add("dojo-debug-messages",!!j.isDebug);a("dojo-debug-messages")?(f.deprecated=function(){},f.experimental=function(){}):f.deprecated=f.experimental=function(){};if(j.modulePaths){f.deprecated("dojo.modulePaths","use paths configuration");a={};for(g in j.modulePaths)a[g.replace(/\./g,"/")]=j.modulePaths[g];i({paths:a})}f.moduleUrl=function(a,c){f.deprecated("dojo.moduleUrl()","use require.toUrl","2.0");var m=
null;a&&(m=i.toUrl(a.replace(/\./g,"/")+(c?"/"+c:"")+"/*.*").replace(/\/\*\.\*/,"")+(c?"":"/"));return m};f._hasResource={};return f})},"dojo/has":function(){define(["require"],function(a){var j=a.has||function(){};j.add("dom-addeventlistener",!!document.addEventListener);j.add("touch","ontouchstart"in document);j.add("device-width",screen.availWidth||innerWidth);j.clearElement=function(a){a.innerHTML="";return a};j.normalize=function(a,n){var g=a.match(/[\?:]|[^:\?]*/g),c=0,o=function(a){var h=g[c++];
if(h==":")return 0;else{if(g[c++]=="?")return!a&&j(h)?o():(o(!0),o(a));return h||0}};return(a=o())&&n(a)};j.load=function(a,n,g){a?n([a],g):g()};return j})},"dojo/_base/config":function(){define(["../has","require"],function(a,j){var i={},n=j.rawConfig,g;for(g in n)i[g]=n[g];return i})},"dojo/_base/sniff":function(){define(["./kernel","../has"],function(a,j){a.isBrowser=!0;a._name="browser";var i=j.add,n=navigator,g=n.userAgent,c=n.appVersion,o=parseFloat(c),f,h,b,l,m,r,p,e,d,k,q,t,s;g.indexOf("AdobeAIR")>=
0&&(h=1);b=c.indexOf("Konqueror")>=0?o:0;l=parseFloat(g.split("WebKit/")[1])||void 0;m=parseFloat(g.split("Chrome/")[1])||void 0;r=c.indexOf("Macintosh")>=0;t=/iPhone|iPod|iPad/.test(g);s=parseFloat(g.split("Android ")[1])||void 0;var u=Math.max(c.indexOf("WebKit"),c.indexOf("Safari"),0);if(u&&!m&&(p=parseFloat(c.split("Version/")[1]),!p||parseFloat(c.substr(u+7))<=419.3))p=2;if(!j("dojo-webkit")&&(g.indexOf("Opera")>=0&&(f=o,f>=9.8&&(f=parseFloat(g.split("Version/")[1])||o)),g.indexOf("Gecko")>=
0&&!b&&!l&&(e=d=o),d&&(q=parseFloat(g.split("Firefox/")[1]||g.split("Minefield/")[1])||void 0),document.all&&!f))k=parseFloat(c.split("MSIE ")[1])||void 0,(g=document.documentMode)&&g!=5&&Math.floor(k)!=g&&(k=g);g=document.compatMode=="BackCompat";i("opera",a.isOpera=f);i("air",a.isAIR=h);i("khtml",a.isKhtml=b);i("webkit",a.isWebKit=l);i("chrome",a.isChrome=m);i("mac",a.isMac=r);i("safari",a.isSafari=p);i("mozilla",a.isMozilla=a.isMoz=e);i("ie",a.isIE=k);i("ff",a.isFF=q);i("quirks",a.isQuirks=g);
i("ios",a.isIos=t);i("android",a.isAndroid=s);a.locale=a.locale||(k?n.userLanguage:n.language).toLowerCase();return j})},"dojo/_base/lang":function(){define(["./kernel","../has","./sniff"],function(a,j){j.add("bug-for-in-skips-shadowed",function(){for(var a in{toString:1})return 0;return 1});var i=j("bug-for-in-skips-shadowed")?"hasOwnProperty.valueOf.isPrototypeOf.propertyIsEnumerable.toLocaleString.toString.constructor".split("."):[],n=i.length,g=function(a){a||(a={});for(var d=1,b=arguments.length;d<
b;d++)p._mixin(a,arguments[d]);return a},c=function(b,d,k){var c,l=0,m=a.global;if(!k)if(b.length){c=b[l++];try{k=a.scopeMap[c]&&a.scopeMap[c][1]}catch(f){}k=k||(c in m?m[c]:d?m[c]={}:void 0)}else return m;for(;k&&(c=b[l++]);)k=c in k?k[c]:d?k[c]={}:void 0;return k},o=function(a,d,b){return c(a.split("."),d,b)},f=Object.prototype.toString,h=function(){function a(){}return function(d,b){a.prototype=d;var c=new a;a.prototype=null;b&&p._mixin(c,b);return c}}(),b=function(a,d,b){return(b||[]).concat(Array.prototype.slice.call(a,
d||0))},l=j("ie")?function(){function a(d,b,e){e=e||[];for(b=b||0;b<d.length;b++)e.push(d[b]);return e}return function(d){return(d.item?a:b).apply(this,arguments)}}():b,m=function(a){if(!a||typeof a!="object"||p.isFunction(a))return a;if(a.nodeType&&"cloneNode"in a)return a.cloneNode(!0);if(a instanceof Date)return new Date(a.getTime());if(a instanceof RegExp)return RegExp(a);var d,b,c;if(p.isArray(a)){d=[];b=0;for(c=a.length;b<c;++b)b in a&&d.push(m(a[b]))}else d=a.constructor?new a.constructor:
{};return p._mixin(d,a,m)},r=/\{([^\}]+)\}/g,p={_extraNames:i,_mixin:function(a,d,b){var c,l,m,f={};for(c in d)if(l=d[c],!(c in a)||a[c]!==l&&(!(c in f)||f[c]!==l))a[c]=b?b(l):l;if(j("bug-for-in-skips-shadowed")&&d)for(m=0;m<n;++m)if(c=i[m],l=d[c],!(c in a)||a[c]!==l&&(!(c in f)||f[c]!==l))a[c]=b?b(l):l;return a},mixin:g,setObject:function(a,d,b){var l=a.split("."),a=l.pop();return(b=c(l,!0,b))&&a?b[a]=d:void 0},getObject:o,exists:function(a,d){return p.getObject(a,!1,d)!==void 0},isString:function(a){return typeof a==
"string"||a instanceof String},isArray:function(a){return a&&(a instanceof Array||typeof a=="array")},isFunction:function(a){return f.call(a)==="[object Function]"},isObject:function(a){return a!==void 0&&(a===null||typeof a=="object"||p.isArray(a)||p.isFunction(a))},isArrayLike:function(a){return a&&a!==void 0&&!p.isString(a)&&!p.isFunction(a)&&!(a.tagName&&a.tagName.toLowerCase()=="form")&&(p.isArray(a)||isFinite(a.length))},isAlien:function(a){return a&&!p.isFunction(a)&&/\{\s*\[native code\]\s*\}/.test(String(a))},
extend:function(a){for(var d=1,b=arguments.length;d<b;d++)p._mixin(a.prototype,arguments[d]);return a},_hitchArgs:function(b,d){var c=l(arguments,2),m=p.isString(d);return function(){var f=l(arguments),h=m?(b||a.global)[d]:d;return h&&h.apply(b||this,c.concat(f))}},hitch:function(b,d){if(arguments.length>2)return p._hitchArgs.apply(a,arguments);d||(d=b,b=null);if(p.isString(d)){b=b||a.global;if(!b[d])throw['dojo.hitch: scope["',d,'"] is null (scope="',b,'")'].join("");return function(){return b[d].apply(b,
arguments||[])}}return!b?d:function(){return d.apply(b,arguments||[])}},delegate:h,_toArray:l,partial:function(){return p.hitch.apply(a,[null].concat(p._toArray(arguments)))},clone:m,trim:String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^\s\s*/,"").replace(/\s\s*$/,"")},replace:function(a,b,c){return a.replace(c||r,p.isFunction(b)?b:function(a,c){return o(c,!1,b)})}};g(a,p);return p})},"dojo/_base/array":function(){define(["./kernel","../has","./lang"],function(a,j,
i){function n(a){return o[a]=new Function("item","index","array",a)}function g(a){var c=!a;return function(m,f,h){var e=0,d=m&&m.length||0,k;d&&typeof m=="string"&&(m=m.split(""));typeof f=="string"&&(f=o[f]||n(f));if(h)for(;e<d;++e){if(k=!f.call(h,m[e],e,m),a^k)return!k}else for(;e<d;++e)if(k=!f(m[e],e,m),a^k)return!k;return c}}function c(a){var c=1,m=0,g=0;a||(c=m=g=-1);return function(i,e,d,k){if(k&&c>0)return h.lastIndexOf(i,e,d);var k=i&&i.length||0,q=a?k+g:m;d===f?d=a?m:k+g:d<0?(d=k+d,d<0&&
(d=m)):d=d>=k?k+g:d;for(k&&typeof i=="string"&&(i=i.split(""));d!=q;d+=c)if(i[d]==e)return d;return-1}}var o={},f,h;h={every:g(!1),some:g(!0),indexOf:c(!0),lastIndexOf:c(!1),forEach:function(a,c,m){var f=0,h=a&&a.length||0;h&&typeof a=="string"&&(a=a.split(""));typeof c=="string"&&(c=o[c]||n(c));if(m)for(;f<h;++f)c.call(m,a[f],f,a);else for(;f<h;++f)c(a[f],f,a)},map:function(a,c,m,f){var h=0,e=a&&a.length||0,f=new (f||Array)(e);e&&typeof a=="string"&&(a=a.split(""));typeof c=="string"&&(c=o[c]||n(c));
if(m)for(;h<e;++h)f[h]=c.call(m,a[h],h,a);else for(;h<e;++h)f[h]=c(a[h],h,a);return f},filter:function(a,c,m){var f=0,h=a&&a.length||0,e=[],d;h&&typeof a=="string"&&(a=a.split(""));typeof c=="string"&&(c=o[c]||n(c));if(m)for(;f<h;++f)d=a[f],c.call(m,d,f,a)&&e.push(d);else for(;f<h;++f)d=a[f],c(d,f,a)&&e.push(d);return e},clearCache:function(){o={}}};i.mixin(a,h);return h})},"dojo/ready":function(){define(["./_base/kernel","./has","require","./domReady","./_base/lang"],function(a,j,i,n,g){var c=0,
o,f=[],h=0,b=function(){if(c&&!h&&f.length){h=1;var a=f.shift();try{a()}finally{h=0}h=0;f.length&&o(b)}};i.on("idle",b);o=function(){i.idle()&&b()};var j=a.ready=a.addOnLoad=function(b,c,l){var e=g._toArray(arguments);typeof b!="number"?(l=c,c=b,b=1E3):e.shift();l=l?g.hitch.apply(a,e):function(){c()};l.priority=b;for(e=0;e<f.length&&b>=f[e].priority;e++);f.splice(e,0,l);o()},l=a.config.addOnLoad;if(l)j[g.isArray(l)?"apply":"call"](a,l);a.config.parseOnLoad&&!a.isAsync&&j(99,function(){a.parser||(a.deprecated("Add explicit require(['dojo/parser']);",
"","2.0"),i(["dojo/parser"]))});n(function(){c=1;a._postLoad=a.config.afterOnLoad=!0;f.length&&o(b)});return j})},"dojo/domReady":function(){define(["./has"],function(a){function j(a){o?a(1):f.push(a)}var i=this,n=document,g={loaded:1,complete:1},c=typeof n.readyState!="string",o=!!g[n.readyState];if(c)n.readyState="loading";if(!o){var f=[],h=[],b=function(a){a=a||i.event;if(!(o||a.type=="readystatechange"&&!g[n.readyState])){o=1;if(c)n.readyState="complete";for(;f.length;)f.shift()()}},l=function(a,
d){a.addEventListener(d,b,!1);f.push(function(){a.removeEventListener(d,b,!1)})};if(!a("dom-addeventlistener")){var l=function(a,d){d="on"+d;a.attachEvent(d,b);f.push(function(){a.detachEvent(d,b)})},m=n.createElement("div");try{m.doScroll&&i.frameElement===null&&h.push(function(){try{return m.doScroll("left"),1}catch(a){}})}catch(r){}}l(n,"DOMContentLoaded");l(i,"load");"onreadystatechange"in n?l(n,"readystatechange"):c||h.push(function(){return g[n.readyState]});if(h.length){var p=function(){if(!o){for(var a=
h.length;a--;)if(h[a]()){b("poller");return}setTimeout(p,30)}};p()}}j.load=function(a,d,b){j(b)};return j})},"dojo/_base/declare":function(){define(["./kernel","../has","./lang"],function(a,j,i){function n(a,d){throw Error("declare"+(d?" "+d:"")+": "+a);}function g(a,d,b){var c,k,e,f,l,m,h,g=this._inherited=this._inherited||{};typeof a=="string"&&(c=a,a=d,d=b);b=0;f=a.callee;(c=c||f.nom)||n("can't deduce a name to call inherited()",this.declaredClass);l=this.constructor._meta;e=l.bases;h=g.p;if(c!=
w){if(g.c!==f&&(h=0,m=e[0],l=m._meta,l.hidden[c]!==f)){(k=l.chains)&&typeof k[c]=="string"&&n("calling chained method with inherited: "+c,this.declaredClass);do if(l=m._meta,k=m.prototype,l&&(k[c]===f&&k.hasOwnProperty(c)||l.hidden[c]===f))break;while(m=e[++h]);h=m?h:-1}if(m=e[++h])if(k=m.prototype,m._meta&&k.hasOwnProperty(c))b=k[c];else{f=t[c];do if(k=m.prototype,(b=k[c])&&(m._meta?k.hasOwnProperty(c):b!==f))break;while(m=e[++h])}b=m&&b||t[c]}else{if(g.c!==f&&(h=0,(l=e[0]._meta)&&l.ctor!==f)){k=
l.chains;for((!k||k.constructor!=="manual")&&n("calling chained constructor with inherited",this.declaredClass);m=e[++h];)if((l=m._meta)&&l.ctor===f)break;h=m?h:-1}for(;m=e[++h];)if(b=(l=m._meta)?l.ctor:m)break;b=m&&b}g.c=b;g.p=h;if(b)return d===!0?b:b.apply(this,d||a)}function c(a,d){if(typeof a=="string")return this.__inherited(a,d,!0);return this.__inherited(a,!0)}function o(a,d,b){var c=this.getInherited(a,d);if(c)return c.apply(this,b||d||a)}function f(a){for(var d=this.constructor._meta.bases,
b=0,c=d.length;b<c;++b)if(d[b]===a)return!0;return this instanceof a}function h(a,d){for(var b in d)b!=w&&d.hasOwnProperty(b)&&(a[b]=d[b]);if(j("bug-for-in-skips-shadowed"))for(var c=i._extraNames,k=c.length;k;)b=c[--k],b!=w&&d.hasOwnProperty(b)&&(a[b]=d[b])}function b(a){k.safeMixin(this.prototype,a);return this}function l(a,b){return function(){var v;var c=arguments,k=c,e=c[0],l,f;f=a.length;var m;if(!(this instanceof c.callee))return d(c);if(b&&(e&&e.preamble||this.preamble)){m=Array(a.length);
m[0]=c;for(l=0;;){if(e=c[0])(e=e.preamble)&&(c=e.apply(this,c)||c);e=a[l].prototype;(e=e.hasOwnProperty("preamble")&&e.preamble)&&(c=e.apply(this,c)||c);if(++l==f)break;m[l]=c}}for(l=f-1;l>=0;--l)e=a[l],(v=(f=e._meta)?f.ctor:e,e=v)&&e.apply(this,m?m[l]:c);(e=this.postscript)&&e.apply(this,k)}}function m(a,b){return function(){var c=arguments,k=c,e=c[0];if(!(this instanceof c.callee))return d(c);if(b){if(e)(e=e.preamble)&&(k=e.apply(this,k)||k);(e=this.preamble)&&e.apply(this,k)}a&&a.apply(this,c);
(e=this.postscript)&&e.apply(this,c)}}function r(a){return function(){var v;var b=arguments,c=0,k,e;if(!(this instanceof b.callee))return d(b);for(;k=a[c];++c)if(v=(e=k._meta)?e.ctor:k,k=v){k.apply(this,b);break}(k=this.postscript)&&k.apply(this,b)}}function p(a,b,d){return function(){var c,k,e=0,l=1;d&&(e=b.length-1,l=-1);for(;c=b[e];e+=l)k=c._meta,(c=(k?k.hidden:c.prototype)[a])&&c.apply(this,arguments)}}function e(a){u.prototype=a.prototype;a=new u;u.prototype=null;return a}function d(a){var b=
a.callee,d=e(b);b.apply(d,a);return d}function k(a,d,o){typeof a!="string"&&(o=d,d=a,a="");var o=o||{},u,j,v,z,F,A,E,J=1,I=d;if(s.call(d)=="[object Array]"){J=a;v=[];z=[{cls:0,refs:[]}];A={};for(var V=1,Y=d.length,K=0,D,N,x,y;K<Y;++K){(D=d[K])?s.call(D)!="[object Function]"&&n("mixin #"+K+" is not a callable constructor.",J):n("mixin #"+K+" is unknown. Did you use dojo.require to pull it in?",J);N=D._meta?D._meta.bases:[D];x=0;for(D=N.length-1;D>=0;--D){y=N[D].prototype;if(!y.hasOwnProperty("declaredClass"))y.declaredClass=
"uniqName_"+B++;y=y.declaredClass;A.hasOwnProperty(y)||(A[y]={count:0,refs:[],cls:N[D]},++V);y=A[y];x&&x!==y&&(y.refs.push(x),++x.count);x=y}++x.count;z[0].refs.push(x)}for(;z.length;){x=z.pop();v.push(x.cls);for(--V;j=x.refs,j.length==1;){x=j[0];if(!x||--x.count){x=0;break}v.push(x.cls);--V}if(x){K=0;for(Y=j.length;K<Y;++K)x=j[K],--x.count||z.push(x)}}V&&n("can't build consistent linearization",J);D=d[0];v[0]=D?D._meta&&D===v[v.length-D._meta.bases.length]?D._meta.bases.length:1:0;A=v;v=A[0];J=A.length-
v;d=A[J]}else A=[0],d?s.call(d)=="[object Function]"?(v=d._meta,A=A.concat(v?v.bases:d)):n("base class is not a callable constructor.",a):d!==null&&n("unknown base class. Did you use dojo.require to pull it in?",a);if(d)for(j=J-1;;--j){u=e(d);if(!j)break;v=A[j];(v._meta?h:q)(u,v.prototype);z=new Function;z.superclass=d;z.prototype=u;d=u.constructor=z}else u={};k.safeMixin(u,o);v=o.constructor;if(v!==t.constructor)v.nom=w,u.constructor=v;for(j=J-1;j;--j)(v=A[j]._meta)&&v.chains&&(E=q(E||{},v.chains));
u["-chains-"]&&(E=q(E||{},u["-chains-"]));v=!E||!E.hasOwnProperty(w);A[0]=z=E&&E.constructor==="manual"?r(A):A.length==1?m(o.constructor,v):l(A,v);z._meta={bases:A,hidden:o,chains:E,parents:I,ctor:o.constructor};z.superclass=d&&d.prototype;z.extend=b;z.prototype=u;u.constructor=z;u.getInherited=c;u.isInstanceOf=f;u.inherited=C;u.__inherited=g;if(a)u.declaredClass=a,i.setObject(a,z);if(E)for(F in E)if(u[F]&&typeof E[F]=="string"&&F!=w)v=u[F]=p(F,A,E[F]==="after"),v.nom=F;return z}var q=i.mixin,t=Object.prototype,
s=t.toString,u=new Function,B=0,w="constructor",C=a.config.isDebug?o:g;a.safeMixin=k.safeMixin=function(a,d){var b,c;for(b in d)if(c=d[b],(c!==t[b]||!(b in t))&&b!=w){if(s.call(c)=="[object Function]")c.nom=b;a[b]=c}if(j("bug-for-in-skips-shadowed"))for(var k=i._extraNames,e=k.length;e;)if(b=k[--e],c=d[b],(c!==t[b]||!(b in t))&&b!=w){if(s.call(c)=="[object Function]")c.nom=b;a[b]=c}return a};return a.declare=k})},"dojo/_base/connect":function(){define(["./kernel","../on","../topic","../aspect","./event",
"../mouse","./sniff","./lang","../keys"],function(a,j,i,n,g,c,o,f){function h(b,k,e,l,m){l=f.hitch(e,l);if(!b||!b.addEventListener&&!b.attachEvent)return n.after(b||a.global,k,l,!0);typeof k=="string"&&k.substring(0,2)=="on"&&(k=k.substring(2));if(!b)b=a.global;if(!m)switch(k){case "keypress":k=p;break;case "mouseenter":k=c.enter;break;case "mouseleave":k=c.leave}return j(b,k,l,m)}function b(a){a.keyChar=a.charCode?String.fromCharCode(a.charCode):"";a.charOrCode=a.keyChar||a.keyCode}o.add("events-keypress-typed",
function(){var a={charCode:0};try{a=document.createEvent("KeyboardEvent"),(a.initKeyboardEvent||a.initKeyEvent).call(a,"keypress",!0,!0,null,!1,!1,!1,!1,9,3)}catch(b){}return a.charCode==0&&!o("opera")});var l={106:42,111:47,186:59,187:43,188:44,189:45,190:46,191:47,192:96,219:91,220:92,221:93,222:39,229:113},m=o("mac")?"metaKey":"ctrlKey",r=function(a,c){var e=f.mixin({},a,c);b(e);e.preventDefault=function(){a.preventDefault()};e.stopPropagation=function(){a.stopPropagation()};return e},p;p=o("events-keypress-typed")?
function(a,b){var c=j(a,"keydown",function(a){var d=a.keyCode,c=(d!=13||o("ie")>=9&&!o("quirks"))&&d!=32&&(d!=27||!o("ie"))&&(d<48||d>90)&&(d<96||d>111)&&(d<186||d>192)&&(d<219||d>222)&&d!=229;if(c||a.ctrlKey){c=c?0:d;if(a.ctrlKey)if(d==3||d==13)return b.call(a.currentTarget,a);else c>95&&c<106?c-=48:!a.shiftKey&&c>=65&&c<=90?c+=32:c=l[c]||c;d=r(a,{type:"keypress",faux:!0,charCode:c});b.call(a.currentTarget,d);if(o("ie"))try{a.keyCode=d.keyCode}catch(e){}}}),e=j(a,"keypress",function(a){var d=a.charCode,
a=r(a,{charCode:d>=32?d:0,faux:!0});return b.call(this,a)});return{remove:function(){c.remove();e.remove()}}}:o("opera")?function(a,b){return j(a,"keypress",function(a){var d=a.which;d==3&&(d=99);d=d<32&&!a.shiftKey?0:d;a.ctrlKey&&!a.shiftKey&&d>=65&&d<=90&&(d+=32);return b.call(this,r(a,{charCode:d}))})}:function(a,c){return j(a,"keypress",function(a){b(a);return c.call(this,a)})};var e={_keypress:p,connect:function(){var a=arguments,b=[],c=0;b.push(typeof a[0]=="string"?null:a[c++],a[c++]);var e=
a[c+1];b.push(typeof e=="string"||typeof e=="function"?a[c++]:null,a[c++]);for(e=a.length;c<e;c++)b.push(a[c]);return h.apply(this,b)},disconnect:function(a){a&&a.remove()},subscribe:function(a,b,c){return i.subscribe(a,f.hitch(b,c))},publish:function(a,b){return i.publish.apply(i,[a].concat(b))},connectPublisher:function(a,b,c){var l=function(){e.publish(a,arguments)};return c?e.connect(b,c,l):e.connect(b,l)},isCopyKey:function(a){return a[m]}};e.unsubscribe=e.disconnect;f.mixin(a,e);return e})},
"dojo/on":function(){define(["./has!dom-addeventlistener?:./aspect","./_base/kernel","./has"],function(a,j,i){function n(a,b,d,c,k){if(c=b.match(/(.*):(.*)/))return b=c[2],c=c[1],f.selector(c,b).call(k,a,d);i("touch")&&(h.test(b)&&(d=s(d)),!i("event-orientationchange")&&b=="orientationchange"&&(b="resize",a=window,d=s(d)));if(a.addEventListener){var l=b in m;a.addEventListener(l?m[b]:b,d,l);return{remove:function(){a.removeEventListener(b,d,l)}}}b="on"+b;if(e&&a.attachEvent)return e(a,b,d);throw Error("Target must be an event emitter");
}function g(){this.cancelable=!1}function c(){this.bubbles=!1}var o=window.ScriptEngineMajorVersion;i.add("jscript",o&&o()+ScriptEngineMinorVersion()/10);i.add("event-orientationchange",i("touch")&&!i("android"));var f=function(a,b,d,c){if(a.on)return a.on(b,d);return f.parse(a,b,d,n,c,this)};f.pausable=function(a,b,d,c){var e,a=f(a,b,function(){if(!e)return d.apply(this,arguments)},c);a.pause=function(){e=!0};a.resume=function(){e=!1};return a};f.once=function(a,b,d){var c=f(a,b,function(){c.remove();
return d.apply(this,arguments)});return c};f.parse=function(a,b,d,c,e,k){if(b.call)return b.call(k,a,d);if(b.indexOf(",")>-1){for(var b=b.split(/\s*,\s*/),l=[],f=0,m;m=b[f++];)l.push(c(a,m,d,e,k));l.remove=function(){for(var a=0;a<l.length;a++)l[a].remove()};return l}return c(a,b,d,e,k)};var h=/^touch/;f.selector=function(a,b,d){return function(c,e){function k(b){for(l=l&&l.matches?l:j.query;!l.matches(b,a,c);)if(b==c||d===!1||!(b=b.parentNode)||b.nodeType!=1)return;return b}var l=this,m=b.bubble;
if(m)return f(c,m(k),e);return f(c,b,function(a){var b=k(a.target);return b&&e.call(b,a)})}};var b=[].slice,l=f.emit=function(a,d,e){var k=b.call(arguments,2),l="on"+d;if("parentNode"in a){var m=k[0]={},f;for(f in e)m[f]=e[f];m.preventDefault=g;m.stopPropagation=c;m.target=a;m.type=d;e=m}do a[l]&&a[l].apply(a,k);while(e&&e.bubbles&&(a=a.parentNode));return e&&e.cancelable&&e},m={};if(i("dom-addeventlistener")){m={focusin:"focus",focusout:"blur"};if(i("opera"))m.keydown="keypress";f.emit=function(a,
b,d){if(a.dispatchEvent&&document.createEvent){var c=document.createEvent("HTMLEvents");c.initEvent(b,!!d.bubbles,!!d.cancelable);for(var e in d)e in c||(c[e]=d[e]);return a.dispatchEvent(c)&&c}return l.apply(f,arguments)}}else{f._fixEvent=function(a,b){if(!a)a=(b&&(b.ownerDocument||b.document||b).parentWindow||window).event;if(!a)return a;if(!a.target){a.target=a.srcElement;a.currentTarget=b||a.srcElement;if(a.type=="mouseover")a.relatedTarget=a.fromElement;if(a.type=="mouseout")a.relatedTarget=
a.toElement;if(!a.stopPropagation)a.stopPropagation=d,a.preventDefault=k;switch(a.type){case "keypress":var c="charCode"in a?a.charCode:a.keyCode;c==10?(c=0,a.keyCode=13):c==13||c==27?c=0:c==3&&(c=99);a.charCode=c;c=a;c.keyChar=c.charCode?String.fromCharCode(c.charCode):"";c.charOrCode=c.keyChar||c.keyCode}}return a};var r=function(a){this.handle=a};r.prototype.remove=function(){delete _dojoIEListeners_[this.handle]};var p=function(a){return function(b){b=f._fixEvent(b,this);return a.call(this,b)}},
e=function(b,d,c){c=p(c);if(((b.ownerDocument?b.ownerDocument.parentWindow:b.parentWindow||b.window||window)!=top||i("jscript")<5.8)&&!i("config-_allow_leaks")){typeof _dojoIEListeners_=="undefined"&&(_dojoIEListeners_=[]);var e=b[d];if(!e||!e.listeners){var k=e;b[d]=e=Function("event","var callee = arguments.callee; for(var i = 0; i<callee.listeners.length; i++){var listener = _dojoIEListeners_[callee.listeners[i]]; if(listener){listener.call(this,event);}}");e.listeners=[];e.global=this;k&&e.listeners.push(_dojoIEListeners_.push(k)-
1)}e.listeners.push(b=e.global._dojoIEListeners_.push(c)-1);return new r(b)}return a.after(b,d,c,!0)},d=function(){this.cancelBubble=!0},k=f._preventDefault=function(){this.bubbledKeyCode=this.keyCode;if(this.ctrlKey)try{this.keyCode=0}catch(a){}this.defaultPrevented=!0;this.returnValue=!1}}if(i("touch"))var q=function(){},t=window.orientation,s=function(a){return function(b){var d=b.corrected;if(!d){var c=b.type;try{delete b.type}catch(e){}b.type?(q.prototype=b,d=new q,d.preventDefault=function(){b.preventDefault()},
d.stopPropagation=function(){b.stopPropagation()}):(d=b,d.type=c);b.corrected=d;if(c=="resize"){if(t==window.orientation)return null;t=window.orientation;d.type="orientationchange";return a.call(this,d)}if(!("rotation"in d))d.rotation=0,d.scale=1;var c=d.changedTouches[0],k;for(k in c)delete d[k],d[k]=c[k]}return a.call(this,d)}};return f})},"dojo/topic":function(){define(["./Evented"],function(a){var j=new a;return{publish:function(){return j.emit.apply(j,arguments)},subscribe:function(){return j.on.apply(j,
arguments)}}})},"dojo/Evented":function(){define(["./aspect","./on"],function(a,j){function i(){}var n=a.after;i.prototype={on:function(a,c){return j.parse(this,a,c,function(a,f){return n(a,"on"+f,c,!0)})},emit:function(){var a=[this];a.push.apply(a,arguments);return j.emit.apply(j,a)}};return i})},"dojo/aspect":function(){define("dojo/aspect",[],function(){function a(a,n,g,c){var o=a[n],f=n=="around",h;if(f){var b=g(function(){return o.advice(this,arguments)});h={remove:function(){h.cancelled=!0},
advice:function(a,c){return h.cancelled?o.advice(a,c):b.apply(a,c)}}}else h={remove:function(){var b=h.previous,c=h.next;if(!c&&!b)delete a[n];else if(b?b.next=c:a[n]=c,c)c.previous=b},advice:g,receiveArguments:c};if(o&&!f)if(n=="after"){for(g=o;g;)o=g,g=g.next;o.next=h;h.previous=o}else{if(n=="before")a[n]=h,h.next=o,o.previous=h}else a[n]=h;return h}function j(i){return function(n,g,c,o){var f=n[g],h;if(!f||f.target!=n){n[g]=h=function(){for(var a=arguments,c=h.before;c;)a=c.advice.apply(this,a)||
a,c=c.next;if(h.around)var f=h.around.advice(this,a);for(c=h.after;c;)f=c.receiveArguments?c.advice.apply(this,a)||f:c.advice.call(this,f),c=c.next;return f};if(f)h.around={advice:function(a,c){return f.apply(a,c)}};h.target=n}n=a(h||f,i,c,o);c=null;return n}}return{before:j("before"),around:j("around"),after:j("after")}})},"dojo/_base/event":function(){define(["./kernel","../on","../has","../dom-geometry"],function(a,j,i,n){if(j._fixEvent){var g=j._fixEvent;j._fixEvent=function(a,i){(a=g(a,i))&&
n.normalizeEvent(a);return a}}a.fixEvent=function(a,g){if(j._fixEvent)return j._fixEvent(a,g);return a};a.stopEvent=function(a){i("dom-addeventlistener")||a&&a.preventDefault?(a.preventDefault(),a.stopPropagation()):(a=a||window.event,a.cancelBubble=!0,j._preventDefault.call(a))};return{fix:a.fixEvent,stop:a.stopEvent}})},"dojo/dom-geometry":function(){define(["./_base/sniff","./_base/window","./dom","./dom-style"],function(a,j,i,n){function g(a,c,f,h,g,e){e=e||"px";a=a.style;if(!isNaN(c))a.left=
c+e;if(!isNaN(f))a.top=f+e;if(h>=0)a.width=h+e;if(g>=0)a.height=g+e}function c(a){return a.tagName.toLowerCase()=="button"||a.tagName.toLowerCase()=="input"&&(a.getAttribute("type")||"").toLowerCase()=="button"}function o(a){return f.boxModel=="border-box"||a.tagName.toLowerCase()=="table"||c(a)}var f={boxModel:"content-box"};if(a("ie"))f.boxModel=document.compatMode=="BackCompat"?"border-box":"content-box";f.getPadExtents=function(a,c){var a=i.byId(a),f=c||n.getComputedStyle(a),h=n.toPixelValue,
g=h(a,f.paddingLeft),e=h(a,f.paddingTop),d=h(a,f.paddingRight),f=h(a,f.paddingBottom);return{l:g,t:e,r:d,b:f,w:g+d,h:e+f}};f.getBorderExtents=function(a,c){var a=i.byId(a),f=n.toPixelValue,h=c||n.getComputedStyle(a),g=h.borderLeftStyle!="none"?f(a,h.borderLeftWidth):0,e=h.borderTopStyle!="none"?f(a,h.borderTopWidth):0,d=h.borderRightStyle!="none"?f(a,h.borderRightWidth):0,f=h.borderBottomStyle!="none"?f(a,h.borderBottomWidth):0;return{l:g,t:e,r:d,b:f,w:g+d,h:e+f}};f.getPadBorderExtents=function(a,
c){var a=i.byId(a),h=c||n.getComputedStyle(a),g=f.getPadExtents(a,h),h=f.getBorderExtents(a,h);return{l:g.l+h.l,t:g.t+h.t,r:g.r+h.r,b:g.b+h.b,w:g.w+h.w,h:g.h+h.h}};f.getMarginExtents=function(b,c){var b=i.byId(b),f=c||n.getComputedStyle(b),h=n.toPixelValue,g=h(b,f.marginLeft),e=h(b,f.marginTop),d=h(b,f.marginRight),h=h(b,f.marginBottom);a("webkit")&&f.position!="absolute"&&(d=g);return{l:g,t:e,r:d,b:h,w:g+d,h:e+h}};f.getMarginBox=function(b,c){var b=i.byId(b),h=c||n.getComputedStyle(b),g=f.getMarginExtents(b,
h),o=b.offsetLeft-g.l,e=b.offsetTop-g.t,d=b.parentNode,k=n.toPixelValue;if(a("mozilla")){var j=parseFloat(h.left),h=parseFloat(h.top);!isNaN(j)&&!isNaN(h)?(o=j,e=h):d&&d.style&&(d=n.getComputedStyle(d),d.overflow!="visible"&&(o+=d.borderLeftStyle!="none"?k(b,d.borderLeftWidth):0,e+=d.borderTopStyle!="none"?k(b,d.borderTopWidth):0))}else if((a("opera")||a("ie")==8&&!a("quirks"))&&d)d=n.getComputedStyle(d),o-=d.borderLeftStyle!="none"?k(b,d.borderLeftWidth):0,e-=d.borderTopStyle!="none"?k(b,d.borderTopWidth):
0;return{l:o,t:e,w:b.offsetWidth+g.w,h:b.offsetHeight+g.h}};f.getContentBox=function(b,c){var b=i.byId(b),h=c||n.getComputedStyle(b),g=b.clientWidth,o=f.getPadExtents(b,h),e=f.getBorderExtents(b,h);g?(h=b.clientHeight,e.w=e.h=0):(g=b.offsetWidth,h=b.offsetHeight);a("opera")&&(o.l+=e.l,o.t+=e.t);return{l:o.l,t:o.t,w:g-o.w-e.w,h:h-o.h-e.h}};f.setContentSize=function(a,c,h){var a=i.byId(a),n=c.w,c=c.h;o(a)&&(h=f.getPadBorderExtents(a,h),n>=0&&(n+=h.w),c>=0&&(c+=h.h));g(a,NaN,NaN,n,c)};var h={l:0,t:0,
w:0,h:0};f.setMarginBox=function(b,l,m){var b=i.byId(b),j=m||n.getComputedStyle(b),m=l.w,p=l.h,e=o(b)?h:f.getPadBorderExtents(b,j),j=f.getMarginExtents(b,j);if(a("webkit")&&c(b)){var d=b.style;if(m>=0&&!d.width)d.width="4px";if(p>=0&&!d.height)d.height="4px"}m>=0&&(m=Math.max(m-e.w-j.w,0));p>=0&&(p=Math.max(p-e.h-j.h,0));g(b,l.l,l.t,m,p)};f.isBodyLtr=function(){return(j.body().dir||j.doc.documentElement.dir||"ltr").toLowerCase()=="ltr"};f.docScroll=function(){var b=j.doc.parentWindow||j.doc.defaultView;
return"pageXOffset"in b?{x:b.pageXOffset,y:b.pageYOffset}:(b=a("quirks")?j.body():j.doc.documentElement,{x:f.fixIeBiDiScrollLeft(b.scrollLeft||0),y:b.scrollTop||0})};f.getIeDocumentElementOffset=function(){var b=j.doc.documentElement;if(a("ie")<8){var c=b.getBoundingClientRect(),f=c.left,c=c.top;a("ie")<7&&(f+=b.clientLeft,c+=b.clientTop);return{x:f<0?0:f,y:c<0?0:c}}else return{x:0,y:0}};f.fixIeBiDiScrollLeft=function(b){var c=a("ie");if(c&&!f.isBodyLtr()){var h=a("quirks"),g=h?j.body():j.doc.documentElement;
c==6&&!h&&j.global.frameElement&&g.scrollHeight>g.clientHeight&&(b+=g.clientLeft);return c<8||h?b+g.clientWidth-g.scrollWidth:-b}return b};f.position=function(b,c){var b=i.byId(b),h=j.body(),g=h.parentNode,o=b.getBoundingClientRect(),o={x:o.left,y:o.top,w:o.right-o.left,h:o.bottom-o.top};if(a("ie"))g=f.getIeDocumentElementOffset(),o.x-=g.x+(a("quirks")?h.clientLeft+h.offsetLeft:0),o.y-=g.y+(a("quirks")?h.clientTop+h.offsetTop:0);else if(a("ff")==3){var h=n.getComputedStyle(g),e=n.toPixelValue;o.x-=
e(g,h.marginLeft)+e(g,h.borderLeftWidth);o.y-=e(g,h.marginTop)+e(g,h.borderTopWidth)}c&&(g=f.docScroll(),o.x+=g.x,o.y+=g.y);return o};f.getMarginSize=function(a,c){var a=i.byId(a),h=f.getMarginExtents(a,c||n.getComputedStyle(a)),g=a.getBoundingClientRect();return{w:g.right-g.left+h.w,h:g.bottom-g.top+h.h}};f.normalizeEvent=function(b){if(!("layerX"in b))b.layerX=b.offsetX,b.layerY=b.offsetY;if(!a("dom-addeventlistener")){var c=b.target,c=c&&c.ownerDocument||document,c=a("quirks")?c.body:c.documentElement,
h=f.getIeDocumentElementOffset();b.pageX=b.clientX+f.fixIeBiDiScrollLeft(c.scrollLeft||0)-h.x;b.pageY=b.clientY+(c.scrollTop||0)-h.y}};return f})},"dojo/_base/window":function(){define(["./kernel","../has","./sniff"],function(a,j){a.doc=this.document||null;a.body=function(){return a.doc.body||a.doc.getElementsByTagName("body")[0]};a.setContext=function(n,g){a.global=i.global=n;a.doc=i.doc=g};a.withGlobal=function(n,g,c,o){var f=a.global;try{return a.global=i.global=n,a.withDoc.call(null,n.document,
g,c,o)}finally{a.global=i.global=f}};a.withDoc=function(n,g,c,o){var f=a.doc,h=a.isQuirks,b=a.isIE,l,m,r;try{a.doc=i.doc=n;a.isQuirks=j.add("quirks",a.doc.compatMode=="BackCompat",!0,!0);if(j("ie")&&(r=n.parentWindow)&&r.navigator)l=parseFloat(r.navigator.appVersion.split("MSIE ")[1])||void 0,(m=n.documentMode)&&m!=5&&Math.floor(l)!=m&&(l=m),a.isIE=j.add("ie",l,!0,!0);c&&typeof g=="string"&&(g=c[g]);return g.apply(c,o||[])}finally{a.doc=i.doc=f,a.isQuirks=j.add("quirks",h,!0,!0),a.isIE=j.add("ie",
b,!0,!0)}};var i={global:a.global,doc:a.doc,body:a.body,setContext:a.setContext,withGlobal:a.withGlobal,withDoc:a.withDoc};return i})},"dojo/dom":function(){define(["./_base/sniff","./_base/lang","./_base/window"],function(a,j,i){try{document.execCommand("BackgroundImageCache",!1,!0)}catch(n){}var g={};g.byId=a("ie")?function(a,g){if(typeof a!="string")return a;var f=g||i.doc,h=a&&f.getElementById(a);if(h&&(h.attributes.id.value==a||h.id==a))return h;else{f=f.all[a];if(!f||f.nodeName)f=[f];for(var b=
0;h=f[b++];)if(h.attributes&&h.attributes.id&&h.attributes.id.value==a||h.id==a)return h}}:function(a,g){return(typeof a=="string"?(g||i.doc).getElementById(a):a)||null};g.isDescendant=function(a,o){try{a=g.byId(a);for(o=g.byId(o);a;){if(a==o)return!0;a=a.parentNode}}catch(f){}return!1};g.setSelectable=function(c,o){c=g.byId(c);if(a("mozilla"))c.style.MozUserSelect=o?"":"none";else if(a("khtml")||a("webkit"))c.style.KhtmlUserSelect=o?"auto":"none";else if(a("ie"))for(var f=c.unselectable=o?"":"on",
h=c.getElementsByTagName("*"),b=0,l=h.length;b<l;++b)h.item(b).unselectable=f};return g})},"dojo/dom-style":function(){define(["./_base/sniff","./dom"],function(a,j){function i(h,e,d){e=e.toLowerCase();if(a("ie")){if(d=="auto"){if(e=="height")return h.offsetHeight;if(e=="width")return h.offsetWidth}if(e=="fontweight")switch(d){case 700:return"bold";default:return"normal"}}e in b||(b[e]=l.test(e));return b[e]?c(h,d):d}var n,g={};n=a("webkit")?function(a){var b;if(a.nodeType==1){var d=a.ownerDocument.defaultView;
b=d.getComputedStyle(a,null);if(!b&&a.style)a.style.display="",b=d.getComputedStyle(a,null)}return b||{}}:a("ie")&&(a("ie")<9||a("quirks"))?function(a){return a.nodeType==1?a.currentStyle:{}}:function(a){return a.nodeType==1?a.ownerDocument.defaultView.getComputedStyle(a,null):{}};g.getComputedStyle=n;var c;c=a("ie")?function(a,b){if(!b)return 0;if(b=="medium")return 4;if(b.slice&&b.slice(-2)=="px")return parseFloat(b);var d=a.style,c=a.runtimeStyle,h=d.left,f=c.left;c.left=a.currentStyle.left;try{d.left=
b,b=d.pixelLeft}catch(g){b=0}d.left=h;c.left=f;return b}:function(a,b){return parseFloat(b)||0};g.toPixelValue=c;var o=function(a,b){try{return a.filters.item("DXImageTransform.Microsoft.Alpha")}catch(d){return b?{}:null}},f=a("ie")<9||a("ie")&&a("quirks")?function(a){try{return o(a).Opacity/100}catch(b){return 1}}:function(a){return n(a).opacity},h=a("ie")<9||a("ie")&&a("quirks")?function(a,b){var d=b*100,c=b==1;a.style.zoom=c?"":1;if(o(a))o(a,1).Opacity=d;else{if(c)return b;a.style.filter+=" progid:DXImageTransform.Microsoft.Alpha(Opacity="+
d+")"}o(a,1).Enabled=!c;if(a.tagName.toLowerCase()=="tr")for(d=a.firstChild;d;d=d.nextSibling)d.tagName.toLowerCase()=="td"&&h(d,b);return b}:function(a,b){return a.style.opacity=b},b={left:!0,top:!0},l=/margin|padding|width|height|max|min|offset/,m=a("ie")?"styleFloat":"cssFloat",r={cssFloat:m,styleFloat:m,"float":m};g.get=function(a,b){var d=j.byId(a),c=arguments.length;if(c==2&&b=="opacity")return f(d);var b=r[b]||b,h=g.getComputedStyle(d);return c==1?h:i(d,b,h[b]||d.style[b])};g.set=function(a,
b,d){var c=j.byId(a),f=arguments.length,l=b=="opacity",b=r[b]||b;if(f==3)return l?h(c,d):c.style[b]=d;for(var o in b)g.set(a,o,b[o]);return g.getComputedStyle(c)};return g})},"dojo/mouse":function(){define(["./_base/kernel","./on","./has","./dom","./_base/window"],function(a,j,i,n,g){function c(a,f){var h=function(b,c){return j(b,a,function(a){if(f)return f(a,c);if(!n.isDescendant(a.relatedTarget,b))return c.call(this,a)})};h.bubble=function(b){return c(a,function(a,c){var h=b(a.target),f=a.relatedTarget;
if(h&&h!=(f&&f.nodeType==1&&b(f)))return c.call(h,a)})};return h}i.add("dom-quirks",g.doc&&g.doc.compatMode=="BackCompat");i.add("events-mouseenter",g.doc&&"onmouseenter"in g.doc.createElement("div"));i=i("dom-quirks")||!i("dom-addeventlistener")?{LEFT:1,MIDDLE:4,RIGHT:2,isButton:function(a,c){return a.button&c},isLeft:function(a){return a.button&1},isMiddle:function(a){return a.button&4},isRight:function(a){return a.button&2}}:{LEFT:0,MIDDLE:1,RIGHT:2,isButton:function(a,c){return a.button==c},isLeft:function(a){return a.button==
0},isMiddle:function(a){return a.button==1},isRight:function(a){return a.button==2}};a.mouseButtons=i;return{enter:c("mouseover"),leave:c("mouseout"),isLeft:i.isLeft,isMiddle:i.isMiddle,isRight:i.isRight}})},"dojo/keys":function(){define("dojo/keys",["./_base/kernel","./_base/sniff"],function(a,j){return a.keys={BACKSPACE:8,TAB:9,CLEAR:12,ENTER:13,SHIFT:16,CTRL:17,ALT:18,META:j("safari")?91:224,PAUSE:19,CAPS_LOCK:20,ESCAPE:27,SPACE:32,PAGE_UP:33,PAGE_DOWN:34,END:35,HOME:36,LEFT_ARROW:37,UP_ARROW:38,
RIGHT_ARROW:39,DOWN_ARROW:40,INSERT:45,DELETE:46,HELP:47,LEFT_WINDOW:91,RIGHT_WINDOW:92,SELECT:93,NUMPAD_0:96,NUMPAD_1:97,NUMPAD_2:98,NUMPAD_3:99,NUMPAD_4:100,NUMPAD_5:101,NUMPAD_6:102,NUMPAD_7:103,NUMPAD_8:104,NUMPAD_9:105,NUMPAD_MULTIPLY:106,NUMPAD_PLUS:107,NUMPAD_ENTER:108,NUMPAD_MINUS:109,NUMPAD_PERIOD:110,NUMPAD_DIVIDE:111,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,F13:124,F14:125,F15:126,NUM_LOCK:144,SCROLL_LOCK:145,UP_DPAD:175,DOWN_DPAD:176,LEFT_DPAD:177,
RIGHT_DPAD:178,copyKey:j("mac")&&!j("air")?j("safari")?91:224:17}})},"dojo/_base/Deferred":function(){define(["./kernel","./config","./lang"],function(a,j,i){var n=function(){},g=Object.freeze||function(){};a.Deferred=function(c){function o(a){if(b)throw Error("This deferred has already been resolved");h=a;b=!0;f()}function f(){for(var a;!a&&r;){var c=r;r=r.next;if(a=c.progress==n)b=!1;var e=l?c.error:c.resolved;if(e)try{var f=e(h);f&&typeof f.then==="function"?f.then(i.hitch(c.deferred,"resolve"),
i.hitch(c.deferred,"reject"),i.hitch(c.deferred,"progress")):(e=a&&f===void 0,a&&!e&&(l=f instanceof Error),c.deferred[e&&l?"reject":"resolve"](e?h:f))}catch(g){c.deferred.reject(g)}else l?c.deferred.reject(h):c.deferred.resolve(h)}}var h,b,l,m,r,p=this.promise={};this.resolve=this.callback=function(a){this.fired=0;this.results=[a,null];o(a)};this.reject=this.errback=function(a){l=!0;this.fired=1;o(a);this.results=[null,a];if(!a||a.log!==!1)(j.deferredOnError||function(){})(a)};this.progress=function(a){for(var b=
r;b;){var c=b.progress;c&&c(a);b=b.next}};this.addCallbacks=function(a,b){this.then(a,b,n);return this};p.then=this.then=function(c,e,h){var g=h==n?this:new a.Deferred(p.cancel),c={resolved:c,error:e,progress:h,deferred:g};r?m=m.next=c:r=m=c;b&&f();return g.promise};var e=this;p.cancel=this.cancel=function(){if(!b){var a=c&&c(e);if(!b)a instanceof Error||(a=Error(a)),a.log=!1,e.reject(a)}};g(p)};i.extend(a.Deferred,{addCallback:function(){return this.addCallbacks(i.hitch.apply(a,arguments))},addErrback:function(){return this.addCallbacks(null,
i.hitch.apply(a,arguments))},addBoth:function(){var c=i.hitch.apply(a,arguments);return this.addCallbacks(c,c)},fired:-1});a.Deferred.when=a.when=function(a,g,f,h){if(a&&typeof a.then==="function")return a.then(g,f,h);return g?g(a):a};return a.Deferred})},"dojo/_base/json":function(){define(["./kernel","../json"],function(a,j){a.fromJson=function(a){return eval("("+a+")")};a._escapeString=j.stringify;a.toJsonIndentStr="\t";a.toJson=function(i,n){return j.stringify(i,function(a,c){if(c){var i=c.__json__||
c.json;if(typeof i=="function")return i.call(c)}return c},n&&a.toJsonIndentStr)};return a})},"dojo/json":function(){define(["./has"],function(a){var j=typeof JSON!="undefined";a.add("json-parse",j);a.add("json-stringify",j&&JSON.stringify({a:0},function(a,g){return g||1})=='{"a":1}');if(a("json-stringify"))return JSON;else{var i=function(a){return('"'+a.replace(/(["\\])/g,"\\$1")+'"').replace(/[\f]/g,"\\f").replace(/[\b]/g,"\\b").replace(/[\n]/g,"\\n").replace(/[\t]/g,"\\t").replace(/[\r]/g,"\\r")};
return{parse:a("json-parse")?JSON.parse:function(a,g){if(g&&!/^([\s\[\{]*(?:"(?:\\.|[^"])+"|-?\d[\d\.]*(?:[Ee][+-]?\d+)?|null|true|false|)[\s\]\}]*(?:,|:|$))+$/.test(a))throw new SyntaxError("Invalid characters in JSON");return eval("("+a+")")},stringify:function(a,g,c){function o(a,b,l){g&&(a=g(l,a));var m;m=typeof a;if(m=="number")return isFinite(a)?a+"":"null";if(m=="boolean")return a+"";if(a===null)return"null";if(typeof a=="string")return i(a);if(m=="function"||m=="undefined")return f;if(typeof a.toJSON==
"function")return o(a.toJSON(l),b,l);if(a instanceof Date)return'"{FullYear}-{Month+}-{Date}T{Hours}:{Minutes}:{Seconds}Z"'.replace(/\{(\w+)(\+)?\}/g,function(b,c,d){b=a["getUTC"+c]()+(d?1:0);return b<10?"0"+b:b});if(a.valueOf()!==a)return o(a.valueOf(),b,l);var j=c?b+c:"",n=c?" ":"",e=c?"\n":"";if(a instanceof Array){for(var n=a.length,d=[],l=0;l<n;l++)m=o(a[l],j,l),typeof m!="string"&&(m="null"),d.push(e+j+m);return"["+d.join(",")+e+b+"]"}d=[];for(l in a){var k;if(typeof l=="number")k='"'+l+'"';
else if(typeof l=="string")k=i(l);else continue;m=o(a[l],j,l);typeof m=="string"&&d.push(e+j+k+":"+n+m)}return"{"+d.join(",")+e+b+"}"}var f;typeof g=="string"&&(c=g,g=null);return o(a,"","")}}}})},"dojo/_base/Color":function(){define(["./kernel","./lang","./array","./config"],function(a,j,i,n){var g=a.Color=function(a){a&&this.setColor(a)};g.named={black:[0,0,0],silver:[192,192,192],gray:[128,128,128],white:[255,255,255],maroon:[128,0,0],red:[255,0,0],purple:[128,0,128],fuchsia:[255,0,255],green:[0,
128,0],lime:[0,255,0],olive:[128,128,0],yellow:[255,255,0],navy:[0,0,128],blue:[0,0,255],teal:[0,128,128],aqua:[0,255,255],transparent:n.transparentColor||[0,0,0,0]};j.extend(g,{r:255,g:255,b:255,a:1,_set:function(a,g,f,h){this.r=a;this.g=g;this.b=f;this.a=h},setColor:function(a){j.isString(a)?g.fromString(a,this):j.isArray(a)?g.fromArray(a,this):(this._set(a.r,a.g,a.b,a.a),a instanceof g||this.sanitize());return this},sanitize:function(){return this},toRgb:function(){return[this.r,this.g,this.b]},
toRgba:function(){return[this.r,this.g,this.b,this.a]},toHex:function(){return"#"+i.map(["r","g","b"],function(a){a=this[a].toString(16);return a.length<2?"0"+a:a},this).join("")},toCss:function(a){var g=this.r+", "+this.g+", "+this.b;return(a?"rgba("+g+", "+this.a:"rgb("+g)+")"},toString:function(){return this.toCss(!0)}});g.blendColors=a.blendColors=function(a,o,f,h){var b=h||new g;i.forEach(["r","g","b","a"],function(h){b[h]=a[h]+(o[h]-a[h])*f;h!="a"&&(b[h]=Math.round(b[h]))});return b.sanitize()};
g.fromRgb=a.colorFromRgb=function(a,i){var f=a.toLowerCase().match(/^rgba?\(([\s\.,0-9]+)\)/);return f&&g.fromArray(f[1].split(/\s*,\s*/),i)};g.fromHex=a.colorFromHex=function(a,o){var f=o||new g,h=a.length==4?4:8,b=(1<<h)-1,a=Number("0x"+a.substr(1));if(isNaN(a))return null;i.forEach(["b","g","r"],function(g){var i=a&b;a>>=h;f[g]=h==4?17*i:i});f.a=1;return f};g.fromArray=a.colorFromArray=function(a,i){var f=i||new g;f._set(Number(a[0]),Number(a[1]),Number(a[2]),Number(a[3]));if(isNaN(f.a))f.a=1;
return f.sanitize()};g.fromString=a.colorFromString=function(a,i){var f=g.named[a];return f&&g.fromArray(f,i)||g.fromRgb(a,i)||g.fromHex(a,i)};return g})},"dojo/_base/browser":function(){require.has&&require.has.add("config-selectorEngine","acme");define(["../ready","./kernel","./connect","./unload","./window","./event","./html","./NodeList","../query","./xhr","./fx"],function(a){return a})},"dojo/_base/unload":function(){define(["./kernel","./connect"],function(a,j){var i=window;a.addOnWindowUnload=
function(n,g){if(!a.windowUnloaded)j.connect(i,"unload",a.windowUnloaded=function(){});j.connect(i,"unload",n,g)};a.addOnUnload=function(a,g){j.connect(i,"beforeunload",a,g)};return{addOnWindowUnload:a.addOnWindowUnload,addOnUnload:a.addOnUnload}})},"dojo/_base/html":function(){define(["./kernel","../dom","../dom-style","../dom-attr","../dom-prop","../dom-class","../dom-construct","../dom-geometry"],function(a,j,i,n,g,c,o,f){a.byId=j.byId;a.isDescendant=j.isDescendant;a.setSelectable=j.setSelectable;
a.getAttr=n.get;a.setAttr=n.set;a.hasAttr=n.has;a.removeAttr=n.remove;a.getNodeProp=n.getNodeProp;a.attr=function(a,b,c){if(arguments.length==2)return n[typeof b=="string"?"get":"set"](a,b);return n.set(a,b,c)};a.hasClass=c.contains;a.addClass=c.add;a.removeClass=c.remove;a.toggleClass=c.toggle;a.replaceClass=c.replace;a._toDom=a.toDom=o.toDom;a.place=o.place;a.create=o.create;a.empty=function(a){o.empty(a)};a._destroyElement=a.destroy=function(a){o.destroy(a)};a._getPadExtents=a.getPadExtents=f.getPadExtents;
a._getBorderExtents=a.getBorderExtents=f.getBorderExtents;a._getPadBorderExtents=a.getPadBorderExtents=f.getPadBorderExtents;a._getMarginExtents=a.getMarginExtents=f.getMarginExtents;a._getMarginSize=a.getMarginSize=f.getMarginSize;a._getMarginBox=a.getMarginBox=f.getMarginBox;a.setMarginBox=f.setMarginBox;a._getContentBox=a.getContentBox=f.getContentBox;a.setContentSize=f.setContentSize;a._isBodyLtr=a.isBodyLtr=f.isBodyLtr;a._docScroll=a.docScroll=f.docScroll;a._getIeDocumentElementOffset=a.getIeDocumentElementOffset=
f.getIeDocumentElementOffset;a._fixIeBiDiScrollLeft=a.fixIeBiDiScrollLeft=f.fixIeBiDiScrollLeft;a.position=f.position;a.marginBox=function(a,b){return b?f.setMarginBox(a,b):f.getMarginBox(a)};a.contentBox=function(a,b){return b?f.setContentSize(a,b):f.getContentBox(a)};a.coords=function(c,b){a.deprecated("dojo.coords()","Use dojo.position() or dojo.marginBox().");var c=j.byId(c),g=i.getComputedStyle(c),g=f.getMarginBox(c,g),m=f.position(c,b);g.x=m.x;g.y=m.y;return g};a.getProp=g.get;a.setProp=g.set;
a.prop=function(a,b,c){if(arguments.length==2)return g[typeof b=="string"?"get":"set"](a,b);return g.set(a,b,c)};a.getStyle=i.get;a.setStyle=i.set;a.getComputedStyle=i.getComputedStyle;a.__toPixelValue=a.toPixelValue=i.toPixelValue;a.style=function(a,b,c){switch(arguments.length){case 1:return i.get(a);case 2:return i[typeof b=="string"?"get":"set"](a,b)}return i.set(a,b,c)};return a})},"dojo/dom-attr":function(){define("dojo/dom-attr",["exports","./_base/sniff","./_base/lang","./dom","./dom-style",
"./dom-prop"],function(a,j,i,n,g,c){function o(a,c){var f=a.getAttributeNode&&a.getAttributeNode(c);return f&&f.specified}var f={innerHTML:1,className:1,htmlFor:j("ie"),value:1},h={classname:"class",htmlfor:"for",tabindex:"tabIndex",readonly:"readOnly"};a.has=function(a,g){var i=g.toLowerCase();return f[c.names[i]||g]||o(n.byId(a),h[i]||g)};a.get=function(a,g){var a=n.byId(a),m=g.toLowerCase(),j=c.names[m]||g,p=f[j];value=a[j];if(p&&typeof value!="undefined")return value;if(j!="href"&&(typeof value==
"boolean"||i.isFunction(value)))return value;m=h[m]||g;return o(a,m)?a.getAttribute(m):null};a.set=function(b,l,m){b=n.byId(b);if(arguments.length==2){for(var j in l)a.set(b,j,l[j]);return b}j=l.toLowerCase();var o=c.names[j]||l,e=f[o];if(o=="style"&&typeof m!="string")return g.set(b,m),b;if(e||typeof m=="boolean"||i.isFunction(m))return c.set(b,l,m);b.setAttribute(h[j]||l,m);return b};a.remove=function(a,c){n.byId(a).removeAttribute(h[c.toLowerCase()]||c)};a.getNodeProp=function(a,f){var a=n.byId(a),
g=f.toLowerCase(),i=c.names[g]||f;if(i in a&&i!="href")return a[i];g=h[g]||f;return o(a,g)?a.getAttribute(g):null}})},"dojo/dom-prop":function(){define("dojo/dom-prop",["exports","./_base/kernel","./_base/sniff","./_base/lang","./dom","./dom-style","./dom-construct","./_base/connect"],function(a,j,i,n,g,c,o,f){var h={},b=0,l=j._scopeName+"attrid",m={col:1,colgroup:1,table:1,tbody:1,tfoot:1,thead:1,tr:1,title:1};a.names={"class":"className","for":"htmlFor",tabindex:"tabIndex",readonly:"readOnly",colspan:"colSpan",
frameborder:"frameBorder",rowspan:"rowSpan",valuetype:"valueType"};a.get=function(b,c){var b=g.byId(b),e=c.toLowerCase();return b[a.names[e]||c]};a.set=function(j,p,e){j=g.byId(j);if(arguments.length==2&&typeof p!="string"){for(var d in p)a.set(j,d,p[d]);return j}d=p.toLowerCase();d=a.names[d]||p;if(d=="style"&&typeof e!="string")return c.style(j,e),j;if(d=="innerHTML")return i("ie")&&j.tagName.toLowerCase()in m?(o.empty(j),j.appendChild(o.toDom(e,j.ownerDocument))):j[d]=e,j;if(n.isFunction(e)){var k=
j[l];k||(k=b++,j[l]=k);h[k]||(h[k]={});var q=h[k][d];if(q)f.disconnect(q);else try{delete j[d]}catch(t){}e?h[k][d]=f.connect(j,d,e):j[d]=null;return j}j[d]=e;return j}})},"dojo/dom-construct":function(){define(["exports","./_base/kernel","./_base/sniff","./_base/window","./dom","./dom-attr","./on"],function(a,j,i,n,g,c,o){function f(a,b){var c=b.parentNode;c&&c.insertBefore(a,b)}var h={option:["select"],tbody:["table"],thead:["table"],tfoot:["table"],tr:["table","tbody"],td:["table","tbody","tr"],
th:["table","thead","tr"],legend:["fieldset"],caption:["table"],colgroup:["table"],col:["table","colgroup"],li:["ul"]},b=/<\s*([\w\:]+)/,l={},m=0,r="__"+j._scopeName+"ToDomId",p;for(p in h)if(h.hasOwnProperty(p))j=h[p],j.pre=p=="option"?'<select multiple="multiple">':"<"+j.join("><")+">",j.post="</"+j.reverse().join("></")+">";var e=null,d;o(window,"unload",function(){e=null});a.toDom=function(a,c){var c=c||n.doc,d=c[r];d||(c[r]=d=++m+"",l[d]=c.createElement("div"));a+="";var e=a.match(b),f=e?e[1].toLowerCase():
"",d=l[d];if(e&&h[f]){e=h[f];d.innerHTML=e.pre+a+e.post;for(e=e.length;e;--e)d=d.firstChild}else d.innerHTML=a;if(d.childNodes.length==1)return d.removeChild(d.firstChild);for(f=c.createDocumentFragment();e=d.firstChild;)f.appendChild(e);return f};a.place=function(b,c,d){c=g.byId(c);typeof b=="string"&&(b=/^\s*</.test(b)?a.toDom(b,c.ownerDocument):g.byId(b));if(typeof d=="number"){var e=c.childNodes;!e.length||e.length<=d?c.appendChild(b):f(b,e[d<0?0:d])}else switch(d){case "before":f(b,c);break;
case "after":d=b;(e=c.parentNode)&&(e.lastChild==c?e.appendChild(d):e.insertBefore(d,c.nextSibling));break;case "replace":c.parentNode.replaceChild(b,c);break;case "only":a.empty(c);c.appendChild(b);break;case "first":if(c.firstChild){f(b,c.firstChild);break}default:c.appendChild(b)}return b};a.create=function(b,d,e,f){var h=n.doc;if(e)e=g.byId(e),h=e.ownerDocument;typeof b=="string"&&(b=h.createElement(b));d&&c.set(b,d);e&&a.place(b,e,f);return b};a.empty=i("ie")?function(b){for(var b=g.byId(b),
c;c=b.lastChild;)a.destroy(c)}:function(a){g.byId(a).innerHTML=""};a.destroy=function(a){a=g.byId(a);try{var b=a.ownerDocument;if(!e||d!=b)e=b.createElement("div"),d=b;e.appendChild(a.parentNode?a.parentNode.removeChild(a):a);e.innerHTML=""}catch(c){}}})},"dojo/dom-class":function(){define("dojo/dom-class",["./_base/lang","./_base/array","./dom"],function(a,j,i){function n(a){if(typeof a=="string"||a instanceof String){if(a&&!c.test(a))return o[0]=a,o;a=a.split(c);a.length&&!a[0]&&a.shift();a.length&&
!a[a.length-1]&&a.pop();return a}if(!a)return[];return j.filter(a,function(a){return a})}var g,c=/\s+/,o=[""],f={};return g={contains:function(a,b){return(" "+i.byId(a).className+" ").indexOf(" "+b+" ")>=0},add:function(a,b){var a=i.byId(a),b=n(b),c=a.className,f,c=c?" "+c+" ":" ";f=c.length;for(var g=0,j=b.length,e;g<j;++g)(e=b[g])&&c.indexOf(" "+e+" ")<0&&(c+=e+" ");f<c.length&&(a.className=c.substr(1,c.length-2))},remove:function(c,b){var c=i.byId(c),f;if(b!==void 0){b=n(b);f=" "+c.className+" ";
for(var g=0,j=b.length;g<j;++g)f=f.replace(" "+b[g]+" "," ");f=a.trim(f)}else f="";c.className!=f&&(c.className=f)},replace:function(a,b,c){a=i.byId(a);f.className=a.className;g.remove(f,c);g.add(f,b);a.className!==f.className&&(a.className=f.className)},toggle:function(a,b,c){a=i.byId(a);if(c===void 0)for(var b=n(b),f=0,j=b.length,o;f<j;++f)o=b[f],g[g.contains(a,o)?"remove":"add"](a,o);else g[c?"add":"remove"](a,b);return c}}})},"dojo/_base/NodeList":function(){define(["./kernel","../query","./array",
"./html","../NodeList-dom"],function(a,j,i){var j=j.NodeList,n=j.prototype;n.connect=j._adaptAsForEach(function(){return a.connect.apply(this,arguments)});n.coords=j._adaptAsMap(a.coords);j.events=["blur","focus","change","click","error","keydown","keypress","keyup","load","mousedown","mouseenter","mouseleave","mousemove","mouseout","mouseover","mouseup","submit"];i.forEach(j.events,function(a){var c="on"+a;n[c]=function(a,f){return this.connect(c,a,f)}});a.NodeList=j;return a.NodeList})},"dojo/query":function(){define(["./_base/kernel",
"./has","./dom","./on","./_base/array","./_base/lang","./selector/_loader","./selector/_loader!default"],function(a,j,i,n,g,c,o,f){function h(a,b){var c=function(c,d){if(typeof d=="string"&&(d=i.byId(d),!d))return new b([]);var e=typeof c=="string"?a(c,d):c.orphan?c:[c];if(e.orphan)return e;return new b(e)};c.matches=a.match||function(a,b,d){return c.filter([a],b,d).length>0};c.filter=a.filter||function(a,b,d){return c(b,d).filter(function(b){return g.indexOf(a,b)>-1})};if(typeof a!="function")var d=
a.search,a=function(a,b){return d(b||document,a)};return c}j.add("array-extensible",function(){return c.delegate([],{length:1}).length==1&&!j("bug-for-in-skips-shadowed")});var b=Array.prototype,l=b.slice,m=b.concat,r=g.forEach,p=function(b,c,d){c=[0].concat(l.call(c,0));d=d||a.global;return function(a){c[0]=a;return b.apply(d,c)}},e=function(a){var b=this instanceof d&&j("array-extensible");typeof a=="number"&&(a=Array(a));var e=a&&"length"in a?a:arguments;if(b||!e.sort){for(var f=b?this:[],g=f.length=
e.length,h=0;h<g;h++)f[h]=e[h];if(b)return f;e=f}c._mixin(e,k);e._NodeListCtor=function(a){return d(a)};return e},d=e,k=d.prototype=j("array-extensible")?[]:{};d._wrap=k._wrap=function(a,b,c){a=new (c||this._NodeListCtor||d)(a);return b?a._stash(b):a};d._adaptAsMap=function(a,b){return function(){return this.map(p(a,arguments,b))}};d._adaptAsForEach=function(a,b){return function(){this.forEach(p(a,arguments,b));return this}};d._adaptAsFilter=function(a,b){return function(){return this.filter(p(a,
arguments,b))}};d._adaptWithCondition=function(b,c,d){return function(){var e=arguments,f=p(b,e,d);if(c.call(d||a.global,e))return this.map(f);this.forEach(f);return this}};r(["slice","splice"],function(a){var c=b[a];k[a]=function(){return this._wrap(c.apply(this,arguments),a=="slice"?this:null)}});r(["indexOf","lastIndexOf","every","some"],function(b){var c=g[b];k[b]=function(){return c.apply(a,[this].concat(l.call(arguments,0)))}});c.extend(e,{constructor:d,_NodeListCtor:d,toString:function(){return this.join(",")},
_stash:function(a){this._parent=a;return this},on:function(a,b){var c=this.map(function(c){return n(c,a,b)});c.remove=function(){for(var a=0;a<c.length;a++)c[a].remove()};return c},end:function(){return this._parent?this._parent:new this._NodeListCtor(0)},concat:function(){var a=c.isArray(this)?this:l.call(this,0),b=g.map(arguments,function(a){return a&&!c.isArray(a)&&(typeof e!="undefined"&&a.constructor===e||a.constructor===this._NodeListCtor)?l.call(a,0):a});return this._wrap(m.apply(a,b),this)},
map:function(a,b){return this._wrap(g.map(this,a,b),this)},forEach:function(a,b){r(this,a,b);return this},filter:function(a){var b=arguments,c=this,d=0;if(typeof a=="string"){c=q._filterResult(this,b[0]);if(b.length==1)return c._stash(this);d=1}return this._wrap(g.filter(c,b[d],b[d+1]),this)},instantiate:function(a,b){var d=c.isFunction(a)?a:c.getObject(a),b=b||{};return this.forEach(function(a){new d(b,a)})},at:function(){var a=new this._NodeListCtor(0);r(arguments,function(b){b<0&&(b=this.length+
b);this[b]&&a.push(this[b])},this);return a._stash(this)}});var q=h(f,e);a.query=h(f,function(a){return e(a)});q.load=function(a,b,c){o.load(a,b,function(a){c(h(a,e))})};a._filterQueryResult=q._filterResult=function(a,b,c){return new e(q.filter(a,b,c))};a.NodeList=q.NodeList=e;return q})},"dojo/selector/_loader":function(){define(["../has","require"],function(a,j){var i=document.createElement("div");a.add("dom-qsa2.1",!!i.querySelectorAll);a.add("dom-qsa3",function(){try{return i.innerHTML="<p class='TEST'></p>",
i.querySelectorAll(".TEST:empty").length==1}catch(a){}});var n;return{load:function(g,c,i){var f=j,g=g=="default"?a("config-selectorEngine")||"css3":g,g=g=="css2"||g=="lite"?"./lite":g=="css2.1"?a("dom-qsa2.1")?"./lite":"./acme":g=="css3"?a("dom-qsa3")?"./lite":"./acme":g=="acme"?"./acme":(f=c)&&g;if(g.charAt(g.length-1)=="?")var g=g.substring(0,g.length-1),h=!0;if(h&&(a("dom-compliant-qsa")||n))return i(n);f([g],function(a){g!="./lite"&&(n=a);i(a)})}}})},"dojo/selector/acme":function(){define(["../_base/kernel",
"../dom","../_base/sniff","../_base/array","../_base/lang","../_base/window"],function(a,j,i,n,g,c){var o=g.trim,f=n.forEach,h=(i("webkit")||i("mozilla"))&&c.doc.compatMode=="BackCompat",b=!1,l=function(){return!0},m=function(a){a+=">~+".indexOf(a.slice(-1))>=0?" * ":" ";for(var c=function(b,c){return o(a.slice(b,c))},d=[],e=-1,f=-1,g=-1,k=-1,h=-1,i=-1,j=-1,l="",m="",n,q=0,G=a.length,p=null,s=null,t=function(){if(i>=0)p.id=c(i,q).replace(/\\/g,""),i=-1;if(j>=0){var a=j==q?null:c(j,q);p[">~+".indexOf(a)<
0?"tag":"oper"]=a;j=-1}h>=0&&(p.classes.push(c(h+1,q).replace(/\\/g,"")),h=-1)};l=m,m=a.charAt(q),q<G;q++)if(l!="\\")if(p||(n=q,p={query:null,pseudos:[],attrs:[],classes:[],tag:null,oper:null,id:null,getTag:function(){return b?this.otag:this.tag}},j=q),e>=0)if(m=="]"){s.attr?s.matchFor=c(g||e+1,q):s.attr=c(e+1,q);if((e=s.matchFor)&&(e.charAt(0)=='"'||e.charAt(0)=="'"))s.matchFor=e.slice(1,-1);p.attrs.push(s);s=null;e=g=-1}else{if(m=="=")g="|~^$*".indexOf(l)>=0?l:"",s.type=g+m,s.attr=c(e+1,q-g.length),
g=q+1}else if(f>=0){if(m==")"){if(k>=0)s.value=c(f+1,q);k=f=-1}}else if(m=="#")t(),i=q+1;else if(m==".")t(),h=q;else if(m==":")t(),k=q;else if(m=="[")t(),e=q,s={};else if(m=="(")k>=0&&(s={name:c(k+1,q),value:null},p.pseudos.push(s)),f=q;else if(m==" "&&l!=m){t();k>=0&&p.pseudos.push({name:c(k+1,q)});p.loops=p.pseudos.length||p.attrs.length||p.classes.length;p.oquery=p.query=c(n,q);p.otag=p.tag=p.oper?null:p.tag||"*";if(p.tag)p.tag=p.tag.toUpperCase();if(d.length&&d[d.length-1].oper)p.infixOper=d.pop(),
p.query=p.infixOper.query+" "+p.query;d.push(p);p=null}return d},r=function(a,b){if(!a)return b;if(!b)return a;return function(){return a.apply(window,arguments)&&b.apply(window,arguments)}},p=function(a,b){var c=b||[];a&&c.push(a);return c},e=function(a){return 1==a.nodeType},d=function(a,c){if(!a)return"";if(c=="class")return a.className||"";if(c=="for")return a.htmlFor||"";if(c=="style")return a.style.cssText||"";return(b?a.getAttribute(c):a.getAttribute(c,2))||""},k={"*=":function(a,b){return function(c){return d(c,
a).indexOf(b)>=0}},"^=":function(a,b){return function(c){return d(c,a).indexOf(b)==0}},"$=":function(a,b){return function(c){c=" "+d(c,a);return c.lastIndexOf(b)==c.length-b.length}},"~=":function(a,b){var c=" "+b+" ";return function(b){return(" "+d(b,a)+" ").indexOf(c)>=0}},"|=":function(a,b){var c=b+"-";return function(e){e=d(e,a);return e==b||e.indexOf(c)==0}},"=":function(a,b){return function(c){return d(c,a)==b}}},q=typeof c.doc.firstChild.nextElementSibling=="undefined",t=!q?"nextElementSibling":
"nextSibling",s=!q?"previousElementSibling":"previousSibling",u=q?e:l,B=function(a){for(;a=a[s];)if(u(a))return!1;return!0},w=function(a){for(;a=a[t];)if(u(a))return!1;return!0},C=function(a){var b=a.parentNode,c=0,d=b.children||b.childNodes,e=a._i||-1,f=b._l||-1;if(!d)return-1;d=d.length;if(f==d&&e>=0&&f>=0)return e;b._l=d;e=-1;for(b=b.firstElementChild||b.firstChild;b;b=b[t])if(u(b))b._i=++c,a===b&&(e=c);return e},Q=function(a){return!(C(a)%2)},G=function(a){return C(a)%2},S={checked:function(){return function(a){return!!("checked"in
a?a.checked:a.selected)}},"first-child":function(){return B},"last-child":function(){return w},"only-child":function(){return function(a){return B(a)&&w(a)}},empty:function(){return function(a){for(var b=a.childNodes,a=a.childNodes.length-1;a>=0;a--){var c=b[a].nodeType;if(c===1||c==3)return!1}return!0}},contains:function(a,b){var c=b.charAt(0);if(c=='"'||c=="'")b=b.slice(1,-1);return function(a){return a.innerHTML.indexOf(b)>=0}},not:function(a,b){var c=m(b)[0],d={el:1};if(c.tag!="*")d.tag=1;if(!c.classes.length)d.classes=
1;var e=O(c,d);return function(a){return!e(a)}},"nth-child":function(a,b){var c=parseInt;if(b=="odd")return G;else if(b=="even")return Q;if(b.indexOf("n")!=-1){var d=b.split("n",2),e=d[0]?d[0]=="-"?-1:c(d[0]):1,f=d[1]?c(d[1]):0,g=0,k=-1;e>0?f<0?f=f%e&&e+f%e:f>0&&(f>=e&&(g=f-f%e),f%=e):e<0&&(e*=-1,f>0&&(k=f,f%=e));if(e>0)return function(a){a=C(a);return a>=g&&(k<0||a<=k)&&a%e==f};else b=f}var h=c(b);return function(a){return C(a)==h}}},T=i("ie")&&(i("ie")<9||a.isQuirks)?function(a){var c=a.toLowerCase();
c=="class"&&(a="className");return function(d){return b?d.getAttribute(a):d[a]||d[c]}}:function(a){return function(b){return b&&b.getAttribute&&b.hasAttribute(a)}},O=function(a,b){if(!a)return l;var b=b||{},c=null;"el"in b||(c=r(c,e));"tag"in b||a.tag!="*"&&(c=r(c,function(b){return b&&b.tagName==a.getTag()}));"classes"in b||f(a.classes,function(a,b){var d=RegExp("(?:^|\\s)"+a+"(?:\\s|$)");c=r(c,function(a){return d.test(a.className)});c.count=b});"pseudos"in b||f(a.pseudos,function(a){var b=a.name;
S[b]&&(c=r(c,S[b](b,a.value)))});"attrs"in b||f(a.attrs,function(a){var b,d=a.attr;a.type&&k[a.type]?b=k[a.type](d,a.matchFor):d.length&&(b=T(d));b&&(c=r(c,b))});"id"in b||a.id&&(c=r(c,function(b){return!!b&&b.id==a.id}));c||"default"in b||(c=l);return c},v=function(a){return function(b,c,d){for(;b=b[t];)if(!q||e(b)){(!d||R(b,d))&&a(b)&&c.push(b);break}return c}},z=function(a){return function(b,c,d){for(b=b[t];b;){if(u(b)){if(d&&!R(b,d))break;a(b)&&c.push(b)}b=b[t]}return c}},F=function(a){a=a||l;
return function(b,c,d){for(var e=0,f=b.children||b.childNodes;b=f[e++];)u(b)&&(!d||R(b,d))&&a(b,e)&&c.push(b);return c}},A={},E=function(a){var b=A[a.query];if(b)return b;var d=a.infixOper,d=d?d.oper:"",e=O(a,{el:1}),f="*"==a.tag,g=c.doc.getElementsByClassName;if(d){g={el:1};if(f)g.tag=1;e=O(a,g);"+"==d?b=v(e):"~"==d?b=z(e):">"==d&&(b=F(e))}else if(a.id)e=!a.loops&&f?l:O(a,{el:1,id:1}),b=function(b,c){var d=j.byId(a.id,b.ownerDocument||b);if(d&&e(d))if(9==b.nodeType)return p(d,c);else{for(var f=d.parentNode;f;){if(f==
b)break;f=f.parentNode}if(f)return p(d,c)}};else if(g&&/\{\s*\[native code\]\s*\}/.test(String(g))&&a.classes.length&&!h)var e=O(a,{el:1,classes:1,id:1}),k=a.classes.join(" "),b=function(a,b,c){for(var b=p(0,b),d,f=0,g=a.getElementsByClassName(k);d=g[f++];)e(d,a)&&R(d,c)&&b.push(d);return b};else!f&&!a.loops?b=function(b,c,d){for(var c=p(0,c),e=0,f=b.getElementsByTagName(a.getTag());b=f[e++];)R(b,d)&&c.push(b);return c}:(e=O(a,{el:1,tag:1,id:1}),b=function(b,c,d){for(var c=p(0,c),f,g=0,k=b.getElementsByTagName(a.getTag());f=
k[g++];)e(f,b)&&R(f,d)&&c.push(f);return c});return A[a.query]=b},J={},I={},V=function(a){var b=m(o(a));if(b.length==1){var c=E(b[0]);return function(a){if(a=c(a,[]))a.nozip=!0;return a}}return function(a){for(var a=p(a),c,d,e=b.length,f,g,k=0;k<e;k++){g=[];c=b[k];d=a.length-1;if(d>0)f={},g.nozip=!0;d=E(c);for(var h=0;c=a[h];h++)d(c,g,f);if(!g.length)break;a=g}return g}},a=navigator.userAgent,a=i("webkit")&&a.indexOf("WebKit/")>0&&parseFloat(a.split("WebKit/")[1])>528,Y=i("ie")?"commentStrip":"nozip",
K=!!c.doc.querySelectorAll&&(!i("safari")||i("safari")>3.1||a),D=/n\+\d|([^ ])?([>~+])([^ =])?/g,N=function(a,b,c,d){return c?(b?b+" ":"")+c+(d?" "+d:""):a},x=function(a,b){a=a.replace(D,N);if(K){var c=I[a];if(c&&!b)return c}if(c=J[a])return c;var c=a.charAt(0),d=-1==a.indexOf(" ");a.indexOf("#")>=0&&d&&(b=!0);if(K&&!b&&">~+".indexOf(c)==-1&&(!i("ie")||a.indexOf(":")==-1)&&!(h&&a.indexOf(".")>=0)&&a.indexOf(":contains")==-1&&a.indexOf(":checked")==-1&&a.indexOf("|=")==-1){var e=">~+".indexOf(a.charAt(a.length-
1))>=0?a+" *":a;return I[a]=function(b){try{if(!(9==b.nodeType||d))throw"";var c=b.querySelectorAll(e);c[Y]=!0;return c}catch(f){return x(a,!0)(b)}}}else{var f=a.split(/\s*,\s*/);return J[a]=f.length<2?V(a):function(a){for(var b=0,c=[],d;d=f[b++];)c=c.concat(V(d)(a));return c}}},y=0,H=i("ie")?function(a){return b?a.getAttribute("_uid")||a.setAttribute("_uid",++y)||y:a.uniqueID}:function(a){return a._uid||(a._uid=++y)},R=function(a,b){if(!b)return 1;var c=H(a);if(!b[c])return b[c]=1;return 0},Z=function(a){if(a&&
a.nozip)return a;var c=[];if(!a||!a.length)return c;a[0]&&c.push(a[0]);if(a.length<2)return c;y++;var d,f;if(i("ie")&&b){var g=y+"";a[0].setAttribute("_zipIdx",g);for(d=1;f=a[d];d++)a[d].getAttribute("_zipIdx")!=g&&c.push(f),f.setAttribute("_zipIdx",g)}else if(i("ie")&&a.commentStrip)try{for(d=1;f=a[d];d++)e(f)&&c.push(f)}catch(k){}else{a[0]&&(a[0]._zipIdx=y);for(d=1;f=a[d];d++)a[d]._zipIdx!=y&&c.push(f),f._zipIdx=y}return c},W=function(a,d){var d=d||c.doc,e=d.ownerDocument||d.documentElement;b=d.contentType&&
d.contentType=="application/xml"||i("opera")&&(d.doctype||e.toString()=="[object XMLDocument]")||!!e&&(i("ie")?e.xml:d.xmlVersion||e.xmlVersion);if((e=x(a)(d))&&e.nozip)return e;return Z(e)};W.filter=function(a,b,c){for(var d=[],e=m(b),e=e.length==1&&!/[^\w#\.]/.test(b)?O(e[0]):function(a){return n.indexOf(W(b,j.byId(c)),a)!=-1},f=0,g;g=a[f];f++)e(g)&&d.push(g);return d};return W})},"dojo/NodeList-dom":function(){define(["./_base/kernel","./query","./_base/array","./_base/lang","./dom-class","./dom-construct",
"./dom-geometry","./dom-attr","./dom-style"],function(a,j,i,n,g,c,o,f,h){function b(a){return function(b,c,d){if(arguments.length==2)return a[typeof c=="string"?"get":"set"](b,c);return a.set(b,c,d)}}var l=function(a){return a.length==1&&typeof a[0]=="string"},m=function(a){var b=a.parentNode;b&&b.removeChild(a)},r=j.NodeList,p=r._adaptWithCondition,e=r._adaptAsForEach,d=r._adaptAsMap;n.extend(r,{_normalize:function(b,d){var e=b.parse===!0;if(typeof b.template=="string")var f=b.templateFunc||a.string&&
a.string.substitute,b=f?f(b.template,b):b;f=typeof b;f=="string"||f=="number"?(b=c.toDom(b,d&&d.ownerDocument),b=b.nodeType==11?n._toArray(b.childNodes):[b]):n.isArrayLike(b)?n.isArray(b)||(b=n._toArray(b)):b=[b];if(e)b._runParse=!0;return b},_cloneNode:function(a){return a.cloneNode(!0)},_place:function(b,d,e,f){if(!(d.nodeType!=1&&e=="only"))for(var g,h=b.length,i=h-1;i>=0;i--){var j=f?this._cloneNode(b[i]):b[i];if(b._runParse&&a.parser&&a.parser.parse){g||(g=d.ownerDocument.createElement("div"));
g.appendChild(j);a.parser.parse(g);for(j=g.firstChild;g.firstChild;)g.removeChild(g.firstChild)}i==h-1?c.place(j,d,e):d.parentNode.insertBefore(j,d);d=j}},attr:p(b(f),l),style:p(b(h),l),addClass:e(g.add),removeClass:e(g.remove),replaceClass:e(g.replace),toggleClass:e(g.toggle),empty:e(c.empty),removeAttr:e(f.remove),position:d(o.position),marginBox:d(o.getMarginBox),place:function(a,b){var d=j(a)[0];return this.forEach(function(a){c.place(a,d,b)})},orphan:function(a){return(a?j._filterResult(this,
a):this).forEach(m)},adopt:function(a,b){return j(a).place(this[0],b)._stash(this)},query:function(a){if(!a)return this;var b=new r;this.map(function(c){j(a,c).forEach(function(a){a!==void 0&&b.push(a)})});return b._stash(this)},filter:function(a){var b=arguments,c=this,d=0;if(typeof a=="string"){c=j._filterResult(this,b[0]);if(b.length==1)return c._stash(this);d=1}return this._wrap(i.filter(c,b[d],b[d+1]),this)},addContent:function(a,b){for(var a=this._normalize(a,this[0]),c=0,d;d=this[c];c++)this._place(a,
d,b,c>0);return this}});return r})},"dojo/_base/xhr":function(){define(["./kernel","./sniff","require","../io-query","../dom","../dom-form","./Deferred","./config","./json","./lang","./array","../on"],function(a,j,i,n,g,c,o,f,h,b,l,m){j.add("native-xhr",function(){return typeof XMLHttpRequest!=="undefined"});a._xhrObj=i.getXhr;var r=a.config;a.objectToQuery=n.objectToQuery;a.queryToObject=n.queryToObject;a.fieldToObject=c.fieldToObject;a.formToObject=c.toObject;a.formToQuery=c.toQuery;a.formToJson=
c.toJson;a._blockAsync=!1;var p=a._contentHandlers=a.contentHandlers={text:function(a){return a.responseText},json:function(a){return h.fromJson(a.responseText||null)},"json-comment-filtered":function(a){var a=a.responseText,b=a.indexOf("/*"),c=a.lastIndexOf("*/");if(b==-1||c==-1)throw Error("JSON was not comment filtered");return h.fromJson(a.substring(b+2,c))},javascript:function(b){return a.eval(b.responseText)},xml:function(a){var b=a.responseXML;if(j("ie")&&(!b||!b.documentElement)){var c=function(a){return"MSXML"+
a+".DOMDocument"},c=["Microsoft.XMLDOM",c(6),c(4),c(3),c(2)];l.some(c,function(c){try{var d=new ActiveXObject(c);d.async=!1;d.loadXML(a.responseText);b=d}catch(e){return!1}return!0})}return b},"json-comment-optional":function(a){return a.responseText&&/^[^{\[]*\/\*/.test(a.responseText)?p["json-comment-filtered"](a):p.json(a)}};a._ioSetArgs=function(d,e,f,h){var k={args:d,url:d.url},i=null;if(d.form){var i=g.byId(d.form),j=i.getAttributeNode("action");k.url=k.url||(j?j.value:null);i=c.toObject(i)}j=
[{}];i&&j.push(i);d.content&&j.push(d.content);d.preventCache&&j.push({"dojo.preventCache":(new Date).valueOf()});k.query=n.objectToQuery(b.mixin.apply(null,j));k.handleAs=d.handleAs||"text";var l=new o(e);l.addCallbacks(f,function(a){return h(a,l)});var m=d.load;m&&b.isFunction(m)&&l.addCallback(function(a){return m.call(d,a,k)});var p=d.error;p&&b.isFunction(p)&&l.addErrback(function(a){return p.call(d,a,k)});var q=d.handle;q&&b.isFunction(q)&&l.addBoth(function(a){return q.call(d,a,k)});r.ioPublish&&
a.publish&&k.args.ioPublish!==!1&&(l.addCallbacks(function(b){a.publish("/dojo/io/load",[l,b]);return b},function(b){a.publish("/dojo/io/error",[l,b]);return b}),l.addBoth(function(b){a.publish("/dojo/io/done",[l,b]);return b}));l.ioArgs=k;return l};var e=function(a){a.canceled=!0;var b=a.ioArgs.xhr,c=typeof b.abort;(c=="function"||c=="object"||c=="unknown")&&b.abort();a=a.ioArgs.error;if(!a)a=Error("xhr cancelled"),a.dojoType="cancel";return a},d=function(a){a=p[a.ioArgs.handleAs](a.ioArgs.xhr);
return a===void 0?null:a},k=function(a){return a},q=null,t=[],s=0,u=function(b){s<=0&&(s=0,r.ioPublish&&a.publish&&(!b||b&&b.ioArgs.args.ioPublish!==!1)&&a.publish("/dojo/io/stop"))},B=function(){var b=(new Date).getTime();if(!a._blockAsync)for(var c=0,d;c<t.length&&(d=t[c]);c++){var e=d.dfd;(function(){if(!e||e.canceled||!d.validCheck(e))t.splice(c--,1),s-=1;else if(d.ioCheck(e))t.splice(c--,1),d.resHandle(e),s-=1;else if(e.startTime&&e.startTime+(e.ioArgs.args.timeout||0)<b){t.splice(c--,1);var a=
Error("timeout exceeded");a.dojoType="timeout";e.errback(a);e.cancel();s-=1}}).call(this)}u(e);t.length||(clearInterval(q),q=null)};a._ioCancelAll=function(){try{l.forEach(t,function(a){try{a.dfd.cancel()}catch(b){}})}catch(a){}};j("ie")&&m(window,"unload",a._ioCancelAll);a._ioNotifyStart=function(b){r.ioPublish&&a.publish&&b.ioArgs.args.ioPublish!==!1&&(s||a.publish("/dojo/io/start"),s+=1,a.publish("/dojo/io/send",[b]))};a._ioWatch=function(a,b,c,d){var e=a.ioArgs.args;if(e.timeout)a.startTime=(new Date).getTime();
t.push({dfd:a,validCheck:b,ioCheck:c,resHandle:d});q||(q=setInterval(B,50));e.sync&&B()};var w=function(a){return a.ioArgs.xhr.readyState},C=function(a){return 4==a.ioArgs.xhr.readyState},Q=function(b){var c=b.ioArgs.xhr;if(a._isDocumentOk(c))b.callback(b);else{var d=Error("Unable to load "+b.ioArgs.url+" status:"+c.status);d.status=c.status;d.responseText=c.responseText;d.xhr=c;b.errback(d)}};a._ioAddQueryToUrl=function(a){if(a.query.length)a.url+=(a.url.indexOf("?")==-1?"?":"&")+a.query,a.query=
null};a.xhr=function(b,c,g){var h=a._ioSetArgs(c,e,d,k),i=h.ioArgs,j=i.xhr=a._xhrObj(i.args);if(!j)return h.cancel(),h;"postData"in c?i.query=c.postData:"putData"in c?i.query=c.putData:"rawBody"in c?i.query=c.rawBody:(arguments.length>2&&!g||"POST|PUT".indexOf(b.toUpperCase())==-1)&&a._ioAddQueryToUrl(i);j.open(b,i.url,c.sync!==!0,c.user||void 0,c.password||void 0);if(c.headers)for(var l in c.headers)l.toLowerCase()==="content-type"&&!c.contentType?c.contentType=c.headers[l]:c.headers[l]&&j.setRequestHeader(l,
c.headers[l]);c.contentType!==!1&&j.setRequestHeader("Content-Type",c.contentType||"application/x-www-form-urlencoded");(!c.headers||!("X-Requested-With"in c.headers))&&j.setRequestHeader("X-Requested-With","XMLHttpRequest");a._ioNotifyStart(h);if(f.debugAtAllCosts)j.send(i.query);else try{j.send(i.query)}catch(m){i.error=m,h.cancel()}a._ioWatch(h,w,C,Q);return h};a.xhrGet=function(b){return a.xhr("GET",b)};a.rawXhrPost=a.xhrPost=function(b){return a.xhr("POST",b,!0)};a.rawXhrPut=a.xhrPut=function(b){return a.xhr("PUT",
b,!0)};a.xhrDelete=function(b){return a.xhr("DELETE",b)};a._isDocumentOk=function(a){a=a.status||0;return a>=200&&a<300||a==304||a==1223||!a};a._getText=function(b){var c;a.xhrGet({url:b,sync:!0,load:function(a){c=a}});return c};b.mixin(a.xhr,{_xhrObj:a._xhrObj,fieldToObject:c.fieldToObject,formToObject:c.toObject,objectToQuery:n.objectToQuery,formToQuery:c.toQuery,formToJson:c.toJson,queryToObject:n.queryToObject,contentHandlers:p,_ioSetArgs:a._ioSetArgs,_ioCancelAll:a._ioCancelAll,_ioNotifyStart:a._ioNotifyStart,
_ioWatch:a._ioWatch,_ioAddQueryToUrl:a._ioAddQueryToUrl,_isDocumentOk:a._isDocumentOk,_getText:a._getText,get:a.xhrGet,post:a.xhrPost,put:a.xhrPut,del:a.xhrDelete});return a.xhr})},"dojo/io-query":function(){define(["./_base/lang"],function(a){var j={};return{objectToQuery:function(i){var n=encodeURIComponent,g=[],c;for(c in i){var o=i[c];if(o!=j[c]){var f=n(c)+"=";if(a.isArray(o))for(var h=0,b=o.length;h<b;++h)g.push(f+n(o[h]));else g.push(f+n(o))}}return g.join("&")},queryToObject:function(i){for(var j=
decodeURIComponent,i=i.split("&"),g={},c,o,f=0,h=i.length;f<h;++f)if(o=i[f],o.length){var b=o.indexOf("=");b<0?(c=j(o),o=""):(c=j(o.slice(0,b)),o=j(o.slice(b+1)));typeof g[c]=="string"&&(g[c]=[g[c]]);a.isArray(g[c])?g[c].push(o):g[c]=o}return g}}})},"dojo/dom-form":function(){define(["./_base/lang","./dom","./io-query","./json"],function(a,j,i,n){var g={fieldToObject:function(a){var g=null;if(a=j.byId(a)){var f=a.name,h=(a.type||"").toLowerCase();if(f&&h&&!a.disabled)if(h=="radio"||h=="checkbox"){if(a.checked)g=
a.value}else if(a.multiple){g=[];for(a=[a.firstChild];a.length;)for(f=a.pop();f;f=f.nextSibling)if(f.nodeType==1&&f.tagName.toLowerCase()=="option")f.selected&&g.push(f.value);else{f.nextSibling&&a.push(f.nextSibling);f.firstChild&&a.push(f.firstChild);break}}else g=a.value}return g},toObject:function(c){for(var i={},c=j.byId(c).elements,f=0,h=c.length;f<h;++f){var b=c[f],l=b.name,m=(b.type||"").toLowerCase();if(l&&m&&"file|submit|image|reset|button".indexOf(m)<0&&!b.disabled){var n=i,p=l,b=g.fieldToObject(b);
if(b!==null){var e=n[p];typeof e=="string"?n[p]=[e,b]:a.isArray(e)?e.push(b):n[p]=b}if(m=="image")i[l+".x"]=i[l+".y"]=i[l].x=i[l].y=0}}return i},toQuery:function(a){return i.objectToQuery(g.toObject(a))},toJson:function(a,i){return n.stringify(g.toObject(a),null,i?4:0)}};return g})},"dojo/_base/fx":function(){define(["./kernel","./config","./lang","../Evented","./Color","./connect","./sniff","../dom","../dom-style"],function(a,j,i,n,g,c,o,f,h){var b=i.mixin;a._Line=function(a,b){this.start=a;this.end=
b};a._Line.prototype.getValue=function(a){return(this.end-this.start)*a+this.start};a.Animation=function(c){b(this,c);if(i.isArray(this.curve))this.curve=new a._Line(this.curve[0],this.curve[1])};a.Animation.prototype=new n;a._Animation=a.Animation;i.extend(a.Animation,{duration:350,repeat:0,rate:20,_percent:0,_startRepeatCount:0,_getStep:function(){var a=this._percent,b=this.easing;return b?b(a):a},_fire:function(a,b){var c=b||[];if(this[a])if(j.debugAtAllCosts)this[a].apply(this,c);else try{this[a].apply(this,
c)}catch(e){}return this},play:function(a,b){this._delayTimer&&this._clearTimer();if(b)this._stopTimer(),this._active=this._paused=!1,this._percent=0;else if(this._active&&!this._paused)return this;this._fire("beforeBegin",[this.node]);var c=a||this.delay,e=i.hitch(this,"_play",b);if(c>0)return this._delayTimer=setTimeout(e,c),this;e();return this},_play:function(){this._delayTimer&&this._clearTimer();this._startTime=(new Date).valueOf();this._paused&&(this._startTime-=this.duration*this._percent);
this._active=!0;this._paused=!1;var a=this.curve.getValue(this._getStep());if(!this._percent){if(!this._startRepeatCount)this._startRepeatCount=this.repeat;this._fire("onBegin",[a])}this._fire("onPlay",[a]);this._cycle();return this},pause:function(){this._delayTimer&&this._clearTimer();this._stopTimer();if(!this._active)return this;this._paused=!0;this._fire("onPause",[this.curve.getValue(this._getStep())]);return this},gotoPercent:function(a,b){this._stopTimer();this._active=this._paused=!0;this._percent=
a;b&&this.play();return this},stop:function(a){this._delayTimer&&this._clearTimer();if(!this._timer)return this;this._stopTimer();if(a)this._percent=1;this._fire("onStop",[this.curve.getValue(this._getStep())]);this._active=this._paused=!1;return this},status:function(){if(this._active)return this._paused?"paused":"playing";return"stopped"},_cycle:function(){if(this._active){var a=((new Date).valueOf()-this._startTime)/this.duration;a>=1&&(a=1);this._percent=a;this.easing&&(a=this.easing(a));this._fire("onAnimate",
[this.curve.getValue(a)]);if(this._percent<1)this._startTimer();else{this._active=!1;if(this.repeat>0)this.repeat--,this.play(null,!0);else if(this.repeat==-1)this.play(null,!0);else if(this._startRepeatCount)this.repeat=this._startRepeatCount,this._startRepeatCount=0;this._percent=0;this._fire("onEnd",[this.node]);!this.repeat&&this._stopTimer()}}return this},_clearTimer:function(){clearTimeout(this._delayTimer);delete this._delayTimer}});var l=0,m=null,r={run:function(){}};i.extend(a.Animation,
{_startTimer:function(){if(!this._timer)this._timer=c.connect(r,"run",this,"_cycle"),l++;m||(m=setInterval(i.hitch(r,"run"),this.rate))},_stopTimer:function(){if(this._timer)c.disconnect(this._timer),this._timer=null,l--;l<=0&&(clearInterval(m),m=null,l=0)}});var p=o("ie")?function(a){var b=a.style;if(!b.width.length&&h.get(a,"width")=="auto")b.width="auto"}:function(){};a._fade=function(d){d.node=f.byId(d.node);var e=b({properties:{}},d),d=e.properties.opacity={};d.start=!("start"in e)?function(){return+h.get(e.node,
"opacity")||0}:e.start;d.end=e.end;d=a.animateProperty(e);c.connect(d,"beforeBegin",i.partial(p,e.node));return d};a.fadeIn=function(c){return a._fade(b({end:1},c))};a.fadeOut=function(c){return a._fade(b({end:0},c))};a._defaultEasing=function(a){return 0.5+Math.sin((a+1.5)*Math.PI)/2};var e=function(a){this._properties=a;for(var b in a){var c=a[b];if(c.start instanceof g)c.tempColor=new g}};e.prototype.getValue=function(a){var b={},c;for(c in this._properties){var e=this._properties[c],f=e.start;
f instanceof g?b[c]=g.blendColors(f,e.end,a,e.tempColor).toCss():i.isArray(f)||(b[c]=(e.end-f)*a+f+(c!="opacity"?e.units||"px":0))}return b};a.animateProperty=function(d){var j=d.node=f.byId(d.node);if(!d.easing)d.easing=a._defaultEasing;d=new a.Animation(d);c.connect(d,"beforeBegin",d,function(){var a={},c;for(c in this.properties){if(c=="width"||c=="height")this.node.display="block";var d=this.properties[c];i.isFunction(d)&&(d=d(j));d=a[c]=b({},i.isObject(d)?d:{end:d});if(i.isFunction(d.start))d.start=
d.start(j);if(i.isFunction(d.end))d.end=d.end(j);var f=c.toLowerCase().indexOf("color")>=0,l=function(a,b){var c={height:a.offsetHeight,width:a.offsetWidth}[b];if(c!==void 0)return c;c=h.get(a,b);return b=="opacity"?+c:f?c:parseFloat(c)};if("end"in d){if(!("start"in d))d.start=l(j,c)}else d.end=l(j,c);f?(d.start=new g(d.start),d.end=new g(d.end)):d.start=c=="opacity"?+d.start:parseFloat(d.start)}this.curve=new e(a)});c.connect(d,"onAnimate",i.hitch(h,"set",d.node));return d};a.anim=function(b,c,e,
f,g,h){return a.animateProperty({node:b,duration:e||a.Animation.prototype.duration,properties:c,easing:f,onEnd:g}).play(h||0)};return{_Line:a._Line,Animation:a.Animation,_fade:a._fade,fadeIn:a.fadeIn,fadeOut:a.fadeOut,_defaultEasing:a._defaultEasing,animateProperty:a.animateProperty,anim:a.anim}})},"dojo/_base/loader":function(){define(["./kernel","../has","require","module","./json","./lang","./array"],function(a,j,i,n,g,c,o){var f=function(a){return a.replace(/\./g,"/")},h=/\/\/>>built/,b=[],l=
[],m=function(){l=o.filter(l,function(a){return a.injected!==s&&!a.executed});if(!l.length){q.holdIdle();var a=b;b=[];o.forEach(a,function(a){a(1)});q.releaseIdle()}},r=function(b,c,d){var e=/\(|\)/g,f=1;for(e.lastIndex=c;c=e.exec(b);)if(c[0]==")"?f-=1:f+=1,f==0)break;if(f!=0)throw"unmatched paren around character "+e.lastIndex+" in: "+b;return[a.trim(b.substring(d,e.lastIndex))+";\n",e.lastIndex]},p=/(\/\*([\s\S]*?)\*\/|\/\/(.*)$)/mg,e=/(^|\s)dojo\.(loadInit|require|provide|requireLocalization|requireIf|requireAfterIf|platformRequire)\s*\(/mg,
d=/(^|\s)(require|define)\s*\(/m,k=function(a,b){var c,f,g,h=[],i=[];c=[];for(b=b||a.replace(p,function(a){e.lastIndex=d.lastIndex=0;return e.test(a)||d.test(a)?"":a});c=e.exec(b);)f=e.lastIndex,g=f-c[0].length,f=r(b,f,g),c[2]=="loadInit"?h.push(f[0]):i.push(f[0]),e.lastIndex=f[1];c=h.concat(i);return c.length||!d.test(b)?[a.replace(/(^|\s)dojo\.loadInit\s*\(/g,"\n0 && dojo.loadInit("),c.join(""),c]:0},q=i.initSyncLoader(function(a,c,d){b.push(d);o.forEach(a.split(","),function(a){a=G(a,c.module);
l.push(a);S(a)});m()},m,function(b,c){var d,e,f=[],g=[];if(h.test(c)||!(d=k(c)))return 0;e=b.mid+"-*loadInit";for(var i in G("dojo",b).result.scopeMap)f.push(i),g.push('"'+i+'"');return"// xdomain rewrite of "+b.path+"\ndefine('"+e+"',{\n\tnames:"+a.toJson(f)+",\n\tdef:function("+f.join(",")+"){"+d[1]+"}});\n\ndefine("+a.toJson(f.concat(["dojo/loadInit!"+e]))+", function("+f.join(",")+"){\n"+d[0]+"});"}),t=q.sync,s=q.arrived,u=q.nonmodule,B=q.executing,w=q.executed,C=q.syncExecStack,Q=q.execQ,G=q.getModule,
S=q.injectModule,T=q.setArrived,O=q.signal,v=q.finishExec,z=q.execModule,F=q.getLegacyMode;a.provide=function(a){var b=C[0],d=c.mixin(G(f(a),i.module),{executed:B,result:c.getObject(a,!0)});T(d);if(b)(b.provides||(b.provides=[])).push(function(){d.result=c.getObject(a);delete d.provides;d.executed!==w&&v(d)});return d.result};j.add("config-publishRequireResult",1,0,0);a.require=function(a,b){var d=function(a,b){var c=G(f(a),i.module);if(C.length&&C[0].finish)C[0].finish.push(a);else{if(c.executed)return c.result;
b&&(c.result=u);var d=F();S(c);d=F();c.executed!==w&&c.injected===s&&(q.holdIdle(),z(c),q.releaseIdle());if(c.executed)return c.result;d==t?c.cjs?Q.unshift(c):C.length&&(C[0].finish=[a]):Q.push(c)}}(a,b);j("config-publishRequireResult")&&!c.exists(a)&&d!==void 0&&c.setObject(a,d);return d};a.loadInit=function(a){a()};a.registerModulePath=function(a,b){var c={};c[a.replace(/\./g,"/")]=b;i({paths:c})};a.platformRequire=function(b){for(var b=(b.common||[]).concat(b[a._name]||b["default"]||[]),d;b.length;)c.isArray(d=
b.shift())?a.require.apply(a,d):a.require(d)};a.requireIf=a.requireAfterIf=function(b,c,d){b&&a.require(c,d)};a.requireLocalization=function(a,b,c){i(["../i18n"],function(d){d.getLocalization(a,b,c)})};return{extractLegacyApiApplications:k,require:q.dojoRequirePlugin,loadInit:function(c,d,e){d([c],function(c){d(c.names,function(){for(var g="",h=[],i=0;i<arguments.length;i++)g+="var "+c.names[i]+"= arguments["+i+"]; ",h.push(arguments[i]);eval(g);var j=d.module,k=[],g={},p=[],q,i={provide:function(a){a=
f(a);a=G(a,j);a!==j&&T(a)},require:function(a,b){a=f(a);b&&(G(a,j).result=u);p.push(a)},requireLocalization:function(b,c,d){k.length||(k=["dojo/i18n"]);d=(d||a.locale).toLowerCase();b=f(b)+"/nls/"+(/root/i.test(d)?"":d+"/")+f(c);G(b,j).isXd&&k.push("dojo/i18n!"+b)},loadInit:function(a){a()}};try{for(q in i)g[q]=a[q],a[q]=i[q];c.def.apply(null,h)}catch(r){O("error",[{src:n.id,id:"failedDojoLoadInit"},r])}finally{for(q in i)a[q]=g[q]}p.length&&k.push("dojo/require!"+p.join(","));b.push(e);o.forEach(p,
function(a){a=G(a,d.module);l.push(a);S(a)});m()})})}}})}}});(function(){var a=this.require;a({cache:{}});!a.async&&a(["dojo"]);a.boot&&a.apply(null,a.boot)})();