//>>built
define("dojo/fx",["./_base/lang","./Evented","./_base/kernel","./_base/array","./_base/connect","./_base/fx","./dom","./dom-style","./dom-geometry","./ready","require"],function(g,p,f,h,b,i,m,o,q,j,r){f.isAsync||j(0,function(){r(["./fx/Toggler"])});var f=f.fx={},j={_fire:function(a,c){this[a]&&this[a].apply(this,c||[]);return this}},k=function(a){this._index=-1;this._animations=a||[];this._current=this._onAnimateCtx=this._onEndCtx=null;this.duration=0;h.forEach(this._animations,function(a){this.duration+=
a.duration;a.delay&&(this.duration+=a.delay)},this)};k.prototype=new p;g.extend(k,{_onAnimate:function(){this._fire("onAnimate",arguments)},_onEnd:function(){b.disconnect(this._onAnimateCtx);b.disconnect(this._onEndCtx);this._onAnimateCtx=this._onEndCtx=null;this._index+1==this._animations.length?this._fire("onEnd"):(this._current=this._animations[++this._index],this._onAnimateCtx=b.connect(this._current,"onAnimate",this,"_onAnimate"),this._onEndCtx=b.connect(this._current,"onEnd",this,"_onEnd"),
this._current.play(0,!0))},play:function(a,c){if(!this._current)this._current=this._animations[this._index=0];if(!c&&this._current.status()=="playing")return this;var d=b.connect(this._current,"beforeBegin",this,function(){this._fire("beforeBegin")}),e=b.connect(this._current,"onBegin",this,function(){this._fire("onBegin",arguments)}),l=b.connect(this._current,"onPlay",this,function(){this._fire("onPlay",arguments);b.disconnect(d);b.disconnect(e);b.disconnect(l)});this._onAnimateCtx&&b.disconnect(this._onAnimateCtx);
this._onAnimateCtx=b.connect(this._current,"onAnimate",this,"_onAnimate");this._onEndCtx&&b.disconnect(this._onEndCtx);this._onEndCtx=b.connect(this._current,"onEnd",this,"_onEnd");this._current.play.apply(this._current,arguments);return this},pause:function(){if(this._current){var a=b.connect(this._current,"onPause",this,function(){this._fire("onPause",arguments);b.disconnect(a)});this._current.pause()}return this},gotoPercent:function(a,c){this.pause();var d=this.duration*a;this._current=null;h.some(this._animations,
function(a){if(a.duration<=d)return this._current=a,!0;d-=a.duration;return!1});this._current&&this._current.gotoPercent(d/this._current.duration,c);return this},stop:function(a){if(this._current){if(a){for(;this._index+1<this._animations.length;++this._index)this._animations[this._index].stop(!0);this._current=this._animations[this._index]}var c=b.connect(this._current,"onStop",this,function(){this._fire("onStop",arguments);b.disconnect(c)});this._current.stop()}return this},status:function(){return this._current?
this._current.status():"stopped"},destroy:function(){this._onAnimateCtx&&b.disconnect(this._onAnimateCtx);this._onEndCtx&&b.disconnect(this._onEndCtx)}});g.extend(k,j);f.chain=function(a){return new k(a)};var n=function(a){this._animations=a||[];this._connects=[];this.duration=this._finished=0;h.forEach(a,function(a){var c=a.duration;a.delay&&(c+=a.delay);if(this.duration<c)this.duration=c;this._connects.push(b.connect(a,"onEnd",this,"_onEnd"))},this);this._pseudoAnimation=new i.Animation({curve:[0,
1],duration:this.duration});var c=this;h.forEach(["beforeBegin","onBegin","onPlay","onAnimate","onPause","onStop","onEnd"],function(a){c._connects.push(b.connect(c._pseudoAnimation,a,function(){c._fire(a,arguments)}))})};g.extend(n,{_doAction:function(a,c){h.forEach(this._animations,function(d){d[a].apply(d,c)});return this},_onEnd:function(){++this._finished>this._animations.length&&this._fire("onEnd")},_call:function(a,c){var d=this._pseudoAnimation;d[a].apply(d,c)},play:function(){this._finished=
0;this._doAction("play",arguments);this._call("play",arguments);return this},pause:function(){this._doAction("pause",arguments);this._call("pause",arguments);return this},gotoPercent:function(a,c){var d=this.duration*a;h.forEach(this._animations,function(a){a.gotoPercent(a.duration<d?1:d/a.duration,c)});this._call("gotoPercent",arguments);return this},stop:function(){this._doAction("stop",arguments);this._call("stop",arguments);return this},status:function(){return this._pseudoAnimation.status()},
destroy:function(){h.forEach(this._connects,b.disconnect)}});g.extend(n,j);f.combine=function(a){return new n(a)};f.wipeIn=function(a){var c=a.node=m.byId(a.node),d=c.style,e,a=i.animateProperty(g.mixin({properties:{height:{start:function(){e=d.overflow;d.overflow="hidden";if(d.visibility=="hidden"||d.display=="none")return d.height="1px",d.display="",d.visibility="",1;else{var a=o.get(c,"height");return Math.max(a,1)}},end:function(){return c.scrollHeight}}}},a)),l=function(){d.height="auto";d.overflow=
e};b.connect(a,"onStop",l);b.connect(a,"onEnd",l);return a};f.wipeOut=function(a){var c=(a.node=m.byId(a.node)).style,d,a=i.animateProperty(g.mixin({properties:{height:{end:1}}},a));b.connect(a,"beforeBegin",function(){d=c.overflow;c.overflow="hidden";c.display=""});var e=function(){c.overflow=d;c.height="auto";c.display="none"};b.connect(a,"onStop",e);b.connect(a,"onEnd",e);return a};f.slideTo=function(a){var c=null,d=null,e=function(a){return function(){var b=o.getComputedStyle(a),e=b.position;
c=e=="absolute"?a.offsetTop:parseInt(b.top)||0;d=e=="absolute"?a.offsetLeft:parseInt(b.left)||0;if(e!="absolute"&&e!="relative")b=q.position(a,!0),c=b.y,d=b.x,a.style.position="absolute",a.style.top=c+"px",a.style.left=d+"px"}}(a.node=m.byId(a.node));e();a=i.animateProperty(g.mixin({properties:{top:a.top||0,left:a.left||0}},a));b.connect(a,"beforeBegin",a,e);return a};return f});