//>>built
define("dojo/on",["./has!dom-addeventlistener?:./aspect","./_base/kernel","./has"],function(q,r,e){function s(a,c,b,d,h){if(d=c.match(/(.*):(.*)/))return c=d[2],d=d[1],f.selector(d,c).call(h,a,b);e("touch")&&(t.test(c)&&(b=j(b)),!e("event-orientationchange")&&c=="orientationchange"&&(c="resize",a=window,b=j(b)));if(a.addEventListener){var g=c in i;a.addEventListener(g?i[c]:c,b,g);return{remove:function(){a.removeEventListener(c,b,g)}}}c="on"+c;if(k&&a.attachEvent)return k(a,c,b);throw Error("Target must be an event emitter");
}function u(){this.cancelable=!1}function v(){this.bubbles=!1}var l=window.ScriptEngineMajorVersion;e.add("jscript",l&&l()+ScriptEngineMinorVersion()/10);e.add("event-orientationchange",e("touch")&&!e("android"));var f=function(a,c,b,d){if(a.on)return a.on(c,b);return f.parse(a,c,b,s,d,this)};f.pausable=function(a,c,b,d){var h,a=f(a,c,function(){if(!h)return b.apply(this,arguments)},d);a.pause=function(){h=!0};a.resume=function(){h=!1};return a};f.once=function(a,c,b){var d=f(a,c,function(){d.remove();
return b.apply(this,arguments)});return d};f.parse=function(a,c,b,d,h,g){if(c.call)return c.call(g,a,b);if(c.indexOf(",")>-1){for(var c=c.split(/\s*,\s*/),f=[],e=0,m;m=c[e++];)f.push(d(a,m,b,h,g));f.remove=function(){for(var a=0;a<f.length;a++)f[a].remove()};return f}return d(a,c,b,h,g)};var t=/^touch/;f.selector=function(a,c,b){return function(d,h){function g(c){for(e=e&&e.matches?e:r.query;!e.matches(c,a,d);)if(c==d||b===!1||!(c=c.parentNode)||c.nodeType!=1)return;return c}var e=this,i=c.bubble;
if(i)return f(d,i(g),h);return f(d,c,function(a){var b=g(a.target);return b&&h.call(b,a)})}};var w=[].slice,x=f.emit=function(a,c,b){var d=w.call(arguments,2),f="on"+c;if("parentNode"in a){var g=d[0]={},e;for(e in b)g[e]=b[e];g.preventDefault=u;g.stopPropagation=v;g.target=a;g.type=c;b=g}do a[f]&&a[f].apply(a,d);while(b&&b.bubbles&&(a=a.parentNode));return b&&b.cancelable&&b},i={};if(e("dom-addeventlistener")){i={focusin:"focus",focusout:"blur"};if(e("opera"))i.keydown="keypress";f.emit=function(a,
c,b){if(a.dispatchEvent&&document.createEvent){var d=document.createEvent("HTMLEvents");d.initEvent(c,!!b.bubbles,!!b.cancelable);for(var e in b)e in d||(d[e]=b[e]);return a.dispatchEvent(d)&&d}return x.apply(f,arguments)}}else{f._fixEvent=function(a,c){if(!a)a=(c&&(c.ownerDocument||c.document||c).parentWindow||window).event;if(!a)return a;if(!a.target){a.target=a.srcElement;a.currentTarget=c||a.srcElement;if(a.type=="mouseover")a.relatedTarget=a.fromElement;if(a.type=="mouseout")a.relatedTarget=
a.toElement;if(!a.stopPropagation)a.stopPropagation=y,a.preventDefault=z;switch(a.type){case "keypress":var b="charCode"in a?a.charCode:a.keyCode;b==10?(b=0,a.keyCode=13):b==13||b==27?b=0:b==3&&(b=99);a.charCode=b;b=a;b.keyChar=b.charCode?String.fromCharCode(b.charCode):"";b.charOrCode=b.keyChar||b.keyCode}}return a};var n=function(a){this.handle=a};n.prototype.remove=function(){delete _dojoIEListeners_[this.handle]};var A=function(a){return function(c){c=f._fixEvent(c,this);return a.call(this,c)}},
k=function(a,c,b){b=A(b);if(((a.ownerDocument?a.ownerDocument.parentWindow:a.parentWindow||a.window||window)!=top||e("jscript")<5.8)&&!e("config-_allow_leaks")){typeof _dojoIEListeners_=="undefined"&&(_dojoIEListeners_=[]);var d=a[c];if(!d||!d.listeners){var f=d;a[c]=d=Function("event","var callee = arguments.callee; for(var i = 0; i<callee.listeners.length; i++){var listener = _dojoIEListeners_[callee.listeners[i]]; if(listener){listener.call(this,event);}}");d.listeners=[];d.global=this;f&&d.listeners.push(_dojoIEListeners_.push(f)-
1)}d.listeners.push(a=d.global._dojoIEListeners_.push(b)-1);return new n(a)}return q.after(a,c,b,!0)},y=function(){this.cancelBubble=!0},z=f._preventDefault=function(){this.bubbledKeyCode=this.keyCode;if(this.ctrlKey)try{this.keyCode=0}catch(a){}this.defaultPrevented=!0;this.returnValue=!1}}if(e("touch"))var o=function(){},p=window.orientation,j=function(a){return function(c){var b=c.corrected;if(!b){var d=c.type;try{delete c.type}catch(f){}c.type?(o.prototype=c,b=new o,b.preventDefault=function(){c.preventDefault()},
b.stopPropagation=function(){c.stopPropagation()}):(b=c,b.type=d);c.corrected=b;if(d=="resize"){if(p==window.orientation)return null;p=window.orientation;b.type="orientationchange";return a.call(this,b)}if(!("rotation"in b))b.rotation=0,b.scale=1;var d=b.changedTouches[0],e;for(e in d)delete b[e],b[e]=d[e]}return a.call(this,b)}};return f});