//>>built
define("dojo/parser",["./_base/kernel","./_base/lang","./_base/array","./_base/config","./_base/html","./_base/window","./_base/url","./_base/json","./aspect","./date/stamp","./query","./on","./ready"],function(q,r,t,y,z,v,J,C,D,F,G,H,A){var I={"dom-attributes-explicit":document.createElement("div").attributes.length<40};q.parser=new function(){function y(g){var e={},j;for(j in g)j.charAt(0)!="_"&&(e[j.toLowerCase()]=j);return e}var B={};D.after(r,"extend",function(){B={}},!0);var x={};this._functionFromScript=
function(g,e){var j="",f="",o=g.getAttribute(e+"args")||g.getAttribute("args");o&&t.forEach(o.split(/\s*,\s*/),function(e,f){j+="var "+e+" = arguments["+f+"]; "});(o=g.getAttribute("with"))&&o.length&&t.forEach(o.split(/\s*,\s*/),function(e){j+="with("+e+"){";f+="}"});return new Function(j+g.innerHTML+f)};this.instantiate=function(g,e,j){var f=[],e=e||{},j=j||{},o=(j.scope||q._scopeName)+"Type",m="data-"+(j.scope||q._scopeName)+"-",E=m+"type",w={};t.forEach([m+"props",E,o,m+"id","jsId",m+"attach-point",
m+"attach-event","dojoAttachPoint","dojoAttachEvent","class","style"],function(a){w[a.toLowerCase()]=a.replace(j.scope,"dojo")});t.forEach(g,function(a){var K;if(a){var c=a.node||a,l=o in e?e[o]:a.node?a.type:c.getAttribute(E)||c.getAttribute(o),h=x[l]||(x[l]=r.getObject(l)),n=h&&h.prototype;if(!h)throw Error("Could not load class '"+l+"'");var i={};j.defaults&&r.mixin(i,j.defaults);a.inherited&&r.mixin(i,a.inherited);var u;if(I["dom-attributes-explicit"])u=c.attributes;else{var b=(/^input$|^img$/i.test(c.nodeName)?
c:c.cloneNode(!1)).outerHTML.replace(/=[^\s"']+|="[^"]*"|='[^']*'/g,"").replace(/^\s*<[a-zA-Z0-9]*\s*/,"").replace(/\s*>.*$/,"");u=t.map(b.split(/\s+/),function(a){var b=a.toLowerCase();return{name:a,value:c.nodeName=="LI"&&a=="value"||b=="enctype"?c.getAttribute(b):c.getAttributeNode(b).value,specified:!0}})}for(var b=0,d;d=u[b++];)if(d&&d.specified){var k=d.name,g=k.toLowerCase();d=d.value;if(g in w)switch(w[g]){case "data-dojo-props":var s=d;break;case "data-dojo-id":case "jsId":var v=d;break;
case "data-dojo-attach-point":case "dojoAttachPoint":i.dojoAttachPoint=d;break;case "data-dojo-attach-event":case "dojoAttachEvent":i.dojoAttachEvent=d;break;case "class":i["class"]=c.className;break;case "style":i.style=c.style&&c.style.cssText}else if(k in n||(k=(B[l]||(B[l]=y(n)))[g]||k),k in n)switch(typeof n[k]){case "string":i[k]=d;break;case "number":i[k]=d.length?Number(d):NaN;break;case "boolean":i[k]=d.toLowerCase()!="false";break;case "function":i[k]=d===""||d.search(/[^\w\.]+/i)!=-1?new Function(d):
r.getObject(d,!1)||new Function(d);break;default:g=n[k],i[k]=g&&"length"in g?d?d.split(/\s*,\s*/):[]:g instanceof Date?d==""?new Date(""):d=="now"?new Date:F.fromISOString(d):g instanceof q._Url?q.baseUrl+d:C.fromJson(d)}else i[k]=d}if(s)try{s=C.fromJson.call(j.propsThis,"{"+s+"}"),r.mixin(i,s)}catch(z){throw Error(z.toString()+" in data-dojo-props='"+s+"'");}r.mixin(i,e);g=a.node?a.scripts:h&&(h._noScript||n._noScript)?[]:G("> script[type^='dojo/']",c);a=[];s=[];u=[];k=[];if(g)for(b=0;b<g.length;b++){var p=
g[b];c.removeChild(p);d=p.getAttribute(m+"event")||p.getAttribute("event");var A=p.getAttribute(m+"prop"),l=p.getAttribute("type"),p=this._functionFromScript(p,m);d?l=="dojo/connect"?a.push({event:d,func:p}):l=="dojo/on"?k.push({event:d,func:p}):i[d]=p:l=="dojo/watch"?u.push({prop:A,func:p}):s.push(p)}K=(l=h.markupFactory||n.markupFactory)?l(i,c,h):new h(i,c),h=K;f.push(h);v&&r.setObject(v,h);for(b=0;b<a.length;b++)D.after(h,a[b].event,q.hitch(h,a[b].func),!0);for(b=0;b<s.length;b++)s[b].call(h);
for(b=0;b<u.length;b++)h.watch(u[b].prop,u[b].func);for(b=0;b<k.length;b++)H(h,k[b].event,k[b].func)}},this);e._started||t.forEach(f,function(a){!j.noStart&&a&&r.isFunction(a.startup)&&!a._started&&a.startup()});return f};this.parse=function(g,e){function j(a){if(!a.inherited){a.inherited={};var b=a.node,d=j(a.parent),b={dir:b.getAttribute("dir")||d.dir,lang:b.getAttribute("lang")||d.lang,textDir:b.getAttribute(w)||d.textDir},c;for(c in b)b[c]&&(a.inherited[c]=b[c])}return a.inherited}var f;!e&&g&&
g.rootNode?(e=g,f=e.rootNode):f=g;f=f?z.byId(f):v.body();var e=e||{},o=(e.scope||q._scopeName)+"Type",m="data-"+(e.scope||q._scopeName)+"-",t=m+"type",w=m+"textdir",m=[],a=f.firstChild,c=e&&e.inherited;if(!c){var l=function(a,b){return a.getAttribute&&a.getAttribute(b)||(a!==v.doc&&a!==v.doc.documentElement&&a.parentNode?l(a.parentNode,b):null)},c={dir:l(f,"dir"),lang:l(f,"lang"),textDir:l(f,w)},h;for(h in c)c[h]||delete c[h]}for(var c={inherited:c},n,i;;)if(a)a.nodeType!=1?a=a.nextSibling:n&&a.nodeName.toLowerCase()==
"script"?((f=a.getAttribute("type"))&&/^dojo\/\w/i.test(f)&&n.push(a),a=a.nextSibling):i?a=a.nextSibling:(f=a.getAttribute(t)||a.getAttribute(o),h=a.firstChild,!f&&(!h||h.nodeType==3&&!h.nextSibling)?a=a.nextSibling:(c={node:a,scripts:n,parent:c},n=(i=f&&(x[f]||(x[f]=r.getObject(f))))&&!i.prototype._noScript?[]:null,f&&m.push({type:f,node:a,scripts:n,inherited:j(c)}),a=h,i=i&&i.prototype.stopParser&&!(e&&e.template)));else{if(!c||!c.node)break;a=c.node.nextSibling;n=c.scripts;i=!1;c=c.parent}return this.instantiate(m,
e&&e.template?{template:!0}:null,e)}};y.parseOnLoad&&A(100,q.parser,"parse");return q.parser});