//>>built
define("dijit/layout/BorderContainer",["dojo/_base/array","dojo/cookie","dojo/_base/declare","dojo/dom-class","dojo/dom-construct","dojo/dom-geometry","dojo/dom-style","dojo/_base/event","dojo/keys","dojo/_base/lang","dojo/on","dojo/touch","dojo/_base/window","../_WidgetBase","../_Widget","../_TemplatedMixin","./_LayoutWidget","./utils"],function(e,k,f,d,g,h,i,m,j,l,n,s,r,u,o,p,v,w){var q=f("dijit.layout._Splitter",[o,p],{live:!0,templateString:'<div class="dijitSplitter" data-dojo-attach-event="onkeypress:_onKeyPress,press:_startDrag,onmouseenter:_onMouse,onmouseleave:_onMouse" tabIndex="0" role="separator"><div class="dijitSplitterThumb"></div></div>',
constructor:function(){this._handlers=[]},postMixInProperties:function(){this.inherited(arguments);this.horizontal=/top|bottom/.test(this.region);this._factor=/top|left/.test(this.region)?1:-1;this._cookieName=this.container.id+"_"+this.region},buildRendering:function(){this.inherited(arguments);d.add(this.domNode,"dijitSplitter"+(this.horizontal?"H":"V"));if(this.container.persist){var a=k(this._cookieName);a&&(this.child.domNode.style[this.horizontal?"height":"width"]=a)}},_computeMaxSize:function(){var a=
this.horizontal?"h":"w",c=h.getMarginBox(this.child.domNode)[a],b=e.filter(this.container.getChildren(),function(a){return a.region=="center"})[0],a=h.getMarginBox(b.domNode)[a];return Math.min(this.child.maxSize,c+a)},_startDrag:function(a){if(!this.cover)this.cover=r.doc.createElement("div"),d.add(this.cover,"dijitSplitterCover"),g.place(this.cover,this.child.domNode,"after");d.add(this.cover,"dijitSplitterCoverActive");this.fake&&g.destroy(this.fake);if(!(this._resize=this.live))(this.fake=this.domNode.cloneNode(!0)).removeAttribute("id"),
d.add(this.domNode,"dijitSplitterShadow"),g.place(this.fake,this.domNode,"after");d.add(this.domNode,"dijitSplitterActive dijitSplitter"+(this.horizontal?"H":"V")+"Active");this.fake&&d.remove(this.fake,"dijitSplitterHover dijitSplitter"+(this.horizontal?"H":"V")+"Hover");var c=this._factor,b=this.horizontal,e=b?"pageY":"pageX",x=a[e],f=this.domNode.style,i=h.getMarginBox(this.child.domNode)[b?"h":"w"],j=this._computeMaxSize(),y=this.child.minSize||20,b=this.region,k=b=="top"||b=="bottom"?"top":"left",
o=parseInt(f[k],10),p=this._resize,q=l.hitch(this.container,"_layoutChildren",this.child.id),b=r.doc;this._handlers=this._handlers.concat([n(b,s.move,this._drag=function(a,b){var d=a[e]-x,g=c*d+i,h=Math.max(Math.min(g,j),y);(p||b)&&q(h);f[k]=d+o+c*(h-g)+"px"}),n(b,"dragstart",m.stop),n(r.body(),"selectstart",m.stop),n(b,s.release,l.hitch(this,"_stopDrag"))]);m.stop(a)},_onMouse:function(a){a=a.type=="mouseover"||a.type=="mouseenter";d.toggle(this.domNode,"dijitSplitterHover",a);d.toggle(this.domNode,
"dijitSplitter"+(this.horizontal?"H":"V")+"Hover",a)},_stopDrag:function(a){try{this.cover&&d.remove(this.cover,"dijitSplitterCoverActive"),this.fake&&g.destroy(this.fake),d.remove(this.domNode,"dijitSplitterActive dijitSplitter"+(this.horizontal?"H":"V")+"Active dijitSplitterShadow"),this._drag(a),this._drag(a,!0)}finally{this._cleanupHandlers(),delete this._drag}this.container.persist&&k(this._cookieName,this.child.domNode.style[this.horizontal?"height":"width"],{expires:365})},_cleanupHandlers:function(){for(var a;a=
this._handlers.pop();)a.remove()},_onKeyPress:function(a){this._resize=!0;var c=this.horizontal,b=1;switch(a.charOrCode){case c?j.UP_ARROW:j.LEFT_ARROW:b*=-1;case c?j.DOWN_ARROW:j.RIGHT_ARROW:break;default:return}c=h.getMarginSize(this.child.domNode)[c?"h":"w"]+this._factor*b;this.container._layoutChildren(this.child.id,Math.max(Math.min(c,this._computeMaxSize()),this.child.minSize));m.stop(a)},destroy:function(){this._cleanupHandlers();delete this.child;delete this.container;delete this.cover;delete this.fake;
this.inherited(arguments)}}),t=f("dijit.layout._Gutter",[o,p],{templateString:'<div class="dijitGutter" role="presentation"></div>',postMixInProperties:function(){this.inherited(arguments);this.horizontal=/top|bottom/.test(this.region)},buildRendering:function(){this.inherited(arguments);d.add(this.domNode,"dijitGutter"+(this.horizontal?"H":"V"))}}),f=f("dijit.layout.BorderContainer",v,{design:"headline",gutters:!0,liveSplitters:!0,persist:!1,baseClass:"dijitBorderContainer",_splitterClass:q,postMixInProperties:function(){this.gutters||
(this.baseClass+="NoGutter");this.inherited(arguments)},startup:function(){this._started||(e.forEach(this.getChildren(),this._setupChild,this),this.inherited(arguments))},_setupChild:function(a){var c=a.region;if(c){this.inherited(arguments);d.add(a.domNode,this.baseClass+"Pane");var b=this.isLeftToRight();c=="leading"&&(c=b?"left":"right");c=="trailing"&&(c=b?"right":"left");if(c!="center"&&(a.splitter||this.gutters)&&!a._splitterWidget)b=a.splitter?this._splitterClass:t,l.isString(b)&&(b=l.getObject(b)),
b=new b({id:a.id+"_splitter",container:this,child:a,region:c,live:this.liveSplitters}),b.isSplitter=!0,a._splitterWidget=b,g.place(b.domNode,a.domNode,"after"),b.startup();a.region=c}},layout:function(){this._layoutChildren()},addChild:function(){this.inherited(arguments);this._started&&this.layout()},removeChild:function(a){var c=a.region,b=a._splitterWidget;b&&(b.destroy(),delete a._splitterWidget);this.inherited(arguments);this._started&&this._layoutChildren();d.remove(a.domNode,this.baseClass+
"Pane");i.set(a.domNode,{top:"auto",bottom:"auto",left:"auto",right:"auto",position:"static"});i.set(a.domNode,c=="top"||c=="bottom"?"width":"height","auto")},getChildren:function(){return e.filter(this.inherited(arguments),function(a){return!a.isSplitter})},getSplitter:function(a){return e.filter(this.getChildren(),function(c){return c.region==a})[0]._splitterWidget},resize:function(){if(!this.cs||!this.pe){var a=this.domNode;this.cs=i.getComputedStyle(a);this.pe=h.getPadExtents(a,this.cs);this.pe.r=
i.toPixelValue(a,this.cs.paddingRight);this.pe.b=i.toPixelValue(a,this.cs.paddingBottom);i.set(a,"padding","0px")}this.inherited(arguments)},_layoutChildren:function(a,c){if(this._borderBox&&this._borderBox.h){var b=e.map(this.getChildren(),function(a,b){return{pane:a,weight:[a.region=="center"?Infinity:0,a.layoutPriority,(this.design=="sidebar"?1:-1)*(/top|bottom/.test(a.region)?1:-1),b]}},this);b.sort(function(a,b){for(var c=a.weight,d=b.weight,e=0;e<c.length;e++)if(c[e]!=d[e])return c[e]-d[e];
return 0});var d=[];e.forEach(b,function(a){a=a.pane;d.push(a);a._splitterWidget&&d.push(a._splitterWidget)});w.layoutChildren(this.domNode,{l:this.pe.l,t:this.pe.t,w:this._borderBox.w-this.pe.w,h:this._borderBox.h-this.pe.h},d,a,c)}},destroyRecursive:function(){e.forEach(this.getChildren(),function(a){var c=a._splitterWidget;c&&c.destroy();delete a._splitterWidget});this.inherited(arguments)}});l.extend(u,{region:"",layoutPriority:0,splitter:!1,minSize:0,maxSize:Infinity});f._Splitter=q;f._Gutter=
t;return f});