//>>built
define("dijit/layout/SplitContainer",["dojo/_base/array","dojo/cookie","dojo/_base/declare","dojo/dom","dojo/dom-class","dojo/dom-construct","dojo/dom-geometry","dojo/dom-style","dojo/_base/event","dojo/_base/kernel","dojo/_base/lang","dojo/on","dojo/_base/sniff","dojo/_base/window","../registry","../_WidgetBase","./_LayoutWidget"],function(d,i,o,j,p,k,e,q,l,r,h,m,s,g,t,u,v){h.extend(u,{sizeMin:10,sizeShare:10});return o("dijit.layout.SplitContainer",v,{constructor:function(){r.deprecated("dijit.layout.SplitContainer is deprecated",
"use BorderContainer with splitter instead",2)},activeSizing:!1,sizerWidth:7,orientation:"horizontal",persist:!0,baseClass:"dijitSplitContainer",postMixInProperties:function(){this.inherited("postMixInProperties",arguments);this.isHorizontal=this.orientation=="horizontal"},postCreate:function(){this.inherited(arguments);this.sizers=[];if(s("mozilla"))this.domNode.style.overflow="-moz-scrollbars-none";if(typeof this.sizerWidth=="object")try{this.sizerWidth=parseInt(this.sizerWidth.toString())}catch(a){this.sizerWidth=
7}var b=g.doc.createElement("div");this.virtualSizer=b;b.style.position="relative";b.style.zIndex=10;b.className=this.isHorizontal?"dijitSplitContainerVirtualSizerH":"dijitSplitContainerVirtualSizerV";this.domNode.appendChild(b);j.setSelectable(b,!1)},destroy:function(){delete this.virtualSizer;if(this._ownconnects)for(var a;a=this._ownconnects.pop();)a.remove();this.inherited(arguments)},startup:function(){this._started||(d.forEach(this.getChildren(),function(a,b,c){this._setupChild(a);b<c.length-
1&&this._addSizer()},this),this.persist&&this._restoreState(),this.inherited(arguments))},_setupChild:function(a){this.inherited(arguments);a.domNode.style.position="absolute";p.add(a.domNode,"dijitSplitPane")},_onSizerMouseDown:function(a){if(a.target.id){for(var b=0;b<this.sizers.length;b++)if(this.sizers[b].id==a.target.id)break;b<this.sizers.length&&this.beginSizing(a,b)}},_addSizer:function(a){var a=a===void 0?this.sizers.length:a,b=g.doc.createElement("div");b.id=t.getUniqueId("dijit_layout_SplitterContainer_Splitter");
this.sizers.splice(a,0,b);this.domNode.appendChild(b);b.className=this.isHorizontal?"dijitSplitContainerSizerH":"dijitSplitContainerSizerV";a=g.doc.createElement("div");a.className="thumb";b.appendChild(a);this.connect(b,"onmousedown","_onSizerMouseDown");j.setSelectable(b,!1)},removeChild:function(a){if(this.sizers.length){var b=d.indexOf(this.getChildren(),a);b!=-1&&(b==this.sizers.length&&b--,k.destroy(this.sizers[b]),this.sizers.splice(b,1))}this.inherited(arguments);this._started&&this.layout()},
addChild:function(a,b){this.inherited(arguments);this._started&&(this.getChildren().length>1&&this._addSizer(b),this.layout())},layout:function(){this.paneWidth=this._contentBox.w;this.paneHeight=this._contentBox.h;var a=this.getChildren();if(a.length){var b=this.isHorizontal?this.paneWidth:this.paneHeight;a.length>1&&(b-=this.sizerWidth*(a.length-1));var c=0;d.forEach(a,function(a){c+=a.sizeShare});var w=b/c,n=0;d.forEach(a.slice(0,a.length-1),function(a){var b=Math.round(w*a.sizeShare);a.sizeActual=
b;n+=b});a[a.length-1].sizeActual=b-n;this._checkSizes();var f=0,e=a[0].sizeActual;this._movePanel(a[0],f,e);a[0].position=f;f+=e;this.sizers&&d.some(a.slice(1),function(a,b){if(!this.sizers[b])return!0;this._moveSlider(this.sizers[b],f,this.sizerWidth);this.sizers[b].position=f;f+=this.sizerWidth;e=a.sizeActual;this._movePanel(a,f,e);a.position=f;f+=e},this)}},_movePanel:function(a,b,c){this.isHorizontal?(a.domNode.style.left=b+"px",a.domNode.style.top=0,b={w:c,h:this.paneHeight}):(a.domNode.style.left=
0,a.domNode.style.top=b+"px",b={w:this.paneWidth,h:c});a.resize?a.resize(b):e.setMarginBox(a.domNode,b)},_moveSlider:function(a,b,c){this.isHorizontal?(a.style.left=b+"px",a.style.top=0,e.setMarginBox(a,{w:c,h:this.paneHeight})):(a.style.left=0,a.style.top=b+"px",e.setMarginBox(a,{w:this.paneWidth,h:c}))},_growPane:function(a,b){if(a>0&&b.sizeActual>b.sizeMin)b.sizeActual-b.sizeMin>a?(b.sizeActual-=a,a=0):(a-=b.sizeActual-b.sizeMin,b.sizeActual=b.sizeMin);return a},_checkSizes:function(){var a=0,
b=0,c=this.getChildren();d.forEach(c,function(c){b+=c.sizeActual;a+=c.sizeMin});if(a<=b){var e=0;d.forEach(c,function(a){if(a.sizeActual<a.sizeMin)e+=a.sizeMin-a.sizeActual,a.sizeActual=a.sizeMin});e>0&&(c=this.isDraggingLeft?c.reverse():c,d.forEach(c,function(a){e=this._growPane(e,a)},this))}else d.forEach(c,function(c){c.sizeActual=Math.round(b*(c.sizeMin/a))})},beginSizing:function(a,b){var c=this.getChildren();this.paneBefore=c[b];this.paneAfter=c[b+1];this.isSizing=!0;this.sizingSplitter=this.sizers[b];
this.cover?this.cover.style.zIndex=5:this.cover=k.create("div",{style:{position:"absolute",zIndex:5,top:0,left:0,width:"100%",height:"100%"}},this.domNode);this.sizingSplitter.style.zIndex=6;this.originPos=e.position(c[0].domNode,!0);var d;this.isHorizontal?(c=a.layerX||a.offsetX||0,d=a.pageX,this.originPos=this.originPos.x):(c=a.layerY||a.offsetY||0,d=a.pageY,this.originPos=this.originPos.y);this.startPoint=this.lastPoint=d;this.screenToClientOffset=d-c;this.dragOffset=this.lastPoint-this.paneBefore.sizeActual-
this.originPos-this.paneBefore.position;this.activeSizing||this._showSizingLine();this._ownconnects=[m(g.doc.documentElement,"mousemove",h.hitch(this,"changeSizing")),m(g.doc.documentElement,"mouseup",h.hitch(this,"endSizing"))];l.stop(a)},changeSizing:function(a){if(this.isSizing)this.lastPoint=this.isHorizontal?a.pageX:a.pageY,this.movePoint(),this.activeSizing?this._updateSize():this._moveSizingLine(),l.stop(a)},endSizing:function(){if(this.isSizing){if(this.cover)this.cover.style.zIndex=-1;this.activeSizing||
this._hideSizingLine();this._updateSize();this.isSizing=!1;this.persist&&this._saveState(this);for(var a;a=this._ownconnects.pop();)a.remove()}},movePoint:function(){var a=this.lastPoint-this.screenToClientOffset;a-=this.dragOffset;a=this.legaliseSplitPoint(a);a+=this.dragOffset;this.lastPoint=a+this.screenToClientOffset},legaliseSplitPoint:function(a){a+=this.sizingSplitter.position;this.isDraggingLeft=!!(a>0);if(!this.activeSizing){var b=this.paneBefore.position+this.paneBefore.sizeMin;a<b&&(a=
b);b=this.paneAfter.position+(this.paneAfter.sizeActual-(this.sizerWidth+this.paneAfter.sizeMin));a>b&&(a=b)}a-=this.sizingSplitter.position;this._checkSizes();return a},_updateSize:function(){var a=this.lastPoint-this.dragOffset-this.originPos,b=this.paneAfter.position+this.paneAfter.sizeActual;this.paneBefore.sizeActual=a-this.paneBefore.position;this.paneAfter.position=a+this.sizerWidth;this.paneAfter.sizeActual=b-this.paneAfter.position;d.forEach(this.getChildren(),function(a){a.sizeShare=a.sizeActual});
this._started&&this.layout()},_showSizingLine:function(){this._moveSizingLine();e.setMarginBox(this.virtualSizer,this.isHorizontal?{w:this.sizerWidth,h:this.paneHeight}:{w:this.paneWidth,h:this.sizerWidth});this.virtualSizer.style.display="block"},_hideSizingLine:function(){this.virtualSizer.style.display="none"},_moveSizingLine:function(){q.set(this.virtualSizer,this.isHorizontal?"left":"top",this.lastPoint-this.startPoint+this.sizingSplitter.position+"px")},_getCookieName:function(a){return this.id+
"_"+a},_restoreState:function(){d.forEach(this.getChildren(),function(a,b){var c=this._getCookieName(b);if(c=i(c))if(c=parseInt(c),typeof c=="number")a.sizeShare=c},this)},_saveState:function(){this.persist&&d.forEach(this.getChildren(),function(a,b){i(this._getCookieName(b),a.sizeShare,{expires:365})},this)}})});