//>>built
define("dojo/selector/acme",["../_base/kernel","../dom","../_base/sniff","../_base/array","../_base/lang","../_base/window"],function(q,I,g,J,X,w){var K=X.trim,F=J.forEach,L=(g("webkit")||g("mozilla"))&&w.doc.compatMode=="BackCompat",r=!1,x=function(){return!0},G=function(a){a+=">~+".indexOf(a.slice(-1))>=0?" * ":" ";for(var b=function(b,c){return K(a.slice(b,c))},c=[],d=-1,f=-1,e=-1,k=-1,p=-1,l=-1,y=-1,z="",m="",g,i=0,o=a.length,h=null,n=null,j=function(){if(l>=0)h.id=b(l,i).replace(/\\/g,""),l=
-1;if(y>=0){var a=y==i?null:b(y,i);h[">~+".indexOf(a)<0?"tag":"oper"]=a;y=-1}p>=0&&(h.classes.push(b(p+1,i).replace(/\\/g,"")),p=-1)};z=m,m=a.charAt(i),i<o;i++)if(z!="\\")if(h||(g=i,h={query:null,pseudos:[],attrs:[],classes:[],tag:null,oper:null,id:null,getTag:function(){return r?this.otag:this.tag}},y=i),d>=0)if(m=="]"){n.attr?n.matchFor=b(e||d+1,i):n.attr=b(d+1,i);if((d=n.matchFor)&&(d.charAt(0)=='"'||d.charAt(0)=="'"))n.matchFor=d.slice(1,-1);h.attrs.push(n);n=null;d=e=-1}else{if(m=="=")e="|~^$*".indexOf(z)>=
0?z:"",n.type=e+m,n.attr=b(d+1,i-e.length),e=i+1}else if(f>=0){if(m==")"){if(k>=0)n.value=b(f+1,i);k=f=-1}}else if(m=="#")j(),l=i+1;else if(m==".")j(),p=i;else if(m==":")j(),k=i;else if(m=="[")j(),d=i,n={};else if(m=="(")k>=0&&(n={name:b(k+1,i),value:null},h.pseudos.push(n)),f=i;else if(m==" "&&z!=m){j();k>=0&&h.pseudos.push({name:b(k+1,i)});h.loops=h.pseudos.length||h.attrs.length||h.classes.length;h.oquery=h.query=b(g,i);h.otag=h.tag=h.oper?null:h.tag||"*";if(h.tag)h.tag=h.tag.toUpperCase();if(c.length&&
c[c.length-1].oper)h.infixOper=c.pop(),h.query=h.infixOper.query+" "+h.query;c.push(h);h=null}return c},s=function(a,b){if(!a)return b;if(!b)return a;return function(){return a.apply(window,arguments)&&b.apply(window,arguments)}},t=function(a,b){var c=b||[];a&&c.push(a);return c},C=function(a){return 1==a.nodeType},u=function(a,b){if(!a)return"";if(b=="class")return a.className||"";if(b=="for")return a.htmlFor||"";if(b=="style")return a.style.cssText||"";return(r?a.getAttribute(b):a.getAttribute(b,
2))||""},M={"*=":function(a,b){return function(c){return u(c,a).indexOf(b)>=0}},"^=":function(a,b){return function(c){return u(c,a).indexOf(b)==0}},"$=":function(a,b){return function(c){c=" "+u(c,a);return c.lastIndexOf(b)==c.length-b.length}},"~=":function(a,b){var c=" "+b+" ";return function(b){return(" "+u(b,a)+" ").indexOf(c)>=0}},"|=":function(a,b){var c=b+"-";return function(d){d=u(d,a);return d==b||d.indexOf(c)==0}},"=":function(a,b){return function(c){return u(c,a)==b}}},D=typeof w.doc.firstChild.nextElementSibling==
"undefined",A=!D?"nextElementSibling":"nextSibling",Y=!D?"previousElementSibling":"previousSibling",B=D?C:x,N=function(a){for(;a=a[Y];)if(B(a))return!1;return!0},O=function(a){for(;a=a[A];)if(B(a))return!1;return!0},E=function(a){var b=a.parentNode,c=0,d=b.children||b.childNodes,f=a._i||-1,e=b._l||-1;if(!d)return-1;d=d.length;if(e==d&&f>=0&&e>=0)return f;b._l=d;f=-1;for(b=b.firstElementChild||b.firstChild;b;b=b[A])if(B(b))b._i=++c,a===b&&(f=c);return f},Z=function(a){return!(E(a)%2)},$=function(a){return E(a)%
2},P={checked:function(){return function(a){return!!("checked"in a?a.checked:a.selected)}},"first-child":function(){return N},"last-child":function(){return O},"only-child":function(){return function(a){return N(a)&&O(a)}},empty:function(){return function(a){for(var b=a.childNodes,a=a.childNodes.length-1;a>=0;a--){var c=b[a].nodeType;if(c===1||c==3)return!1}return!0}},contains:function(a,b){var c=b.charAt(0);if(c=='"'||c=="'")b=b.slice(1,-1);return function(a){return a.innerHTML.indexOf(b)>=0}},not:function(a,
b){var c=G(b)[0],d={el:1};if(c.tag!="*")d.tag=1;if(!c.classes.length)d.classes=1;var f=j(c,d);return function(a){return!f(a)}},"nth-child":function(a,b){var c=parseInt;if(b=="odd")return $;else if(b=="even")return Z;if(b.indexOf("n")!=-1){var d=b.split("n",2),f=d[0]?d[0]=="-"?-1:c(d[0]):1,e=d[1]?c(d[1]):0,k=0,p=-1;f>0?e<0?e=e%f&&f+e%f:e>0&&(e>=f&&(k=e-e%f),e%=f):f<0&&(f*=-1,e>0&&(p=e,e%=f));if(f>0)return function(a){a=E(a);return a>=k&&(p<0||a<=p)&&a%f==e};else b=e}var l=c(b);return function(a){return E(a)==
l}}},aa=g("ie")&&(g("ie")<9||q.isQuirks)?function(a){var b=a.toLowerCase();b=="class"&&(a="className");return function(c){return r?c.getAttribute(a):c[a]||c[b]}}:function(a){return function(b){return b&&b.getAttribute&&b.hasAttribute(a)}},j=function(a,b){if(!a)return x;var b=b||{},c=null;"el"in b||(c=s(c,C));"tag"in b||a.tag!="*"&&(c=s(c,function(b){return b&&b.tagName==a.getTag()}));"classes"in b||F(a.classes,function(a,b){var e=RegExp("(?:^|\\s)"+a+"(?:\\s|$)");c=s(c,function(a){return e.test(a.className)});
c.count=b});"pseudos"in b||F(a.pseudos,function(a){var b=a.name;P[b]&&(c=s(c,P[b](b,a.value)))});"attrs"in b||F(a.attrs,function(a){var b,e=a.attr;a.type&&M[a.type]?b=M[a.type](e,a.matchFor):e.length&&(b=aa(e));b&&(c=s(c,b))});"id"in b||a.id&&(c=s(c,function(b){return!!b&&b.id==a.id}));c||"default"in b||(c=x);return c},ba=function(a){return function(b,c,d){for(;b=b[A];)if(!D||C(b)){(!d||v(b,d))&&a(b)&&c.push(b);break}return c}},ca=function(a){return function(b,c,d){for(b=b[A];b;){if(B(b)){if(d&&!v(b,
d))break;a(b)&&c.push(b)}b=b[A]}return c}},da=function(a){a=a||x;return function(b,c,d){for(var f=0,e=b.children||b.childNodes;b=e[f++];)B(b)&&(!d||v(b,d))&&a(b,f)&&c.push(b);return c}},Q={},R=function(a){var b=Q[a.query];if(b)return b;var c=a.infixOper,c=c?c.oper:"",d=j(a,{el:1}),f="*"==a.tag,e=w.doc.getElementsByClassName;if(c){e={el:1};if(f)e.tag=1;d=j(a,e);"+"==c?b=ba(d):"~"==c?b=ca(d):">"==c&&(b=da(d))}else if(a.id)d=!a.loops&&f?x:j(a,{el:1,id:1}),b=function(b,c){var e=I.byId(a.id,b.ownerDocument||
b);if(e&&d(e))if(9==b.nodeType)return t(e,c);else{for(var f=e.parentNode;f;){if(f==b)break;f=f.parentNode}if(f)return t(e,c)}};else if(e&&/\{\s*\[native code\]\s*\}/.test(String(e))&&a.classes.length&&!L)var d=j(a,{el:1,classes:1,id:1}),k=a.classes.join(" "),b=function(a,b,c){for(var b=t(0,b),e,f=0,g=a.getElementsByClassName(k);e=g[f++];)d(e,a)&&v(e,c)&&b.push(e);return b};else!f&&!a.loops?b=function(b,c,d){for(var c=t(0,c),e=0,f=b.getElementsByTagName(a.getTag());b=f[e++];)v(b,d)&&c.push(b);return c}:
(d=j(a,{el:1,tag:1,id:1}),b=function(b,c,e){for(var c=t(0,c),f,k=0,g=b.getElementsByTagName(a.getTag());f=g[k++];)d(f,b)&&v(f,e)&&c.push(f);return c});return Q[a.query]=b},S={},T={},U=function(a){var b=G(K(a));if(b.length==1){var c=R(b[0]);return function(a){if(a=c(a,[]))a.nozip=!0;return a}}return function(a){for(var a=t(a),c,e,k=b.length,g,l,j=0;j<k;j++){l=[];c=b[j];e=a.length-1;if(e>0)g={},l.nozip=!0;e=R(c);for(var o=0;c=a[o];o++)e(c,l,g);if(!l.length)break;a=l}return l}},q=navigator.userAgent,
q=g("webkit")&&q.indexOf("WebKit/")>0&&parseFloat(q.split("WebKit/")[1])>528,ea=g("ie")?"commentStrip":"nozip",V=!!w.doc.querySelectorAll&&(!g("safari")||g("safari")>3.1||q),fa=/n\+\d|([^ ])?([>~+])([^ =])?/g,ga=function(a,b,c,d){return c?(b?b+" ":"")+c+(d?" "+d:""):a},W=function(a,b){a=a.replace(fa,ga);if(V){var c=T[a];if(c&&!b)return c}if(c=S[a])return c;var c=a.charAt(0),d=-1==a.indexOf(" ");a.indexOf("#")>=0&&d&&(b=!0);if(V&&!b&&">~+".indexOf(c)==-1&&(!g("ie")||a.indexOf(":")==-1)&&!(L&&a.indexOf(".")>=
0)&&a.indexOf(":contains")==-1&&a.indexOf(":checked")==-1&&a.indexOf("|=")==-1){var f=">~+".indexOf(a.charAt(a.length-1))>=0?a+" *":a;return T[a]=function(b){try{if(!(9==b.nodeType||d))throw"";var c=b.querySelectorAll(f);c[ea]=!0;return c}catch(e){return W(a,!0)(b)}}}else{var e=a.split(/\s*,\s*/);return S[a]=e.length<2?U(a):function(a){for(var b=0,c=[],d;d=e[b++];)c=c.concat(U(d)(a));return c}}},o=0,ha=g("ie")?function(a){return r?a.getAttribute("_uid")||a.setAttribute("_uid",++o)||o:a.uniqueID}:
function(a){return a._uid||(a._uid=++o)},v=function(a,b){if(!b)return 1;var c=ha(a);if(!b[c])return b[c]=1;return 0},ia=function(a){if(a&&a.nozip)return a;var b=[];if(!a||!a.length)return b;a[0]&&b.push(a[0]);if(a.length<2)return b;o++;var c,d;if(g("ie")&&r){var f=o+"";a[0].setAttribute("_zipIdx",f);for(c=1;d=a[c];c++)a[c].getAttribute("_zipIdx")!=f&&b.push(d),d.setAttribute("_zipIdx",f)}else if(g("ie")&&a.commentStrip)try{for(c=1;d=a[c];c++)C(d)&&b.push(d)}catch(e){}else{a[0]&&(a[0]._zipIdx=o);for(c=
1;d=a[c];c++)a[c]._zipIdx!=o&&b.push(d),d._zipIdx=o}return b},H=function(a,b){var b=b||w.doc,c=b.ownerDocument||b.documentElement;r=b.contentType&&b.contentType=="application/xml"||g("opera")&&(b.doctype||c.toString()=="[object XMLDocument]")||!!c&&(g("ie")?c.xml:b.xmlVersion||c.xmlVersion);if((c=W(a)(b))&&c.nozip)return c;return ia(c)};H.filter=function(a,b,c){for(var d=[],f=G(b),f=f.length==1&&!/[^\w#\.]/.test(b)?j(f[0]):function(a){return J.indexOf(H(b,I.byId(c)),a)!=-1},e=0,g;g=a[e];e++)f(g)&&
d.push(g);return d};return H});